<div id="content">
    <h4><?php echo $this->translate("User Account Details") ?></h4>
    <div class="innerLR">

        <!-- Widget -->
        <div class="widget">

            <!-- Widget heading -->
            <div class="widget-head">
                <h4 class="heading"><?php echo $this->translate("Account Manage") ?></h4>
            </div>
            <!-- // Widget heading END -->

            <div class="widget-body">

                <!-- Table -->
                <table class="dynamicTable table table-striped table-bordered table-condensed">

                    <!-- Table heading -->
                    <thead>
                        <tr>
                            <th><?php echo $this->translate("User Name") ?></th>
                            <th><?php echo $this->translate("Address") ?></th>
                            <th><?php echo $this->translate("Balance Amount") ?></th>
                            <th><?php echo $this->translate("FPP") ?></th>
                            <th><?php echo $this->translate("Available Tickets") ?></th>
                            <th><?php echo $this->translate("Used Tickets") ?></th>
                            <th><?php echo $this->translate("Bonus Amount") ?></th>
                            <th><?php echo $this->translate("Edit") ?></th>
                        </tr>
                    </thead>
                    <!-- // Table heading END -->

                    <!-- Table body -->
                    <tbody>

                       <?php if(isset($this->userAccountDetails)): foreach ($this->userAccountDetails as $accountDetails): ?>
                        <!-- Table row -->
                        <tr class="gradeA">
                            <td><?php echo $accountDetails['user_name']; ?></td>
                            <td><?php echo $accountDetails['address']; ?></td>
                            <td><?php echo $accountDetails['balance_amt']; ?></td>
                            <td><?php echo $accountDetails['fpp']; ?></td>
                            <td><?php echo $accountDetails['available_tickets']; ?></td>
                            <td class="center"><?php echo $accountDetails['used_tickets']; ?></td>
                            <td class="center"><?php echo $accountDetails['bonus_amt']; ?></td>
                            <td class="center">
                                <a href="/admin/edit-contest/<?php echo $accountDetails['account_id']; ?>" class="btn-action glyphicons pencil btn-success"><i></i></a>
                                
                            </td>
                        </tr>
                        <!-- // Table row END -->
                        <?php endforeach; endif; ?>

                    </tbody>
                    <!-- // Table body END -->

                </table>
                <!-- // Table END -->

            </div>
        </div>
    </div>	
</div>
<script>
//    $('#menu_components3').removeClass('collapse').addClass('in collapse');
//    $('#promotion_setting_menu').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons cogwheels active');
//    $('#contest_promotion_menu').addClass('active');    
</script>
