<?php // echo $this->render('profile.phtml');  ?>

<form action="../../../samples/sample_posteddata.php" method="post">
    <textarea cols="100" id="editor1" name="editor1" rows="10">&lt;p&gt;This is some &lt;strong&gt;sample text&lt;/strong&gt;. You are using &lt;a href="http://ckeditor.com/"&gt;CKEditor&lt;/a&gt;.&lt;/p&gt;</textarea>

    <script>
       
        // Replace the <textarea id="editor1"> with an CKEditor instance.
        CKEDITOR.replace( 'editor1', {
            on: {
                focus: onFocus1,
                blur: onBlur,

                // Check for availability of corresponding plugins.
                pluginsLoaded: function( evt ) {
                    var doc = CKEDITOR.document, ed = evt.editor;
                    if ( !ed.getCommand( 'bold' ) )
                        doc.getById( 'exec-bold' ).hide();
                    if ( !ed.getCommand( 'link' ) )
                        doc.getById( 'exec-link' ).hide();
                }
            }
        });
                        

    </script>

    <p id="eMessage">
    </p>

    <div id="eButtons" style="display: none">
        <input id="exec-bold" onclick="ExecuteCommand('bold');" type="button" value="Execute &quot;bold&quot; Command">
        <input id="exec-link" onclick="ExecuteCommand('link');" type="button" value="Execute &quot;link&quot; Command">
        <input onclick="Focus();" type="button" value="Focus">
        <br><br>
        <input onclick="InsertHTML();" type="button" value="Insert HTML">
        <input onclick="SetContents();" type="button" value="Set Editor Contents">
        <input onclick="GetContents();" type="button" value="Get Editor Contents (HTML)">
        <br>
        <textarea cols="100" id="htmlArea" rows="3">&lt;h2&gt;Test&lt;/h2&gt;&lt;p&gt;This is some &lt;a href="/Test1.html"&gt;sample&lt;/a&gt; HTML code.&lt;/p&gt;</textarea>
        <br>
        <br>
        <input onclick="InsertText();" type="button" value="Insert Text">
        <br>
        <textarea cols="100" id="txtArea" rows="3">   First line with some leading whitespaces.

Second line of text preceded by two line breaks.</textarea>
        <br>
        <br>
        <input onclick="CheckDirty();" type="button" value="checkDirty()">
        <input onclick="ResetDirty();" type="button" value="resetDirty()">
    </div>
</form>

