 
<style>
    .wrapper footer {
        display: block !important;
    }

    footer {
        display: none;
    }

    .wrapper {
        padding-bottom: 0px !important;
    }

    .table.table-responsive td {
        font-size: 13px;
        padding: 18px 8px;
    }
    
    .table.table-responsive.no-tpadding td {
        padding: 8px;
    }
    
    .no-border {
        border: none !important;
    }

    .sorting, .sorting_asc, sorting_desc {
        font-size: 12px;
        /*font-weight: lighter !important;*/
        vertical-align: middle !important;
        width: 11% !important;
    }
    
    #dataTableLarge td {
        text-align: center;
    }
    
    #dataTableLarge td.text-left {
        text-align: left !important;
    }
</style>  
<div class="main-container">

    <div class="padding-md m-bottom-md">
        <div class="row" id ="paymentalertmessage" style="display:none;">
            <div class="col-md-6 col-md-offset-3 text-center">
                <div class="well bg-danger">
                    <h4><b>Table is not updated a with the values give, Please try again</b></h4>
                </div>
            </div>
        </div>
        
        <h3 class="header-text m-top-lg"><?php echo $this->translate("Teacher Payment Formulae") ?></h3>

        <div class="row">
            <div class="col-md-4 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong><?php echo $this->translate("Teacher Payment") ?></strong>
                    </div>
                    <div class="panel-body">
                        <table class="table table-responsive no-tpadding">
                            <tbody>
                                <tr>
                                    <td class="no-border"><?php echo $this->translate("No.of Monthly paid students") ?></td>
                                    <td class="no-border"><?php if(isset($this->monthlypaiduserscount)){ echo $this->monthlypaiduserscount;}?></td>
                                </tr>
                                  <tr>
                                    <td class="no-border"><?php echo $this->translate("No.of Yearly paid students") ?></td>
                                    <td class="no-border"><?php if(isset($this->yearlypaiduserscount)){ echo $this->yearlypaiduserscount;}?></td>
                                </tr>
                                
                                 <tr>
                                    <td class="no-border"><?php echo $this->translate("Sum of Monthly paid students") ?></td>
                                    <td class="no-border"><?php if(isset( $this->getmonthlysum)){ echo  $this->getmonthlysum;}?></td>
                                </tr>
                                
                                  <tr>
                                    <td class="no-border"><?php echo $this->translate("Sum of Yearly paid students") ?></td>
                                    <td class="no-border"><?php if(isset($this->getyearlysum)){ echo  $this->getyearlysum;}?></td>
                                </tr>
                                 <tr>
                                    <td class="no-border"><?php echo $this->translate(" Total Sum of Monthly and Yearly") ?></td>
                                    <td class="no-border" data-asset="<?php if(isset($this->totalsum)){ echo $this->totalsum ;}?>" id ="totalassetvalue"><?php if(isset($this->totalsum)){ echo  round($this->totalsum , 2);}?></td>
                                </tr>
                                <tr>
                                    <td>% to divide</td>
                                    <td class="form-group" style="width: 32%;">
                                        <select  id="devide_per" class="form-control" aria-controls="dataTableLarge" name="dataTableLarge_length">
                                            <option value="10" <?php if(($this->commissiondata['percentage_divide']) && ($this->commissiondata['percentage_divide'] ==10)){ echo "selected";}?>>10%</option>
                                            <option value="20" <?php if(($this->commissiondata['percentage_divide']) && ($this->commissiondata['percentage_divide'] ==20)){ echo "selected";}?>>20%</option>
                                            <option value="30" <?php if(($this->commissiondata['percentage_divide']) && ($this->commissiondata['percentage_divide'] ==30)){ echo "selected";}?>>30%</option>
                                            <option value="40" <?php if(($this->commissiondata['percentage_divide']) && ($this->commissiondata['percentage_divide'] ==40)){ echo "selected";}?>>40%</option>
                                            <option value="50" <?php if(($this->commissiondata['percentage_divide']) && ($this->commissiondata['percentage_divide'] ==50)){ echo "selected";}?>>50%</option>
                                            <option value="60" <?php if(($this->commissiondata['percentage_divide']) && ($this->commissiondata['percentage_divide'] ==60)){ echo "selected";}?>>60%</option>
                                            <option value="70" <?php if(($this->commissiondata['percentage_divide']) && ($this->commissiondata['percentage_divide'] ==70)){ echo "selected";}?>>70%</option>
                                            <option value="80" <?php if(($this->commissiondata['percentage_divide']) && ($this->commissiondata['percentage_divide'] ==80)){ echo "selected";}?>>80%</option>
                                            <option value="90" <?php if(($this->commissiondata['percentage_divide']) && ($this->commissiondata['percentage_divide'] ==90)){ echo "selected";}?>>90%</option>
                                            <option value="100 <?php if(($this->commissiondata['percentage_divide']) && ($this->commissiondata['percentage_divide'] ==100)){ echo "selected";}?>">100%</option>
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td><?php echo $this->translate("Total value of the Commission to divide between teachers") ?></td>
                                    <td id='totalamount' data-totalamount ="<?php echo (($this->totalsum *($this->commissiondata['percentage_divide']))/100);?>"><?php echo round(($this->totalsum *($this->commissiondata['percentage_divide']))/100,2);?></td>
                                    <?php $moneyy=($this->totalsum *($this->commissiondata['percentage_divide']))/100;  ?> 
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong><?php echo $this->translate("Weight average") ?></strong>
                    </div>
                    <div class="panel-body" style="min-height: 383px;">
                        <table class="table table-responsive">
                            <tbody>
                                <tr>
                                    <td class="no-border"><?php echo $this->translate("Wight Average Nr. Students") ?></td>
                                    <td class="no-border" style="width: 32%;">
                                        <select name="dataTableLarge_length" aria-controls="dataTableLarge" id="stu_per" class="form-control">
                                             <option value="0"<?php if(($this->commissiondata['students_weightage']) && ($this->commissiondata['students_weightage'] ==10)){ echo "selected";}?>>0%</option>
                                            <option value="10" <?php if(($this->commissiondata['students_weightage']) && ($this->commissiondata['students_weightage'] ==10)){ echo "selected";}?>>10%</option>
                                            <option value="20"<?php if(($this->commissiondata['students_weightage']) && ($this->commissiondata['students_weightage'] ==20)){ echo "selected";}?>>20%</option>
                                            <option value="30" <?php if(($this->commissiondata['students_weightage']) && ($this->commissiondata['students_weightage'] ==30)){ echo "selected";}?>>30%</option>
                                            <option value="40" <?php if(($this->commissiondata['students_weightage']) && ($this->commissiondata['students_weightage'] ==40)){ echo "selected";}?>>40%</option>
                                            <option value="50" <?php if(($this->commissiondata['students_weightage']) && ($this->commissiondata['students_weightage'] ==50)){ echo "selected";}?>>50%</option>
                                            <option value="60" <?php if(($this->commissiondata['students_weightage']) && ($this->commissiondata['students_weightage'] ==60)){ echo "selected";}?>>60%</option>
                                            <option value="70" <?php if(($this->commissiondata['students_weightage']) && ($this->commissiondata['students_weightage'] ==70)){ echo "selected";}?>>70%</option>
                                            <option value="80" <?php if(($this->commissiondata['students_weightage']) && ($this->commissiondata['students_weightage'] ==80)){ echo "selected";}?>>80%</option>
                                            <option value="90" <?php if(($this->commissiondata['students_weightage']) && ($this->commissiondata['students_weightage'] ==90)){ echo "selected";}?>>90%</option>
                                            <option value="100" <?php if(($this->commissiondata['students_weightage']) && ($this->commissiondata['students_weightage'] ==100)){ echo "selected";}?>>100%</option>
                                           
                                        </select>
                                    </td>
                                </tr>
                                <tr>
                                    <td><?php echo $this->translate("Wight Average Nr. Project") ?></td>
                                    <td style="width: 32%;">
                                        <select name="dataTableLarge_length" aria-controls="dataTableLarge" id="pro_per" class="form-control">
                                            <option value="0" <?php if(($this->commissiondata['projects_weightage']) && ($this->commissiondata['projects_weightage'] ==0)){ echo "selected";}?>>0%</option>
                                            <option value="10" <?php if(($this->commissiondata['projects_weightage']) && ($this->commissiondata['projects_weightage'] ==10)){ echo "selected";}?>>10%</option>
                                            <option value="20" <?php if(($this->commissiondata['projects_weightage']) && ($this->commissiondata['projects_weightage'] ==20)){ echo "selected";}?>>20%</option>
                                            <option value="30" <?php if(($this->commissiondata['projects_weightage']) && ($this->commissiondata['projects_weightage'] ==30)){ echo "selected";}?>>30%</option>
                                            <option value="40" <?php if(($this->commissiondata['projects_weightage']) && ($this->commissiondata['projects_weightage'] ==40)){ echo "selected";}?>>40%</option>
                                            <option value="50" <?php if(($this->commissiondata['projects_weightage']) && ($this->commissiondata['projects_weightage'] ==50)){ echo "selected";}?>>50%</option>
                                            <option value="60" <?php if(($this->commissiondata['projects_weightage']) && ($this->commissiondata['projects_weightage'] ==60)){ echo "selected";}?>>60%</option>
                                            <option value="70" <?php if(($this->commissiondata['projects_weightage']) && ($this->commissiondata['projects_weightage'] ==70)){ echo "selected";}?>>70%</option>
                                            <option value="80" <?php if(($this->commissiondata['projects_weightage']) && ($this->commissiondata['projects_weightage'] ==80)){ echo "selected";}?>>80%</option>
                                            <option value="90" <?php if(($this->commissiondata['projects_weightage']) && ($this->commissiondata['projects_weightage'] ==90)){ echo "selected";}?>>90%</option>
                                            <option value="100" <?php if(($this->commissiondata['projects_weightage']) && ($this->commissiondata['projects_weightage'] ==100)){ echo "selected";}?>>100%</option>
                                        </select>
                                    </td>
                                </tr>

                                <tr>
                                    <td></td>
                                    <td id="wight_total"></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong><?php echo $this->translate("Array for satisfaction") ?></strong>
                    </div>
                    <div class="panel-body" style="min-height: 383px;">
                        <table class="table table-responsive">
                            <thead>
                                <tr>
                                    <th colspan="2"><?php echo $this->translate("Array for satisfaction") ?></th>
                                    <th><?php echo $this->translate("Apply") ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><?php echo $this->translate("Above of") ?></td>
                                    <td>90%</td>
                                    <td>100%</td>
                                </tr>
                                <tr>
                                    <td><?php echo $this->translate("Above of") ?></td>
                                    <td>80%</td>
                                    <td>95%</td>
                                </tr>
                                <tr>
                                    <td><?php echo $this->translate("Above of") ?></td>
                                    <td>70%</td>
                                    <td>90%</td>
                                </tr>
                                <tr>
                                    <td><?php echo $this->translate("Below of") ?></td>
                                    <td>70%</td>
                                    <td>85%</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group">
                    <button class="btn btn-info" id ="previewchanges">Preview</button>
                    <button class="btn btn-success" id ="applychanges">Apply</button>
                </div>
            </div>
        </div>
        
        <h3 class="header-text m-top-lg"><?php echo $this->translate("Teacher Payment Estimation") ?></h3>
        <div class="row" style="margin-top: 5%;">
            <div class="col-md-12 col-lg-12">
                <table class="table tableLarge table-responsive" id="dataTableLarge">
                    <thead>
                        <th><?php echo $this->translate("Name of teacher") ?></th>
                        <th><?php echo $this->translate("Class Name") ?></th>
                        <th><?php echo $this->translate("Total No. of Students") ?></th>
                        <th><?php echo $this->translate("Total No. of Projects") ?></th>
                        <th><?php echo $this->translate("% of Satisfaction") ?></th>
                        <th><?php echo $this->translate("Index % by nr Student") ?></th>
                        <th><?php echo $this->translate("Index % by nr Project") ?></th>
                        <th><?php echo $this->translate("Sum Total index %") ?></th>
                        <th><?php echo $this->translate("Value without satisfaction") ?></th>
                        <th><?php echo $this->translate("Value with satisfaction") ?></th>
                        <th><?php echo $this->translate("Leftover") ?></th>
                    </thead>
                    <tbody>
<?php
if(isset($this->teacherformulaevalues)){
                        foreach ( $this->teacherformulaevalues as $value) {
                          ?>
                            <tr>
                                <td class="text-left"><?php echo $value['first_name'].$value['last_name'] ?></td>
                                <td><?php echo $value['class_title'] ?></td>
                                <td><?php echo $value['studentcount'] ?></td>
                                <td><?php echo $value['projectcount'] ?></td>
                                <td><?php echo round($value['avgreviewspercentage'],2) . '%'; ?></td>
                                <td><?php echo round($value['pernoofstudents'],2). '%';?></td>
                                <td><?php echo round($value['pernoofprojects'],2). '%';?></td>
                                <td><?php echo round($value['sumtotalper'],2). '%';?></td>
                                <td><?php echo round($value['valuewidoutsatifaction'],2);?></td>
                                <td><?php echo round($value['valuewidsatifaction'],2);?></td>
                                <td><?php echo round($value['leftover'],2);?></td>
                                
                            </tr>
<?php }  } ?>

                    </tbody>
                </table>
            </div>

        </div>

    </div>
</div>







<script>
    $(function() {
        $('#dataTableLarge').dataTable({
            "bAutoWidth": true,
            "bLengthChange": true,
            "bFilter": true,
            "sScrollX": "200%",
            "bScrollCollapse": true,
            "bSort": true,
            "bPaginate": true
        });
    });
</script>

<script>

//deV : Priyanka varanasi
//desc: to get the value of commision given to students on change
//date:24/9/2015

$(document).on('change','#devide_per',function(){
    
    var commissionper = $('#devide_per').val();
    
    var valuetodivide = $('#totalassetvalue').attr('data-asset');
    
    var commissionval = (valuetodivide * commissionper)/100;
    
    $('#totalamount').attr('data-totalamount','');
    $('#totalamount').html('');
    
    $('#totalamount').attr('data-totalamount',commissionval);
    $('#totalamount').html(commissionval);

});

//dev: priyanka varanasi
//desc: to change the percentage of select option but make it equal to 100 %
//date : 24/9/2015

$(document).on('change','#stu_per',function(){
    
    var stuvalue = $('#stu_per').val();
    var provalue = 100 - stuvalue ;
    $("#pro_per").val(provalue);
    
});

$(document).on('change',"#pro_per",function(){
    
    var projvalue = $('#pro_per').val();
    var studvalue = 100 - projvalue ;
    $("#stu_per").val(studvalue);
    
});


//dev: priyanka varanasi
//desc: to change show the preview of changed values
//date : 24/9/2015
$(document).on('click','#previewchanges',function(){
    $('#preloader').show();
   var dividepercentage =  $('#devide_per').val();
   var totalamount =  $('#totalamount').attr('data-totalamount');
   var studentpercentage =  $('#stu_per').val();
   var projectpercentage =  $('#pro_per').val();
   var tablenew = $('#dataTableLarge').dataTable();
   
  $.ajax({
      url:'/admin/get-paid-students',
      type:'POST',
      datatype : 'json',
      data:{
       dividepercentage :  dividepercentage,
        totalamount  :totalamount,
        studentpercentage :studentpercentage,
        projectpercentage :projectpercentage
      },
      success:function(response){
          console.log(response);
          var res = jQuery.parseJSON(response);
          if(res.code === 200){
            $('#preloader').hide();
        tablenew.fnClearTable();
                    var i=0;
                    $.each(res.data,function( index, value ) {
                        i++;
                      var a = "";
                      var b = " ";
                      var c = " ";
                      var d = "";
                      var e =" ";
                      var f =" ";
                      var g =" ";
                      var h =" ";
                      var i =" ";
                      var j =" ";
                      var k =" ";
                      
                      a = value.first_name +" "+ value.last_name;
                      b =value.class_title;
                      c = value.studentcount;
                      d = value.projectcount;
                      e =value.avgreviewspercentage;
                      f =(value.pernoofstudents).toFixed(2);
                      g =(value.pernoofprojects).toFixed(2);
                      h = value.sumtotalper;
                      i = (value.valuewidoutsatifaction).toFixed(2);
                      j =(value.valuewidsatifaction).toFixed(2);
                      k =value.leftover;
                     
                 tablenew.fnAddData([a,b,c,d,e,f,g,h,i,j,k]); 
                  if(i===res.length)
                    {
                         tablenew.draw();
                    }
                    });
                   
                 
             }else{
             $('#preloader').hide();
             $('#paymentalertmessage').show();
                 
             }
          
      }
      
             
      });

});

setTimeout(function() {
    $('#paymentalertmessage').fadeOut('slow');
}, 3000);

//dev: priyanka varanasi
//desc: to uopdate the changed values in db
//date : 25/9/2015
$(document).on('click','#applychanges',function(){
    $('#preloader').show();
   var dividepercentage =  $('#devide_per').val();
   var totalamount =  $('#totalamount').attr('data-totalamount');
   var studentpercentage =  $('#stu_per').val();
   var projectpercentage =  $('#pro_per').val();
   
  $.ajax({
      url:'/admin/teacher-formula',
      type:'POST',
      datatype : 'json',
      data:{
       dividepercentage :  dividepercentage,
        totalamount  :totalamount,
        studentpercentage :studentpercentage,
        projectpercentage :projectpercentage
        
      },
      success:function(response){
          var res = jQuery.parseJSON(response);
        if(res.code===200){
         window.location.reload(); 
        }else{
           $('#preloader').hide(); 
            $('#paymentalertmessage').show();
           
        }  
          
      }
      
             
      });

});

</script>
