<div class="main-container">
				<div class="padding-md m-bottom-md">
				
<h3 class="header-text m-top-lg"><?php echo $this->translate("Payment Details") ?></h3>

					<table class="table table-striped" id="dataTable">
						<thead>
							<tr>
								<th><button><?php echo $this->translate("S.No") ?></button></th>
								<th><button><?php echo $this->translate("First Name") ?></button></th>
								<th><button><?php echo $this->translate("Amount") ?></button> </th>
                                                                <th><button><?php echo $this->translate("Payment ID") ?></button></th>
                                                                <th><button><?php echo $this->translate("Pay Method") ?></button></th>
								<th><button><?php echo $this->translate("Transaction Id") ?></button></th>
<!--								<th>Transcation Date</th>-->
								<th><button><?php echo $this->translate("Plan Status") ?></button></th>
							</tr>
						</thead>
						<tbody>
                                                    <?php if(isset($this->paymentdetails)) {
                                                    $sno=1;    
                                                    foreach($this->paymentdetails as $value){
                                                        
                                                    
                                                        ?>
                                                    
							<tr>
								<td><?php echo $sno; ?></td>
								<td><?php echo $value['first_name']; ?>&nbsp;&nbsp;<?php echo $value['last_name']; ?></td>
								<td><?php echo "$".$value['amount']; ?></td>
                                                                <td><?php echo $value['payment_id']; ?></td>
								<td><?php if($value['payment_method']==0) { echo "pagar"; } else if($value['payment_method']==1){ echo "Boleto"; } ?></td>
								<td><?php echo $value['transaction_id']; ?></td>
<!--								<td>Jan 08,2015</td>-->
                                                                <?php if($value['status']=="paid"){ ?>
								<td><span class="label label-success"><?php echo $value['status']; ?></span></td>
                                                                <?php } else { ?>
                                                                <td><span class="label label-warning"><?php echo $value['status']; ?></span></td>
                                                                <?php } ?>
							</tr>
                                                        
                                                        <?php 
                                                         $sno++;
                                                        } 
                                                       
                                                    }
                                                    ?>
							
						</tbody>
					</table>
				</div><!-- ./padding-md -->
			</div><!-- /main-container -->

		</div><!-- /wrapper -->

		<a href="#" class="scroll-to-top hidden-print"><i class="fa fa-chevron-up fa-lg"></i></a>
		
	

		<script>
                  
			$(function()	{
			    $('#dataTable').dataTable();
			});
		</script>
