			<div class="main-container">
				<div class="padding-md">
					

					<div class="row">
						<!-- ./ col -->
						<div class="col-lg-12 col-md-12 col-sm-12">
							<div class="row bg-white padding-xs">
                            <h3 class="header-text m-top-lg"><?php echo $this->translate("Teacher Payment Details") ?></h3>
								<table class="table table-striped" id="dataTable">
						<thead>
							<tr>
								<th><?php echo $this->translate("Pick") ?></th>
								<th><?php echo $this->translate("Teacher Name") ?></th>
								<th><?php echo $this->translate("No.of Students Monthly") ?></th>
								<th><?php echo $this->translate("No.of Students Yearly") ?></th>
                                <th><?php echo $this->translate("Total Students") ?></th>
                                <th><?php echo $this->translate("Total Amount") ?></th>
								<th><?php echo $this->translate("Status") ?></th>
                                
							</tr>
						</thead>
						<tbody>
                                                    <?php
                                                   $result= $this->result;
                                                   $count=0;
                                                   if(isset($result)){
                                                    foreach ($result as $key => $value) {
                                                       
                                                    
                                                            ?>
                                                    
							<tr>
								<td>  	<div class="custom-checkbox">
											<input type="checkbox" id="inlineFormCheckbox<?php echo $count;?>">
											<label for="inlineFormCheckbox<?php echo $count;?>"></label>
										</div>
										
									</td>
                                    <td><?php echo $value['name'] ?></td>
								<td><?php echo $value['monthly_user'] ?></td>
								<td><?php echo $value['yearly']?></td>
								<td><?php echo $value['total_user'] ?></td>
                                <td><?php echo $value['amount'] ?>$</td>
                                <td><span class="label label-success">UnPaid</span></td>
								
							</tr><?php $count++; } } ?>
								
						</tbody>
					</table>
                    
							</div><!-- ./row -->
						</div><!-- ./ col -->
					</div><!-- ./row -->
				</div><!-- ./padding-md -->
			</div><!-- /main-container -->
			
		</div><!-- /wrapper -->

		<a href="#" class="scroll-to-top hidden-print"><i class="fa fa-chevron-up fa-lg"></i></a>
		
	    <!-- Le javascript
	    ================================================== -->
	    <!-- Placed at the end of the document so the pages load faster -->
		
		<!-- Jquery -->
		<script src="js/jquery-1.11.1.min.js"></script>
		
		<!-- Bootstrap -->
	    <script src="js/bootstrap.min.js"></script>
	  

		<!-- Slimscroll -->
		<script src='js/jquery.slimscroll.min.js'></script>

<!-- Datatable -->
		<script src='js/jquery.dataTables.min.js'></script>
		<script src='js/uncompressed/dataTables.bootstrap.js'></script>
			
		<!-- Simplify -->
		<script src="js/simplify/simplify.js"></script>
			<!-- Popup Overlay -->
		<script src='js/jquery.popupoverlay.min.js'></script>

		<!-- Modernizr -->
		<script src='js/modernizr.min.js'></script>

<script>
			$(function()	{
			    $('#dataTable').dataTable();
			});
		</script>
		
	
  	</body>

</html>
