<div class="main-container">
    <div class="padding-md m-bottom-md">
        <h3 class="header-text m-top-lg"><?php echo $this->translate("Classes Unit Details") ?></h3>
        <table class="table table-striped" id="dataTable" class="display">
            <thead>
                <tr>     
                    <th><?php echo $this->translate("S.no") ?></th>
                    <th><?php echo $this->translate("Class Unit title") ?></th>
                    <th><?php echo $this->translate("Username") ?></th>
                   <th colspan="2"><?php echo $this->translate("Edit/Delete") ?></th>

                </tr>
            </thead>

            <tbody>

                <?php
                if (isset($this->videoinfo)) {
                    $i = 1;
                    foreach ($this->videoinfo as $value) {
                      
                        ?>
                        <tr>
                            <td><?php echo $i; ?></td>
                            <td><a href ="/admin/class-unit-videos/<?php echo $value['class_unit_id']; ?>"style="cursor:pointer;color:#008000;"><?php if (isset($value['class_unit_titile'])) {
                    echo $value['class_unit_titile'];
                } ?></a></td>
                            <td><?php if (isset($value['first_name'])) {
                    echo $value['first_name'];
                } ?></td>
                         <td colspan="2"><a href="/admin/edit-class-units/<?php echo $value['class_unit_id']; ?>"><button class="btn btn-success btn-sm"><?php echo $this->translate("Edit") ?></button></a>
                                <a class="delete_<?php echo $value['class_unit_id']; ?>" data-val="<?php echo $value['class_unit_id']; ?>" id ="delete" ><button class="btn btn-danger btn-sm"><?php echo $this->translate("Delete") ?></button></td>
                        </tr>    

        <?php $i++; ?>  
        <?php
    }
}
?>

            </tbody>
        </table>
    </div><!-- ./padding-md -->
</div><!-- /main-container -->

<a href="#" class="scroll-to-top hidden-print"><i class="fa fa-chevron-up fa-lg"></i></a>

<script type="text/javascript" language="javascript">

    $(document).ready(function() {

        $('#dataTable').dataTable({
        });
    });


//dev:priyanka varanasi
//desc:To delete the class

    $(document.body).on('click', '#delete', function() {

        var deleteid = $(this).attr('data-val');

        $("#Deleteclassunitmodal").modal('show');
        $(document.body).on('click', '#ok', function() {
            $("#Deleteclassunitmodal").modal('hide');
            if (deleteid) {
                $.ajax({
                    url: '../class-ajax-handler',
                    type: 'POST',
                    dataType : 'json',
                    data: {
                        method : 'classunitdelete',
                        classunitid : deleteid
                    },
                    success: function(response) {
                     
                        if (response) {
                            $('.'+"delete_"+response).parent().parent().remove();
                        }
                    }

                });
            }
        });
    });
</script>
