<div class="main-container">
    <div class="padding-md m-bottom-md">
        <h3 class="header-text m-top-lg"><?php echo $this->translate("Classes Video Details") ?></h3>
        <table class="table table-striped" id="dataTable" class="display">
            <thead>
                <tr>     
                    <th><?php echo $this->translate("S.no") ?></th>
                    <th><?php echo $this->translate("Class Video Title") ?></th>
                    <th><?php echo $this->translate("Video Cover image") ?></th>
                    <th><?php echo $this->translate("Username") ?></th>
                    <th><?php echo $this->translate("Transcode Status") ?></th>
                    <th colspan="2"><?php echo $this->translate("Edit/Delete") ?></th>

                </tr>
            </thead>

            <tbody>

                <?php
                if (isset($this->videos)) {
                    $i = 1;
                    foreach ($this->videos as $value) {
                      
                        ?>
                        <tr>
                            <td><?php echo $i; ?></td>
                            <td><a style="cursor:pointer;color:#008000;" id="clsvideo" data-val="<?php  if (isset($value['video_id'])){echo $value['video_id'];} ?>"><?php if (isset($value['class_video_title'])) {
                    echo $value['class_video_title'];
                    } ?></a></td>
                            <?php if(isset($value['cover_image'])){?>
                            <td><img src="<?php echo ($value['cover_image']);?>" class="img-responsive prj_image"  alt=""/></td>
                            <?php }else{?>
                               
                             <td><img src="<?php echo ($value['video_thumb_url']);?>" class="img-responsive prj_image"  alt=""/></td>   
                            <?php }?>
                            <td><?php if (isset($value['first_name'])) {
                    echo $value['first_name'];
                } ?></td>
                           
                            <td><?php if (isset($value['transcode_status'])) {
                    echo $value['transcode_status'];
                } ?></td>
                            <td colspan="2"><a href="/admin/edit-class-video/<?php echo $value['video_id']; ?>"><button class="btn btn-success btn-sm"><?php echo $this->translate("Edit") ?></button></a>
                                <a class="delete_<?php echo $value['video_id']; ?>" data-val="<?php echo $value['video_id']; ?>" id ="delete" ><button class="btn btn-danger btn-sm"><?php echo $this->translate("Delete") ?></button></td>
                        </tr>    

        <?php $i++; ?>  
        <?php
    }
}
?>

            </tbody>
        </table>
    </div><!-- ./padding-md -->
</div><!-- /main-container -->

<a href="#" class="scroll-to-top hidden-print"><i class="fa fa-chevron-up fa-lg"></i></a>

<script type="text/javascript" language="javascript">

    $(document).ready(function() {

        $('#dataTable').dataTable({
        });
    });


    $(document).on('click', '#clsvideo', function() {

        var videoid = $(this).attr('data-val');

        if (videoid) {
            $('#videoplay').modal('show');
            $('.videoclass').html('<div class="display"><iframe id="player1" src="//player.vimeo.com/video/' + videoid + '?api=1&player_id=player1" width="622" height="354" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></div>');
            } 
    });



//dev:priyanka varanasi
//desc:To delete the class

    $(document.body).on('click', '#delete', function() {

        var deleteid = $(this).attr('data-val');

        $("#Deletevideomodal").modal('show');
        $(document.body).on('click', '#ok', function() {
            $("#Deletevideomodal").modal('hide');
            if (deleteid) {
                $.ajax({
                    url: '../class-ajax-handler',
                    type: 'POST',
                    dataType : 'json',
                    data: {
                        method : 'classvideodelete',
                        classvideoid : deleteid
                    },
                    success: function(response) {
                        if (response) {
                            $('.'+"delete_"+response).parent().parent().remove();
                        }
                    }

                });
            }
        });
    });
</script>
