<div class="main-container bg-white margin0">
    <div class="padding-md m-top-md">
        <ul class="breadcrumb">
            <li><span class="primary-font"><i class="icon-home"></i></span><a href="#"><?php echo $this->translate(" Class") ?></a></li>
            <li><?php echo $this->translate("Create Class") ?></li>
        </ul>
        <div class="container-fluid">
            <div class="row well">
                <div class="col-md-6 col-md-offset-3" style="margin-top:3%;">
                    <form action="/admin/teachdetail" method="post" class="fomr-horizontal" >
                        <div class="form-group">
                            <input type="text" class="form-control" name="teach" placeholder="Enter the Class" />
                        </div>
                        <div class="form-group text-center">
                            <input type="submit" class="btn btn-success" name="submit" value="create class" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>