<div class="main-container">
				<div class="padding-md">
					
					<h3 class="m-left-xs header-text m-top-lg"><?php echo $this->translate("Classes Details") ?></h3>
<div class="smart-widget m-top-lg widget-dark-blue">
						<div class="smart-widget-header">
							<?php echo $this->translate("Edit Class Details") ?>
							
						</div>
						<div class="smart-widget-inner">
							<div class="smart-widget-hidden-section">
								<ul class="widget-color-list clearfix">
									<li data-color="widget-dark" style="background-color:#20232b;"></li>
									<li data-color="widget-dark-blue" style="background-color:#4c5f70;"></li>
									<li data-color="widget-blue" style="background-color:#23b7e5;"></li>
									<li data-color="widget-green" style="background-color:#2baab1;"></li>
									<li data-color="widget-yellow" style="background-color:#edbc6c;"></li>
									<li data-color="widget-orange" style="background-color:#fbc852;"></li>
									<li data-color="widget-red" style="background-color:#e36159;"></li>
									<li data-color="widget-purple" style="background-color:#7266ba;"></li>
									<li data-color="widget-light-grey" style="background-color:#f5f5f5;"></li>
									<li data-color="reset" style="background-color:#fff;"></li>
								</ul>
							</div>
							<div class="smart-widget-body">
								<form class="form-horizontal" name="editclassform" method="POST" >
									<div class="form-group">
										<label class="col-lg-2 control-label" for="UserName"><?php echo $this->translate("UserName") ?></label>
										<div class="col-lg-10">
                                                                                        <input <?php if(isset($this->classes)){?> value="<?php echo ($this->classes['first_name']);}?>" readonly type="text" placeholder="<?php echo $this->translate("UserName") ?>" name="UserName" id="UserName" class="form-control">
										</div><!-- /.col -->
									</div><!-- /form-group -->
									<div class="form-group">
										<label class="col-lg-2 control-label" for="ClassTitle"><?php echo $this->translate("Class Title") ?></label>
										<div class="col-lg-10">
											<input <?php if(isset($this->classes)){?> value="<?php echo ($this->classes['class_title']);}?>"type="text" name="classtitle" placeholder="<?php echo $this->translate("Class Title") ?>" id="classtitle" class="form-control">
										</div><!-- /.col -->
									</div><!-- /form-group -->
                                    <div class="form-group">
										<label class="col-lg-2 control-label" for="classdescription"><?php echo $this->translate("Class Description") ?></label>
				                                           <div>
    
        <textarea id="MyToolbar4" name="MyToolbar5"><?php if(isset($this->classes)){echo ($this->classes['class_description']);}?></textarea>
       <script>CKEDITOR.replace( 'MyToolbar5', {
    toolbar: 'MyToolbar5',
    uiColor: '#9AB8F3',
                    filebrowserBrowseUrl :'js/ckeditor/filemanager/browser/default/browser.html?Connector=http://www.mixedwaves.com/filemanager_in_ckeditor/js/ckeditor/filemanager/connectors/php/connector.php',
                    filebrowserImageBrowseUrl : "",
                    filebrowserFlashBrowseUrl :'js/ckeditor/filemanager/browser/default/browser.html?Type=Flash&amp;Connector=http://www.mixedwaves.com/filemanager_in_ckeditor/js/ckeditor/filemanager/connectors/php/connector.php',
		    filebrowserUploadUrl  :'http://www.mixedwaves.com/filemanager_in_ckeditor/js/ckeditor/filemanager/connectors/php/upload.php?Type=File',
		    filebrowserImageUploadUrl : 'http://www.mixedwaves.com/filemanager_in_ckeditor/js/ckeditor/filemanager/connectors/php/upload.php?Type=Image',
		    filebrowserFlashUploadUrl : 'http://www.mixedwaves.com/filemanager_in_ckeditor/js/ckeditor/filemanager/connectors/php/upload.php?Type=Flash'
});</script>
<!--        <input name="submit" type="submit" value="Submit" />-->
 
</div><!-- /form-group -->
                                    <div class="form-group">
										<label class="col-lg-2 control-label" for="classtags"><?php echo $this->translate("Class Tags") ?></label>
										<div class="col-lg-10">
                                                                                    <input type="text" name="classtags" placeholder="Class Tags" <?php if(isset($this->classes)){?> value="<?php echo ($this->classes['class_tags']);}?>"id="classtags" class="form-control">
<!--										<a href="#" class="blog-tag">Website</a>
                                        <a href="#" class="blog-tag">Tutorials</a>
                                        <a href="#" class="blog-tag">Modern</a>
                                        <a href="#" class="blog-tag">Flat</a>-->
										</div><!-- /.col -->
									</div><!-- /form-group -->
                                   
                                      <div class="form-group">
										<label class="col-lg-2 control-label" for="password"><?php echo $this->translate("Publish Status") ?></label>
										<div class="col-lg-10">
                                                                                   <select class="form-control"  name="classstatus">
                                                                                                <option class="hidden" selected="selected" value="<?php if($this->classes['publish_status']==0){ echo 0 ;}else if($this->classes['publish_status']== 1){echo 1;}else{ echo 2;}?>"><?php if(isset($this->classes)){ if($this->classes['publish_status']==0){ echo "Published" ;}else if($this->classes['publish_status']== 1){echo "Saved in Drafts";}else{ echo "Pending";}}?> </option>
												<option value="0">Published</option>
												<option value="1"  >Saved in Drafts</option>
												<option value="2"  >Pending</option>
											
											</select>                       
										</div><!-- /.col -->
									</div><!-- /form-group -->
								     
									<div class="form-group">
										<div class="col-lg-offset-2 col-lg-10">
											<button class="btn btn-success btn-sm" type="submit"><?php echo $this->translate("Save Class") ?></button>
                                                                                        &nbsp;&nbsp;&nbsp;
                                                                                        <a href="/admin/classesdetails" class="btn btn-danger btn-sm"><?php echo $this->translate("Cancel") ?></a>
										</div><!-- /.col -->
									</div><!-- /form-group -->
								
							</div>
                                                                        </form>
						</div><!-- ./smart-widget-inner -->
					</div>
		        </div><!-- ./padding-md -->
			</div><!-- /main-container -->
		</div><!-- /wrapper -->

		<a href="#" class="scroll-to-top hidden-print"><i class="fa fa-chevron-up fa-lg"></i></a>
			