<div class="main-container">
    <div class="padding-md">
        <ul class="breadcrumb">
            <li><span class="primary-font"><i class="icon-home"></i></span><a href="#"><?php echo $this->translate(" Gamification Panel") ?></a></li>
            <li><?php echo $this->translate("Achievements") ?></li>
        </ul>
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title header-text no-m-bottom">
                   <?php echo $this->translate(" Gamification Panel") ?>
                </div>
            </div>
        </div
        <div class="row m-top-md">
            <div class="col-md-12">
                <div class="panel">
                    <div class="panel-heading">
                        <h4> <?php echo $this->translate("Achievements") ?></h4>
                        <button class="btn btn-success btn-sm addlevel pull-right"><?php echo $this->translate("Add Badge") ?></button>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th><?php echo $this->translate("SL no") ?></th>
                                        <th><?php echo $this->translate("Likes required") ?></th>
                                        <th><?php echo $this->translate("Classes Completed") ?></th>
                                        <th><?php echo $this->translate("Projects Created") ?></th>
                                        <th><?php echo $this->translate("Comments") ?></th>
                                        <th><?php echo $this->translate("Discussion") ?></th>
                                        <th><?php echo $this->translate("Badge Title") ?></th>
                                        <th><?php echo $this->translate("Badge Link") ?></th>
                                        <th><?php echo $this->translate("invite") ?></th>
                                        <th><?php echo $this->translate("Free signup") ?></th>
                                        <th><?php echo $this->translate("Premium signup") ?></th>
                                        <th><?php echo $this->translate("Edit/Delete") ?></th>
                                    </tr>
                                </thead>
                                <tbody id="tablebody">
                                    <?php if(isset($this->Achievement)){ $count = 1; foreach($this->Achievement as $value){?>
                                    <tr>
                                        <td id='<?php echo $value['achevementsid'] ?>'><?php echo $count; ?></td>
                                        <td><p><?php echo $value['likes'] ?></p><input type='text' hidden></td>
                                        <td><p><?php echo $value['classes_completed'] ?></p><input type='text' hidden></td>
                                        <td><p><?php echo $value['projects_created'] ?></p><input type='text' hidden></td>
                                        <td><p><?php echo $value['comments'] ?></p><input type='text' hidden></td>
                                        <td><p><?php echo $value['discussion'] ?></p><input type='text' hidden></td>
                                        <td><p><?php echo $value['badge_title'] ?></p><input type='text' hidden></td>
                                        <td><p><?php echo $value['badge_link'] ?></p><input type='text' hidden><form enctype="multipart/form-data" style='display:none' id='<?php echo "useravatarform".$value['achevementsid']; ?>' class="col-lg-9 col-md-8 col-sm-7"><input type="file"><button class='btn btn-success btn-sm saveimage' iid="<?php echo $value['achevementsid'] ?>">save Image</button></form></td>
                                        <td><p><?php echo $value['invite'] ?></p><input type='text' hidden></td>
                                        <td><p><?php echo $value['freesignup'] ?></p><input type='text' hidden></td>
                                        <td><p><?php echo $value['premiumsignup'] ?></p><input type='text' hidden></td>
                                        <td><button class="btn btn-success btn-sm savechanges" style='display:none'><?php echo $this->translate("save") ?></button> <button class="btn btn-success btn-sm editrow"><?php echo $this->translate("Edit") ?></button> <button class="btn btn-danger btn-sm deleterow" lid='<?php echo $value['achevementsid'] ?>'><?php echo $this->translate("Delete") ?></button><button class="btn btn-danger btn-sm Cancel" style='display:none'><?php echo $this->translate("Cancel") ?></button></td>
                                    </tr>
                                    <?php $count++;} } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- ./padding-md -->
<a href="#" class="scroll-to-top hidden-print"><i class="fa fa-chevron-up fa-lg"></i></a>
<script>
   var length =  <?php echo $count; ?>;  
    var count = length+0;
     allfun();
    $(document).ready(function(){
    
       $("#Gamificationpanalli").addClass("active");
        $("#Gamificationpanalli").addClass("openable active open");
        $("#gamificationpanelul").show();
        $("#achivementsli").addClass("active");
       allfun();
    });

function allfun(){
$(".editrow").on('click',function(){
   var premimummember = $(this).parent().prev().children()['0'].innerHTML;
   var freemember = $(this).parent().prev().prev().children()['0'].innerHTML;
   var invite = $(this).parent().prev().prev().prev().children()['0'].innerHTML; 
   var link = $(this).parent().prev().prev().prev().prev().children()['0'].innerHTML;
   var badgetitle = $(this).parent().prev().prev().prev().prev().prev().children()['0'].innerHTML;
   var discussion = $(this).parent().prev().prev().prev().prev().prev().prev().children()['0'].innerHTML;
   var comments = $(this).parent().prev().prev().prev().prev().prev().prev().prev().children()['0'].innerHTML;
   var projects_created = $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().children()['0'].innerHTML;
   var classes_completed = $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().children()['0'].innerHTML;
   var likes = $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().prev().children()['0'].innerHTML;
   $(this).parent().prev().children().hide();
   $(this).parent().prev().children().next().show();
   $(this).parent().prev().children().next().attr("value", premimummember);
   $(this).parent().prev().prev().children().hide();
   $(this).parent().prev().prev().children().next().show();
   $(this).parent().prev().prev().children().next().attr("value", freemember);
   $(this).parent().prev().prev().prev().children().hide();
   $(this).parent().prev().prev().prev().children().next().show();
   $(this).parent().prev().prev().prev().children().next().attr("value", invite);
   $(this).parent().prev().prev().prev().prev().children().hide();
   $(this).parent().prev().prev().prev().prev().children().next().show();
   $(this).parent().prev().prev().prev().prev().children().next().attr("value", link);
   $(this).parent().prev().prev().prev().prev().prev().children().hide();
   $(this).parent().prev().prev().prev().prev().prev().children().next().show();
   $(this).parent().prev().prev().prev().prev().prev().children().next().attr("value", badgetitle);
   $(this).parent().prev().prev().prev().prev().prev().prev().children().hide();
   $(this).parent().prev().prev().prev().prev().prev().prev().children().next().show();
   $(this).parent().prev().prev().prev().prev().prev().prev().children().next().attr("value", discussion);
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().children().hide();
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().children().next().show();
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().children().next().attr("value", comments);
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().children().hide();
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().children().next().show();
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().children().next().attr("value", projects_created);
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().children().hide();
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().children().next().show();
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().children().next().attr("value", classes_completed);
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().prev().children().hide();
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().prev().children().next().show();
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().prev().children().next().attr("value", classes_completed);
   $(this).prev().show();
   $(this).next().hide();
   $(this).hide();
   $(this).next().next().show();
   if($(this).next().next().hasClass("Cancel")){
       
   }else{
       $(this).next().next().addClass("Cancel");
        $(this).next().next().removeClass("Cancelnewrow");
   }
   
});
$(".savechanges").on('click',function(){
    var presentitem = $(this);
    var premimummember = $(this).parent().prev().children().next().val();
    var freemember = $(this).parent().prev().prev().children().next().val();
    var invite = $(this).parent().prev().prev().prev().children().next().val();
    var link = $(this).parent().prev().prev().prev().prev().children().next().val();
    var badgetitle = $(this).parent().prev().prev().prev().prev().prev().children().next().val();
    var discussion = $(this).parent().prev().prev().prev().prev().prev().prev().children().next().val();
    var comments = $(this).parent().prev().prev().prev().prev().prev().prev().prev().children().next().val();
    var projects_created = $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().children().next().val();
    var classes_completed = $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().children().next().val();
    var likes = $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().prev().children().next().val();
    var id = $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().prev().prev().attr("id");
   
        $.ajax({
                url: '/admin-ajax-handler',
                type: 'post',
                dataType: 'json',
                data: {
                    method:'achivements',
                    link:link,
                    badgetitle:badgetitle,
                    discussion:discussion,
                    comments:comments,
                    projects_created:projects_created,
                    classes_completed:classes_completed,
                    likes:likes,
                    premimummember:premimummember,
                    freemember:freemember,
                    invite:invite,
                    id:id
                },
                success: function (response) {
                    if(response != 1 && response != 0){
                        //presentitem.parent().prev().prev().prev().prev().prev().prev().prev().prev().children()['0'].innerHTML = response;
                       presentitem.parent().prev().prev().prev().prev().prev().prev().prev().prev().attr("id",response);
                       presentitem.next().next().attr("lid",response)
                    }
                    presentitem.parent().prev().children()['0'].innerHTML = premimummember;
                    presentitem.parent().prev().prev().children()['0'].innerHTML = freemember;
                    presentitem.parent().prev().prev().prev().children()['0'].innerHTML = invite;
                    presentitem.parent().prev().prev().prev().prev().children()['0'].innerHTML = link;
                    presentitem.parent().prev().prev().prev().prev().prev().children()['0'].innerHTML = badgetitle;
                    presentitem.parent().prev().prev().prev().prev().prev().prev().children()['0'].innerHTML = discussion;
                    presentitem.parent().prev().prev().prev().prev().prev().prev().prev().children()['0'].innerHTML = comments;
                    presentitem.parent().prev().prev().prev().prev().prev().prev().prev().prev().children()['0'].innerHTML = projects_created;
                    presentitem.parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().children()['0'].innerHTML = classes_completed;
                    presentitem.parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().prev().children()['0'].innerHTML = likes;
                    
                    presentitem.parent().prev().children().show();
                    presentitem.parent().prev().children().next().hide();
                    presentitem.parent().prev().prev().children().show();
                    presentitem.parent().prev().prev().children().next().hide();
                    presentitem.parent().prev().prev().prev().children().show();
                    presentitem.parent().prev().prev().prev().children().next().hide();
                    presentitem.parent().prev().prev().prev().prev().children().show();
                    presentitem.parent().prev().prev().prev().prev().children().next().hide();
                    presentitem.parent().prev().prev().prev().prev().prev().children().show();
                    presentitem.parent().prev().prev().prev().prev().prev().children().next().hide();
                    presentitem.parent().prev().prev().prev().prev().prev().prev().children().show();
                    presentitem.parent().prev().prev().prev().prev().prev().prev().children().next().hide();
                    presentitem.parent().prev().prev().prev().prev().prev().prev().prev().children().show();
                    presentitem.parent().prev().prev().prev().prev().prev().prev().prev().children().next().hide();
                    presentitem.parent().prev().prev().prev().prev().prev().prev().prev().prev().children().show();
                    presentitem.parent().prev().prev().prev().prev().prev().prev().prev().prev().children().next().hide();
                    presentitem.parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().children().show();
                    presentitem.parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().children().next().hide();
                    presentitem.parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().prev().children().show();
                    presentitem.parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().prev().children().next().hide();
                    presentitem.parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().prev().children().next().next().hide();
                    presentitem.hide();
                    presentitem.next().show();
                    presentitem.next().next().show();
                    presentitem.next().next().next().hide();
                }
               
                });
    
});
$('.deleterow').on('click',function(){
   var presentitem = $(this);
   var id = $(this).attr('lid');
   $.ajax({
                url: '/admin-ajax-handler',
                type: 'post',
                dataType: 'json',
                data: {
                    method:'deleteachivements',
                    id:id
                },
                success: function (response) {
                       presentitem.parent().parent().hide();
                       count -- ;
                }
                });
});

$('.saveimage').on('click',function(e){
        e.preventDefault();
        var thisitem = $(this);
        var iid =  $(this).attr('iid');
         var formData = new FormData();
         formData.append('file', $('#'+'useravatarform'+iid)[0][0].files[0]);
          $.ajax({
            url: '/admin/imageuploadhandler',
            type: 'POST',
            dataType: 'text',
            async: false,
            cache: false,
            contentType: false,
            processData: false,
            data: formData,
            success: function (response) {
                thisitem.parent().prev().attr("value",response);
                if(response != "error"){
                     thisitem.parent().hide();
                }
                
            }
        });
    });

}
$(document.body).on('click','.Cancel',function(){
     count -- ;
   $(this).parent().prev().children().show();
   $(this).parent().prev().children().next().hide();
   $(this).parent().prev().prev().children().show();
   $(this).parent().prev().prev().children().next().hide();
   $(this).parent().prev().prev().prev().children().show();
   $(this).parent().prev().prev().prev().children().next().hide();
   $(this).parent().prev().prev().prev().prev().children().show();
   $(this).parent().prev().prev().prev().prev().children().next().hide();
   $(this).parent().prev().prev().prev().prev().prev().children().show();
   $(this).parent().prev().prev().prev().prev().prev().children().next().hide();
   $(this).parent().prev().prev().prev().prev().prev().prev().children().show();
   $(this).parent().prev().prev().prev().prev().prev().prev().children().next().hide();
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().children().show();
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().children().next().hide();
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().children().show();
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().children().next().hide();
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().children().show();
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().children().next().hide();
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().prev().children().show();
   $(this).parent().prev().prev().prev().prev().prev().prev().prev().prev().prev().prev().children().next().hide();
   $(this).prev().show();
   $(this).prev().prev().show();
    $(this).prev().prev().prev().hide();
   $(this).hide();
   
});

$('.addlevel').on('click',function(){
    var row = "<tr><td id=''>"+count+"</td><td><p></p><input type='text'></td><td><p></p><input type='text'></td><td><p></p><input type='text'></td><td><p></p><input type='text'></td><td><p></p><input type='text'></td><td><p></p><input type='text'></td><td><p></p><input type='text'><form enctype='multipart/form-data' class='col-lg-9 col-md-8 col-sm-7' id='useravatarform' ><input type='file' name='badgeimage' id='badgeimage'><button class='btn btn-success btn-sm saveimage' iid=''>save Image</button></form></td><td><p></p><input type='text'></td><td><p></p><input type='text'></td><td><p></p><input type='text'></td><td><button class='btn btn-success btn-sm savechanges'>save</button> <button class='btn btn-success btn-sm editrow' style='display:none'>Edit</button> <button class='btn btn-danger btn-sm deleterow' lid='' style='display:none' >Delete</button><button class='btn btn-danger btn-sm Cancelnewrow'>Cancel</button></td></tr>";
    count ++;
    $('#tablebody').append(row);
    allfun();
});

$(document.body).on('click','.Cancelnewrow',function(){
   $(this).parent().parent().hide();
});


</script>
<script>
    $(document).ready(function () {

        setTimeout(function () {
            $('.opennotificationGreen').fadeOut("slow");
        }, 500);
    });
   </script>