<div class="main-container">


    <div class="smart-widget m-top-lg widget-dark-blue">
        <div class="smart-widget-header"style="margin-top:-33px">
          <?php echo $this->translate("Change Password") ?> 

        </div>
        <div class="smart-widget-inner">
            <div class="smart-widget-hidden-section">
                <ul class="widget-color-list clearfix">
                    <li data-color="widget-dark" style="background-color:#20232b;"></li>
                    <li data-color="widget-dark-blue" style="background-color:#4c5f70;"></li>
                    <li data-color="widget-blue" style="background-color:#23b7e5;"></li>
                    <li data-color="widget-green" style="background-color:#2baab1;"></li>
                    <li data-color="widget-yellow" style="background-color:#edbc6c;"></li>
                    <li data-color="widget-orange" style="background-color:#fbc852;"></li>
                    <li data-color="widget-red" style="background-color:#e36159;"></li>
                    <li data-color="widget-purple" style="background-color:#7266ba;"></li>
                    <li data-color="widget-light-grey" style="background-color:#f5f5f5;"></li>
                    <li data-color="reset" style="background-color:#fff;"></li>
                </ul>
            </div>
            <div class="smart-widget-body">
                <form class="form-horizontal" name="edituser"  id="edituser" method="POST" enctype="multipart/form-data">
                    <div class="form-group">
                        <label class="col-lg-2 control-label"  for="firstName"><?php echo $this->translate("Current Password") ?></label>
                        <div class="col-lg-10">
                            <input type="password" placeholder=" <?php echo $this->translate("Current Password") ?>" value=""  name="currentpassword" id="currentpassword" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-lg-2 control-label" for="LastName"><?php echo $this->translate("New Password") ?></label>
                        <div class="col-lg-10">
                           <input type="password" placeholder="<?php echo $this->translate("New Password") ?>" value=""  name="newpassword" id="newpassword" class="form-control">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label" for="password"><?php echo $this->translate("Confirm Password") ?></label>
                        <div class="col-lg-10">
                            <input type="password" placeholder="<?php echo $this->translate("Confirm Password") ?>" value=""  name="confirmpassword" id="confirmpassword" class="form-control">
                        </div>
                   </div>


                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-success btn-sm" type="submit"><?php echo $this->translate("Change Password") ?></button>
                                
                                &nbsp;&nbsp;&nbsp;
                                <a href="<?php $this->baseUrl(); ?>/admin/dashboard"><button class="btn btn-danger btn-sm"><?php echo $this->translate("Cancel") ?></button></a>
                            </div><!-- /.col -->
                        </div><!-- /form-group -->
                          <?php if(isset($this->message)){?>  <div class="opennotificationGreen" style="background-color:#66B45E; height: 40px; padding: 3%; margin-top: 7%; text-align: center;" align="left" >
                                                    <p><font face="verdana" id="data" color="black"><?php echo ($this->message);?></font></p>
                                                </div>
                          <?php }?>
                </form>
            </div><!-- ./smart-widget-inner -->
        </div>
    </div><!-- ./padding-md -->
</div><!-- /main-container -->
<!-- /wrapper -->

<a href="#" class="scroll-to-top hidden-print"><i class="fa fa-chevron-up fa-lg"></i></a>
<script>
$(document).ready(function(){
    setTimeout(function(){
        $('.opennotificationGreen').fadeOut("slow");
    },500);
});
</script>