<div class="main-container">
				<div class="padding-md">
					
                    <div class="row">
						<div class="col-sm-6">
                            <h3><?php echo $this->translate("DASHBOARD") ?></h3>  
						</div>
                    </div>
                    <div class="row">
                    	<div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        	
                            <div class="widget-stat">
								<span class="stat-icon bg-warning bounceIn animation-delay3"><i class="block icon-1222"></i></span>
								<div class="stat-info">
									<small class="text-muted text-upper"><?php echo $this->translate("Total of Premium Member") ?></small>
                                                                        <span><?php if(isset($this->ptotal)){echo $this->ptotal;}?></span>
								</div>
							</div>
                            
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        	 <div class="widget-stat">
								<span class="stat-icon bg-info bounceIn animation-delay3"><i class="block icon-1222"></i></span>
								<div class="stat-info">
									<small class="text-muted text-upper"><?php echo $this->translate("Total of Free Member") ?></small>
                                                                        <span><?php if(isset($this->ftotal)){echo $this->ftotal;} ?></span>
								</div>
							</div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        	 <div class="widget-stat">
								<span class="stat-icon bg-purple bounceIn animation-delay3"><i class="block icon-1222"></i></span>
								<div class="stat-info">
									<small class="text-muted text-upper"><?php echo $this->translate("Total of Premium Months") ?></small>
                                                                        <span><?php if(isset($this->mtotal)){echo $this->mtotal ;} ?></span>
								</div>
							</div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        	 <div class="widget-stat">
								<span class="stat-icon bg-purple bounceIn animation-delay3"><i class="block icon-1222"></i></span>
								<div class="stat-info">
									<small class="text-muted text-upper"><?php echo $this->translate("Total of Premiums Yearly") ?></small>
                                                                        <span><?php if(isset($this->ytotal)){echo $this->ytotal ;} ?></span>
								</div>
							</div>
                        </div>
                    </div>        
                          
                    <div class="row m-top-md">
                          <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        	 <div class="widget-stat">
								<span class="stat-icon bg-primary bounceIn animation-delay3"><i class="block icon-1222"></i></span>
								<div class="stat-info">
									<small class="text-muted text-upper"><?php echo $this->translate("Number of Trials User") ?></small>
                                                                        <span><?php if(isset($this->tusers)){echo $this->tusers;} ?></span>
								</div>
							</div>
                        </div>
                    
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        	 <div class="widget-stat">
								<span class="stat-icon bg-success bounceIn animation-delay3"><i class="block icon-1222"></i></span>
								<div class="stat-info">
									<small class="text-muted text-upper"><?php echo $this->translate("Number of Teacher") ?></small>
                                                                        <span><?php if(isset($this->totalteachercount)){echo $this->totalteachercount ;}?></span>
								</div>
							</div>
                            
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        	 <div class="widget-stat">
								<span class="stat-icon bg-purple bounceIn animation-delay3"><i class="block icon-1222"></i></span>
								<div class="stat-info">
									<small class="text-muted text-upper"><?php echo $this->translate("Total de classes") ?></small>
                                                                        <span><?php if(isset($this->countofclass)){echo $this->countofclass;}?></span>
								</div>
							</div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                        	 <div class="widget-stat">
								<span class="stat-icon bg-info bounceIn animation-delay3"><i class="block icon-1222"></i></span>
								<div class="stat-info">
									<small class="text-muted text-upper"><?php echo $this->translate("Total de Projects") ?></small>
                                                                        <span><?php if(isset($this->countofproj)){echo $this->countofproj; }?></span>
								</div>
							</div>
                        </div>
                    </div> 
                                    
                    <div class="row">
                    	<div class="col-md-12">
                        	<div class="smart-widget">
								<div class="smart-widget-header border-bottom">
									<?php echo $this->translate("CONVERSION") ?> 
								</div>
								<div class="smart-widget-inner">
									<div class="smart-widget-body no-padding">
										<div class="padding-md">
											<div>
                                            	<div>
                                                    <span class="m-right-sm"><i class="fa fa-circle totalvisit-link m-right-sm" style="color:rgba(143,19,253,0.2)"></i><?php echo $this->translate("Total Visit") ?></span>
                                                    <span><i class="fa fa-circle freeuser-link m-right-sm" style="color:rgba(156,43,108,1)"></i><?php echo $this->translate("Free User") ?></span>
                                                    <span><i class="fa fa-circle trialuser-link m-right-sm" style="color:rgba(255,0,0,0.2)"></i><?php echo $this->translate("Trial User") ?></span>
                                                    <span><i class="fa fa-circle premium-link m-right-sm" style="color:rgba(17,156,220,1)"></i><?php echo $this->translate("Premium User") ?></span>
                                                    <ul class="list-unstyled list-inline pull-right">
                                                        <li class="no-padding"><a id="dayg" ><?php echo $this->translate("Days") ?></a></li>
                                                        <li  class="no-padding">- <a id="weekg"><?php echo $this->translate("Weeks") ?></a></li>
                                                        <li class="no-padding">- <a id="monthg"><?php echo $this->translate("Months") ?></a></li>
                                                    </ul>
                                                </div>
                                                <div class="m-top-sm" style="height:300px;width:100%">
                                                    <canvas id="studentCanvas" style="height:300px; width:100%;"></canvas>
                                                </div>
                                            </div>
										</div>
		
									</div>
								</div><!-- ./smart-widget-inner -->
							</div>
                        </div>
                    </div>
                     
                     
                     <div class="row">
                     	<div class="col-md-12">
                          <div class="smart-widget">
                          		<div class="smart-widget-header border-bottom">
								<?php echo $this->translate("CLASSES POPULARITY") ?>	
                                </div>
								<div class="smart-widget-inner">
                                	<div class="smart-widget-body no-padding">
										<div class="padding-md">
                                        	<div class="table-responsive">
                                              <table id="batatables123" class="table no-m-bottom bg-headblue">
                                                <thead class="">
                                                  <tr class="marginTB-sm">
                                                    <th class=""><?php echo $this->translate("Class") ?></th>
                                                    <th class=""><?php echo $this->translate("Teacher") ?></th>
                                                    <th class=""><?php echo $this->translate("Total of student") ?></th>
                                                    <th class=""><?php echo $this->translate("Total of Project") ?></th>
                                                    <th class=""><?php echo $this->translate("Popularity") ?></th>
                                                      <th class=""><?php echo $this->translate("Time") ?></th>
                                                  </tr>
                                                  </thead>
                                                <tbody>
                                                 <?php if(isset($this->classes)){  foreach ($this->classes as $value) { ?>
      
  
                                                  <tr>
                                                    <td><?php echo  $value['class_title']?></td>
                                                    <td><?php echo $value['first_name']?></td>
                                                    <td><?php echo $value['allstudents']?></td>
                                                    <td><?php echo $value['allprojectcount'] ?></td>
                                                    <td><div class="progress progress-striped active" style="height:8px; margin:5px 0 0 0;">
                                                            <div class="progress-bar" style="width:<?php echo $value['popularity'];?>">
                                                                <span class="sr-only"><?php echo $value['popularity'];?>%<?php echo $this->translate("Complete") ?> </span>
                                                            </div>
                                                        </div></td>
                                                         <td><label class="bg-purple label-bg"><?php echo gmdate("H:i:s", $value['duration']);?> hrs</label></td>
                                                  </tr>
                                                  <?php }} ?>
                                                  </tbody>
                                                </table>
                                  			</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                          </div>
                        </div>
                     </div>
                           
                     
		
				</div>
</div><!-- /wrapper -->

		<a href="#" class="scroll-to-top hidden-print"><i class="fa fa-chevron-up fa-lg"></i></a>
		
	   


		<script>
                   
    $('#batatables123').dataTable();
    $('#dashboard').addClass('active');
			$(function()	{
				$('.chart').easyPieChart({
					easing: 'easeOutBounce',
					size: '140',
					lineWidth: '7',
					barColor: '#7266ba',
					onStep: function(from, to, percent) {
						$(this.el).find('.percent').text(Math.round(percent));
					}
				});

				$('.sortable-list').sortable();

				$('.todo-checkbox').click(function()	{
					
					var _activeCheckbox = $(this).find('input[type="checkbox"]');

					if(_activeCheckbox.is(':checked'))	{
						$(this).parent().addClass('selected');					
					}
					else	{
						$(this).parent().removeClass('selected');
					}
				
				});

				//Delete Widget Confirmation
				$('#deleteWidgetConfirm').popup({
					vertical: 'top',
					pagecontainer: '.container',
					transition: 'all 0.3s'
				});
			});

					
		</script>
        <script>
			$('[data-toggle="popover"]').popover({ trigger: "hover focus" });

			$(window).on("load resize",function(){
					var width=$(window).width();
					
					if( width <=500){
						$('.followers').removeClass('col-xs-5').addClass('col-xs-11')
						$('.new-project').children().removeClass('col-xs-6').addClass('col-xs-12')
						
					}
					if( width > 500){
						$('.followers').removeClass('col-xs-11').addClass('col-xs-5')
						$('.new-project').children().removeClass('col-xs-12').addClass('col-xs-6')
					}
					if( width < 768){
						$('.followers').removeClass('margin-15px').addClass('margin-sm')
						$('.dashboard-brief').children().removeClass('col-xs-6').addClass('col-xs-12');	
					}
					if( width >= 768){
						$('.followers').removeClass('margin-sm').addClass('margin-15px')
						$('.dashboard-brief').children().removeClass('col-xs-12').addClass('col-xs-6');	
					}
					
					
				});
				
			
			
		</script>
        
        <script>
            window.onload = function(){
                $("#dayg").trigger("click");
            }
            
            $("#dayg").click(function(){
//            var arr=  <?php // echo json_decode($this->daysreport->labels); ?> 
             var labels = new Array();
             var data1 = new Array();
             var data2 = new Array();
             var data3 = new Array();
             var data4 = new Array();
    <?php foreach($this->daysreport["labels"] as $key => $val){ ?>
        labels.push('<?php echo $val; ?>');
    <?php } ?>
        
         <?php foreach($this->daysreport["free"] as $key => $val){ ?>
        data1.push('<?php echo $val; ?>');
    <?php } ?>
        
         <?php foreach($this->daysreport["premium"] as $key => $val){ ?>
        data2.push('<?php echo $val; ?>');
    <?php } ?>
        <?php foreach($this->daysreport["trailing"] as $key => $val){ ?>
        data3.push('<?php echo $val; ?>');
    <?php } ?>
        <?php foreach($this->daysreport["total"] as $key => $val){ ?>
        data4.push('<?php echo $val; ?>');
    <?php } ?>
        
//             var arr= ["January","February","March","April","May","June","July"];

		var lineChartData1 = {
                   
                    
			labels : labels,
			datasets : [
				{
					label: "My First dataset",
					fillColor : "rgba(156,43,108,0.2)",
					strokeColor : "rgba(156,43,108,1)",
					pointColor : "rgba(156,43,108,1)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(220,220,220,1)",
					data: data1
				},
				{
					label: "My Second dataset",
					fillColor : "rgba(17,156,220,0.2)",
					strokeColor : "rgba(17,156,220,1)",
					pointColor : "rgba(17,156,220,1)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(151,187,205,1)",
					data: data2
				},
                                {
					label: "My Second dataset",
					fillColor : "rgba(255,0,0,0.1)",
					strokeColor : "rgba(255,0,0,0.2)",
					pointColor : "rgba(255,0,0,0.2)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(151,187,205,1)",
					data: data3
				},
                                {
					label: "My Second dataset",
					fillColor : "rgba(143,19,253,0.1)",
					strokeColor : "rgba(143,19,253,0.2)",
					pointColor : "rgba(143,19,253,0.2)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(151,187,205,1)",
					data: data4
				}
			]

		}
 if(window.myLine)
             window.myLine.destroy();
          
	
                 var ctx = document.getElementById("studentCanvas").getContext("2d");
                
		window.myLine = new Chart(ctx).Line(lineChartData1, {
			responsive: true
		});
	
    });
</script>
 <script>

        $("#weekg").click(function(){
            
        
        var labels = new Array();
             var data1 = new Array();
             var data2 = new Array();
             var data3 = new Array();
             var data4 = new Array();
    <?php foreach($this->weeksreport["labels"] as $key => $val){ ?>
        labels.push('<?php echo $val; ?>');
    <?php } ?>
        
         <?php foreach($this->weeksreport["free"] as $key => $val){ ?>
        data1.push('<?php echo $val; ?>');
    <?php } ?>
        
         <?php foreach($this->weeksreport["premium"] as $key => $val){ ?>
        data2.push('<?php echo $val; ?>');
    <?php } ?>
        <?php foreach($this->weeksreport["trailing"] as $key => $val){ ?>
        data3.push('<?php echo $val; ?>');
    <?php } ?>
        <?php foreach($this->weeksreport["total"] as $key => $val){ ?>
        data4.push('<?php echo $val; ?>');
    <?php } ?>
        
//             var arr= ["January","February","March","April","May","June","July"];

		var lineChartData2 = {
                   
                    
			labels : labels,
			datasets : [
				{
					label: "My First dataset",
					fillColor : "rgba(156,43,108,0.2)",
					strokeColor : "rgba(156,43,108,1)",
					pointColor : "rgba(156,43,108,1)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(220,220,220,1)",
					data: data1
				},
				{
					label: "My Second dataset",
					fillColor : "rgba(17,156,220,0.2)",
					strokeColor : "rgba(17,156,220,1)",
					pointColor : "rgba(17,156,220,1)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(151,187,205,1)",
					data: data2
				},
                                {
					label: "My Second dataset",
					fillColor : "rgba(255,0,0,0.1)",
					strokeColor : "rgba(255,0,0,0.2)",
					pointColor : "rgba(255,0,0,0.2)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(151,187,205,1)",
					data: data3
				},
                                {
					label: "My Second dataset",
					fillColor : "rgba(143,19,253,0.1)",
					strokeColor : "rgba(143,19,253,0.2)",
					pointColor : "rgba(143,19,253,0.2)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(151,187,205,1)",
					data: data4
				}
			]

		}

	 if(window.myLine)
             window.myLine.destroy();
		
                var ctx = document.getElementById("studentCanvas").getContext("2d");
               
		window.myLine = new Chart(ctx).Line(lineChartData2, {
			responsive: true
		});
	
      
        });



	</script>
        
        
        <script>

        $("#monthg").click(function(){
            
        
        var labels = new Array();
             var data1 = new Array();
             var data2 = new Array();
             var data3 = new Array();
             var data4 = new Array();
    <?php foreach($this->monthsreport["labels"] as $key => $val){ ?>
        labels.push('<?php echo $val; ?>');
    <?php } ?>
        
         <?php foreach($this->monthsreport["free"] as $key => $val){ ?>
        data1.push('<?php echo $val; ?>');
    <?php } ?>
        
         <?php foreach($this->monthsreport["premium"] as $key => $val){ ?>
        data2.push('<?php echo $val; ?>');
    <?php } ?>
        <?php foreach($this->monthsreport["trailing"] as $key => $val){ ?>
        data3.push('<?php echo $val; ?>');
    <?php } ?>
        <?php foreach($this->monthsreport["total"] as $key => $val){ ?>
        data4.push('<?php echo $val; ?>');
    <?php } ?>
        
//             var arr= ["January","February","March","April","May","June","July"];

		var lineChartData2 = {
                   
                    
			labels : labels,
			datasets : [
				{
					label: "My First dataset",
					fillColor : "rgba(156,43,108,0.2)",
					strokeColor : "rgba(156,43,108,1)",
					pointColor : "rgba(156,43,108,1)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(220,220,220,1)",
					data: data1
				},
				{
					label: "My Second dataset",
					fillColor : "rgba(17,156,220,0.2)",
					strokeColor : "rgba(17,156,220,1)",
					pointColor : "rgba(17,156,220,1)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(151,187,205,1)",
					data: data2
				},
                                {
					label: "My Second dataset",
					fillColor : "rgba(255,0,0,0.1)",
					strokeColor : "rgba(255,0,0,0.2)",
					pointColor : "rgba(255,0,0,0.2)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(151,187,205,1)",
					data: data3
				},
                                {
					label: "My Second dataset",
					fillColor : "rgba(143,19,253,0.1)",
					strokeColor : "rgba(143,19,253,0.2)",
					pointColor : "rgba(143,19,253,0.2)",
					pointStrokeColor : "#fff",
					pointHighlightFill : "#fff",
					pointHighlightStroke : "rgba(151,187,205,1)",
					data: data4
				}
			]

		}

	 if(window.myLine)
             window.myLine.destroy();
		
                var ctx = document.getElementById("studentCanvas").getContext("2d");
               
		window.myLine = new Chart(ctx).Line(lineChartData2, {
			responsive: true
		});
	
      
        });



	</script>
 