<!DOCTYPE html>
<html lang="en">
  	
<head>
	    <meta charset="utf-8">
	    <title>Fashion Learn</title>
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <meta name="description" content="">
	    <meta name="author" content="">

	    <!-- Bootstrap core CSS -->
	    <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
		
		<!-- Font Awesome -->
		<link href="/assets/css/font-awesome.min.css" rel="stylesheet">

		<!-- ionicons -->
		<link href="/assets/css/ionicons.min.css" rel="stylesheet">
		
		<!-- Animate -->
		<link href="/assets/css/animate.min.css" rel="stylesheet">

		<!-- Web Fonts -->
		<link href="/assets/css/styles.css" rel="stylesheet">

		
		<link href="/assets/css/fashionlearn-admin.css" rel="stylesheet">
		
       
        	
  	</head>

  	<body class="overflow-hidden index-bg">
		<div class="wrapper preload no-padding">
			
			
        <div class="sign-in-inner padding-md">
					<div class="login-brand m-bottom-md text-center">
						<img src="/assets/images/Fashionlearn(Logo-1-png).png" class="img-responsive center-block" alt="Logo"/>
					</div>

					<form name="adminlogin" id="adminlogin" method="post">
						<div id="signin" class="form-group m-bottom-md">
							<input type="text" required  name="username" id="username" class="form-control" placeholder="<?php echo $this->translate("Email Address") ?>">
						</div>
						<div class="form-group">
                                                    <input type="password" required name="password" id="password" class="form-control" placeholder="<?php echo $this->translate("Password") ?>">
						</div>

<!--						<div class="form-group">
							<div class="custom-checkbox">
								<input type="checkbox" id="chkRemember">
								<label for="chkRemember"></label>
							</div>
							<?php echo $this->translate("Remember me") ?>
						</div>-->
<span style="color: red"><?php if(isset($this->error)) echo "invalid username/password" ?></span>

						<div class="m-top-md p-top-sm">
							<button class="btn btn-success block" id="login"><?php echo $this->translate("Sign in") ?></button>
						</div>
                                             <?php if (isset($this->empty)) { ?>
                        <div>
                            <p style="background-color: red"><i></i><?php echo $this->translate("Please enter your username and password ") ?>...</p>
                        </div>
                    <?php } if (isset($this->invalid)) { ?>
                        <div>
                            <p class="glyphicons restart clrError"><i></i><?php echo $this->translate("Invalid email or password") ?></p>
                        </div>
                    <?php } ?>

					</form>
				</div>    
			
			
			<!-- /main-container -->

		</div><!-- /wrapper -->

		
		
	    <!-- Le javascript
	    ================================================== -->
	    <!-- Placed at the end of the document so the pages load faster -->
		
		<!-- Jquery -->
		<script src="/assets/js/jquery.min.js"></script>
		
		<!-- Bootstrap -->
	    <script src="/assets/js/bootstrap.min.js"></script>
	  
		<!-- Flot -->
		<script src='/assets/js/jquery.flot.min.js'></script>



		
  	</body>

</html>


<script type="text/javascript">
    $(document).ready(function() {
        
//dev:priyanka varanasi
        // desc:hide and show forgot pass and admin login forms
        $(document.body).on('click', '#forgotpassord', function() {
            $('#rempassword').show();
            $('#signin').hide();

        });
        $(document.body).on('click', '#login', function() {
            $('#rempassword').hide();
            $('#signin').show();
        });

        $(document.body).on('click', '#resetmypassword', function(e) {
            var emailid = $('#email').val();
            $.ajax({
                url: '/reset-my-password',
                type: 'POST',
                dataType: 'json',
                data: {
                    email: emailid
                },
                beforeSend: function() {

                },
                success: function(response) {
             console.log(response);
             if(response){
                 $('#passerr').html(response);
                   setTimeout(function() {
                   $('#passerr').fadeOut("slow");
                   $('div').remove("#passerr");
               }, 3000); 
                 
             }
                }
            });
        })

    });
     
</script>
