<script> 
</script>
<div class="main-container">
    <div class="padding-md">
        <ul class="breadcrumb">
            <li><span class="primary-font"><i class="icon-home"></i></span><a href="#"> <?php echo $this->translate("Gamification Panel") ?></a></li>
            <li><?php echo $this->translate("Points/Scores") ?></li>
        </ul>
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title header-text no-m-bottom">
                    <?php echo $this->translate("Gamification Panel") ?>
                </div>
            </div>
        </div
        <div class="row m-top-md">
            <div class="col-md-12">
                <div class="panel">
                    <div class="panel-heading">
                        <h4><?php echo $this->translate("Points/Scores") ?></h4>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th><?php echo $this->translate("SL no") ?></th>
                                        <th><?php echo $this->translate("Name") ?></th>
                                        <th><?php echo $this->translate("Type") ?></th>
                                        <th><?php echo $this->translate("Gems") ?></th>
                                        <th><?php echo $this->translate("Points") ?></th>
                                        <th><?php echo $this->translate("Edit/Delete") ?></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php if(isset($this->points)){ $count = 1; foreach($this->points as $value){ ?>
                                    <tr>
                                        <td><?php echo $count; ?></td>
                                        <td><p><?php echo $value['name'] ?></p><input type='text' hidden></td>
                                        <td><p><?php echo $value['pointid'] ?></p><input type='text' hidden></td>
                                        <td><p><?php echo $value['gems'] ?></p><input type='text' hidden></td>
                                        <td><p><?php echo $value['points'] ?></p><input type='text' hidden></td>
                                        <td><button class="btn btn-success btn-sm savechanges" style='display:none'><?php echo $this->translate("save") ?></button> <button class="btn btn-success btn-sm editrow"><?php echo $this->translate("Edit") ?></button><button class="btn btn-success btn-sm Cancel" style='display:none'><?php echo $this->translate("Cancel") ?></button> </td>
                                    </tr>
                                    <?php $count++;} } ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- ./padding-md -->
<a href="#" class="scroll-to-top hidden-print"><i class="fa fa-chevron-up fa-lg"></i></a>
<script>
    $("#Gamificationpanalli").addClass("active");
        $("#Gamificationpanalli").addClass("openable active open");
        $("#gamificationpanelul").show();
        $("#pointsscoreli").addClass("active");
$(".editrow").on('click',function(){
   var points = $(this).parent().prev().children()['0'].innerHTML;
   var gems = $(this).parent().prev().prev().children()['0'].innerHTML;
   var typeid = $(this).parent().prev().prev().prev().children()['0'].innerHTML;
   var name = $(this).parent().prev().prev().prev().prev().children()['0'].innerHTML;
   $(this).parent().prev().prev().children().hide();
   $(this).parent().prev().prev().children().next().show();
   $(this).parent().prev().prev().children().next().attr("value", gems);
   $(this).parent().prev().children().hide();
   $(this).parent().prev().children().next().show();
   $(this).parent().prev().children().next().attr("value", points);
   $(this).prev().show();$(this).hide();
   $(this).next().show();
});
$(".savechanges").on('click',function(){
    var presentitem = $(this);
    var points = $(this).parent().prev().children().next().val();
    var gems = $(this).parent().prev().prev().children().next().val();
    var typeid = $(this).parent().prev().prev().prev().children()['0'].innerHTML;
    $.ajax({
                url: '/admin-ajax-handler',
                type: 'post',
                dataType: 'json',
                data: {
                    method:'points',
                    points:points,
                    gems:gems,
                    pointid:typeid
                },
                success: function (response) {
                   if(response == 1 || response == 0){
                       presentitem.parent().prev().children()['0'].innerHTML = points;
                       presentitem.parent().prev().prev().children()['0'].innerHTML = gems;
                       presentitem.parent().prev().prev().children().show();
                       presentitem.parent().prev().prev().children().next().hide();
                       presentitem.parent().prev().children().show();
                       presentitem.parent().prev().children().next().hide();
                       presentitem.hide();
                       presentitem.next().show();
                        presentitem.next().next().hide();
                   }
                }
                });
    
});
$('.Cancel').on('click',function(){
  $(this).parent().prev().prev().children().show();
   $(this).parent().prev().prev().children().next().hide();
   $(this).parent().prev().children().show();
   $(this).parent().prev().children().next().hide();
   $(this).prev().prev().hide();$(this).hide();
   $(this).prev().show();
});
    $(document).ready(function () {

        setTimeout(function () {
            $('.opennotificationGreen').fadeOut("slow");
        }, 500);
    });
</script>