<div class="main-container">
 <ul class="breadcrumb">
            <li><span class="primary-font"><i class="icon-home"></i></span><a href="/dashboard/admin"><?php echo $this->translate("Home") ?></a></li>
            <li><span class="primary-font"><i class="icon-home"></i></span><a href="/admin/manageusers"><?php echo $this->translate("User Details") ?></a></li>	 

        </ul>
   
    <div class="smart-widget m-top-lg widget-dark-blue">
        <div class="smart-widget-header"style="margin-top:-6px">
            <?php echo $this->translate("Edit User") ?>

        </div>
        <div class="smart-widget-inner">
            <div class="smart-widget-hidden-section">
                <ul class="widget-color-list clearfix">
                    <li data-color="widget-dark" style="background-color:#20232b;"></li>
                    <li data-color="widget-dark-blue" style="background-color:#4c5f70;"></li>
                    <li data-color="widget-blue" style="background-color:#23b7e5;"></li>
                    <li data-color="widget-green" style="background-color:#2baab1;"></li>
                    <li data-color="widget-yellow" style="background-color:#edbc6c;"></li>
                    <li data-color="widget-orange" style="background-color:#fbc852;"></li>
                    <li data-color="widget-red" style="background-color:#e36159;"></li>
                    <li data-color="widget-purple" style="background-color:#7266ba;"></li>
                    <li data-color="widget-light-grey" style="background-color:#f5f5f5;"></li>
                    <li data-color="reset" style="background-color:#fff;"></li>
                </ul>
            </div>
            <div class="smart-widget-body">
                <form class="form-horizontal" name="edituser"  id="edituser" method="POST" enctype="multipart/form-data">
                    <div class="form-group">
                        <label class="col-lg-2 control-label"  for="firstName"><?php echo $this->translate("FirstName") ?></label>
                        <div class="col-lg-10">
                            <input type="text" placeholder="<?php echo $this->translate("firstName") ?>" value="<?php if (isset($this->user)) {
    echo ($this->user['first_name']);
} ?>"  name="firstname" id="firstName" class="form-control">
                        </div><!-- /.col -->
                    </div><!-- /form-group -->
                    <div class="form-group">
                        <label class="col-lg-2 control-label" for="LastName"><?php echo $this->translate("LastName") ?></label>
                        <div class="col-lg-10">
                            <input type="text" placeholder="<?php echo $this->translate("LastName") ?>" value="<?php if (isset($this->user)) {
    echo ($this->user['last_name']);
} ?>"  name="lastname" id="LastName" class="form-control">
                        </div><!-- /.col -->
                    </div><!-- /form-group -->
                    <div class="form-group">
                        <label class="col-lg-2 control-label" for="email"><?php echo $this->translate("Email") ?></label>
                        <div class="col-lg-10">
                            <input type="email" value="<?php if (isset($this->user)) {
    echo ($this->user['email']);
} ?>"  name="email" placeholder="<?php echo $this->translate("Email") ?>" id="inputEmail1" class="form-control">
                        </div><!-- /.col -->
                    </div><!-- /form-group -->
                    <div class="form-group">
                        <label class="col-lg-2 control-label" for="password"><?php echo $this->translate("Password") ?></label>
                        <div class="col-lg-10">
                            <input type="password" placeholder="<?php echo $this->translate("Password") ?>" value="<?php if (isset($this->user)) {
    echo ($this->user['password']);
} ?>"  name="password" id="password" class="form-control">
                        </div>
                        </div><!-- /.col -->
                        <!--									</div> /form-group 
                                                            <div class="form-group">
                                                                                                        <label class="col-lg-2 control-label" for="gender">Gender</label>
                                                                                                        <div class="col-lg-10">
                                                                                                                <div class="checkbox inline-block">
                                                                                                                        <div class="custom-checkbox">
                                                                                                                                <input type="checkbox" class="checkbox-red" id="inlineCheckbox1">
                                                                                                                                <label for="inlineCheckbox1"></label>
                                                                                                                        </div>
                                                                                                                        <div class="inline-block vertical-top">
                                                                                                                                Male
                                                                                                                        </div>
                                                                                                                </div>
                                                                    <div class="checkbox inline-block">
                                                                                                                        <div class="custom-checkbox">
                                                                                                                                <input type="checkbox" id="inlineCheckbox2">
                                                                                                                                <label for="inlineCheckbox2"></label>
                                                                                                                        </div>
                                                                                                                        <div class="inline-block vertical-top">
                                                                                                                                Female
                                                                                                                        </div>
                                                                                                                </div>
                                                                                                        </div> /.col 
                                                                                                </div> /form-group -->
                        <div class="form-group">
                            <label class="col-lg-2 control-label" name="profile"for="profile"><?php echo $this->translate("User Profile Pic") ?></label>
                          <div class="col-lg-10">
                          <img id="imgprv" src="<?php echo $this->user['user_profile_pic']; ?>"  class="img-rounded pull-left" alt="" style="width:150px;">
                                <input type="file" class="pull-left" style="margin-left: 2%; margin-top: 9%;" id="file" name="fileToUpload" value="">
                            </div><!-- /.col -->
                        </div>
                        <!--                                    
                                                            <div class="form-group">
                                                                                                        <label class="col-lg-2 control-label" for="city">City</label>
                                                                                                        <div class="col-lg-3">
                                                                                                                <input type="text" placeholder="City" id="city" class="form-control">
                                                                                                        </div> /.col 
                                                                <label class="col-lg-2 control-label" for="zip">Zip</label>
                                                                                                        <div class="col-lg-3">
                                                                                                                <input type="text" placeholder="Zip" id="zip" class="form-control">
                                                                                                        </div> /.col 
                                                                                                </div> /form-group -->

                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-success btn-sm" type="submit"><?php echo $this->translate("Save User") ?></button>
                                &nbsp;&nbsp;&nbsp;
                                <a href="/admin/manageusers"class="btn btn-danger btn-sm"><?php echo $this->translate("Cancel") ?></a>
                               <?php if(isset($this->message)){?>
                                <span class="data" style="color:green"><h5><?php echo($this->message);?></h5></span><!-- /form-group -->
                        <?php }?>
                            </div>
                       <!-- /.col -->
                        </div>
                     
                </form>
            <!-- ./smart-widget-inner -->
        </div>
    </div><!-- ./padding-md -->
</div><!-- /main-container -->
<!-- /wrapper -->

<a href="#" class="scroll-to-top hidden-print"><i class="fa fa-chevron-up fa-lg"></i></a>


</div>
<script>
    
     $(document).ready(function() {
    $(function() {


        //Wizard Step

        $("#formWizard").steps({
            headerTag: "h2",
            bodyTag: "section",
            transitionEffect: "slideLeft",
            onStepChanging: function(event, currentIndex, newIndex) {
                if (newIndex > currentIndex) {
                    if ($('#formExample').parsley().validate('step' + newIndex)) {
                        return true;
                    }
                    else {
                        return false;
                    }
                }
                else {
                    return true;
                }

            },
            onFinished: function(event, currentIndex) {
                $('#wizardModal').modal('show')
            }

        });
    });
               
        $('#edituser').validate({
             onkeyup: function(element) {
                    $(element).valid();
                },
            rules: {
                firstname: {
                    required: true
                },
                lastname: {
                    required: true
                
                },
              email: {
                    required: true
                },
              password:{
                     required: true
               }
             
            },
    
            messages: {      
                firstname:{    
                    required: "please enter firstname"
                },
                lastname:{
                   required: "please enter lastname" 
                },
                email:{
                   required:"please enter valid email"
                },
                password:{
                    required: "*New Password is required Field",
                     minlength: "Minimum Length of password is 5"
                  }
            }
            
        });
    });
    
    
    
    $(document).ready(function(){
        setTimeout(function(){
            $('.data').fadeOut("slow");
        },5000);
    });
</script>


<script language="javascript">
var srcc=$('#imgprv').attr('src');
$(document.body).on("change","#file",function(){

var fup = document.getElementById('file');
var fileName = fup.value;
var ext = fileName.substring(fileName.lastIndexOf('.') + 1);
if(ext == "gif" || ext == "GIF" || ext == "JPEG" || ext == "jpeg" || ext == "jpg" || ext == "JPG" || ext == "png")
{
 if (this.files && this.files[0]) {
                    var reader = new FileReader();
                    reader.onload = function (e) {
                        $('#imgprv').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(this.files[0]);
                }
} 
else
{
alert("Upload Gif or Jpg images only");
fup.focus();
   $("#file").val("");
   $('#imgprv').attr('src',srcc);
return false;
}
});
</script>