<div class="main-container">
    <input hidden id="userid" type="text"  value=<?php print $this->ress["user_id"]?>>
    <input hidden id="requestid" type="text"  value=<?php print $this->res["requestid"]?>>  
 <?php 
if(isset($this->ress)&&$this->ress!="")
{
  echo "<h1>edit account<h1>";
      
 echo "<h3>previous account details<h3>";
 
 ?>
    
     <table class="table table-bordered">
                                            <tr>
                                                <td class="h6"><strong>user_id</strong></td>

                                                <td class="h5"><?php print $this->ress["user_id"]?></td>
                                            </tr> 
                                           

                                            <tr>
                                                <td class="h6"><strong>bank_code</strong></td>

                                                <td class="h5"><?php print $this->ress["bank_code"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>agency</strong></td>

                                                <td class="h5"><?php print $this->ress["agency"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>agencia_dv</strong></td>

                                                <td class="h5"><?php print $this->ress["agencia_dv"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>account_no</strong></td>

                                                <td class="h5"><?php print $this->ress["account_no"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>conta_dv</strong></td>

                                                <td class="h5"><?php print $this->ress["conta_dv"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>document_number</strong></td>

                                                <td class="h5"><?php print $this->ress["document_number"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>legal_name</strong></td>

                                                <td class="h5"><?php print $this->ress["legal_name"]?></td>
                                            </tr> 
                                         
                                        </table>
    
   
    <?php
    
    echo "<h3>requested account details<h3>";
    ?>
    <table class="table table-bordered">
                                            
         <tr>
                                                <td class="h6"><strong>user_id</strong></td>

                                                <td class="h5"><?php print $this->res["user_id"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>bank_code</strong></td>

                                                <td class="h5"><?php print $this->res["bank_code"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>agency</strong></td>

                                                <td class="h5"><?php print $this->res["agency"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>agencia_dv</strong></td>

                                                <td class="h5"><?php print $this->res["agencia_dv"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>account_no</strong></td>

                                                <td class="h5"><?php print $this->res["account_no"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>conta_dv</strong></td>

                                                <td class="h5"><?php print $this->res["conta_dv"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>document_number</strong></td>

                                                <td class="h5"><?php print $this->res["document_number"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>legal_name</strong></td>

                                                <td class="h5"><?php print $this->res["legal_name"]?></td>
                                            </tr> 
                                         
                                        </table>
    
    <button id="acc" class="btn btn-success">Accept</button>
    <button id="dec" class="btn btn-danger">Decline</button>
   
     <div id="mess" class="hidden form-group">
  <label for="comment" style="margin-left: 3%;">Reason For Declining:</label>
  <textarea style="margin-left: 3%; margin-top: 25px; width: 96%;" class="form-control" rows="5" id="comment" style="margin-left: 3%;"></textarea>
</div>
    <button style="margin-left: 84%; width: 15%;" id="send" class="btn btn-primary hidden">send</button>
    
    
<?php } else { ?>
    <h3>Account detail<h3>"
    <table class="table table-bordered">
 <tr>
                                                <td class="h6"><strong>user_id</strong></td>

                                                <td class="h5"><?php print $this->res["user_id"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>bank_code</strong></td>

                                                <td class="h5"><?php print $this->res["bank_code"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>agency</strong></td>

                                                <td class="h5"><?php print $this->res["agency"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>agencia_dv</strong></td>

                                                <td class="h5"><?php print $this->res["agencia_dv"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>account_no</strong></td>

                                                <td class="h5"><?php print $this->res["account_no"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>conta_dv</strong></td>

                                                <td class="h5"><?php print $this->res["conta_dv"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>document_number</strong></td>

                                                <td class="h5"><?php print $this->res["document_number"]?></td>
                                            </tr> 
                                            <tr>
                                                <td class="h6"><strong>legal_name</strong></td>

                                                <td class="h5"><?php print $this->res["legal_name"]?></td>
                                            </tr> 
                                         
                                        </table>
   <button id="acc" class="btn btn-success">Accept</button>
    <button id="dec" class="btn btn-danger">Decline</button>
      <div id="mess" class="hidden form-group">
  <label for="comment" style="margin-left: 3%;">Reason For Declining:</label>
  <textarea style="margin-left: 3%; margin-top: 25px; width: 96%;" class="form-control" rows="5" id="comment" style="margin-left: 3%;"></textarea>
</div>
    <button style="margin-left: 84%; width: 15%;" id="send" class="btn btn-primary hidden">send</button>
    
<?php }?>
    

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

</div>


<script>
    
    
    $("#dec").click(function(){
     $("#acc").hide(); 
     $("#dec").hide();
      $("#mess").removeClass("hidden");
   $("#send").removeClass("hidden"); 
        
        
        
    });
</script>


<script>
    
    
    $("#send").click(function(){
     var comment=$("#comment").val(); 
     var method="reject";
     var user_id=$("#userid").val();
     var requestid=$("#requestid").val();
     
       $.ajax({
                type: "POST",
                url: '/pagarbankcrs',
                data: {
                    method:method,
                    comment:comment,
                    user_id:user_id,
                    requestid:requestid
                },
                success: function (response) {
                    //   location.reload();
                    console.log(response);
                    if (response==1) {
                        alert("done");
                       window.location = "/dashboard/admin";
                    }
                    else
                    {
                       alert("error"); 
                    }
                        
                    
                }

            });

        
        
    });
</script>


<script>
       
    $("#acc").click(function(){

       var method="accept";
     var user_id=$("#userid").val();
     var requestid=$("#requestid").val();
   
       $.ajax({
                type: "POST",
                url: '/pagarbankcrs',
                data: {
                    method:method,                
                    user_id:user_id,
                    requestid:requestid,           
                },
                success: function (response) {
                    //   location.reload();
                    var responser = jQuery.parseJSON(response);
                    console.log("response");
                     console.log(responser.res);
                    if (responser.res==1) {
                        alert("done");
                       //window.location = "/dashboard/admin";
                    }
                    else
                    {
                       alert(response); 
                      
                    }
                }

            }); 
        
    });
</script>