

<div class="main-container">
    <div class="padding-md m-bottom-md">
        <ul class="breadcrumb">
            <li><span class="primary-font"><i class="icon-home"></i></span><a href="/dashboard/admin"><?php echo $this->translate("Home") ?></a></li>
            <li><?php echo $this->translate("User Details") ?></li>	 

        </ul>
<!--        <div class="col-lg-10">

            <input id="radio4" class="checkbox" value="ALL" checked="" type="radio" name="radiog_dark"><label>ALL users</label>

        </div>
        <div class="col-lg-10">

            <input id="radio4" class="checkbox" value="Membership" type="radio" name="radiog_dark"><label> Membership users </label>


        </div>-->



        <div role="tabpanel">

            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#allUsers" aria-controls="allUsers" role="tab" data-toggle="tab"> <?php echo $this->translate("All Users") ?> </a></li>
                 <li role="presentation"><a href="#mtrial" aria-controls="mtrial" role="tab" data-toggle="tab"><?php echo $this->translate("Trial Users ") ?> </a></li>
                <li role="presentation"><a href="#mUsers" aria-controls="mUsers" role="tab" data-toggle="tab"><?php echo $this->translate("Membership Users ") ?> </a></li>
                <li role="presentation"><a href="#mteacher" aria-controls="mteacher" role="tab" data-toggle="tab"><?php echo $this->translate("Teachers") ?> </a></li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="allUsers">
                    <table class="table table-striped" id="dataTable">
                        <thead>
                            <tr>
                                <th><?php echo $this->translate("S.No") ?></th>
                                <th><?php echo $this->translate("Firstname") ?></th>
                                <th><?php echo $this->translate("Email ID") ?></th>
                                <th><?php echo $this->translate("Joining Date") ?></th>
                                <th><?php echo $this->translate("Status") ?></th>
                                <th><?php echo $this->translate("Action") ?></th>
                                <th><?php echo $this->translate("Edit/Delete") ?></th>

                            </tr>
                        </thead>
                        <tbody id="cleardata">
                            <?php
                            if (isset($this->users)) {
                                $i = 1;
                                foreach ($this->users as $userinfo) {
                                    ?>

                                    <tr class="userdet">
                                        <td><?php echo $i; ?></td>
                                        <td><?php echo $userinfo['first_name']; ?></td>
                                        <td><?php echo $userinfo['email']; ?></td>
                                        <td><?php if(isset($userinfo['reg_date'])){echo $userinfo['reg_date'];}else{ echo "No date";}?></td>
                                        <?php if ($userinfo['status'] == 1) { ?>
                                            <td id="activeuser_<?php echo $userinfo['user_id']; ?>" class = "useractive"><?php echo $this->translate("Active") ?></td>
                                            &nbsp;
                                            <td class="text-center"><a href="#" id="<?php
                                                if (isset($userinfo['user_id'])): echo "users_" . $userinfo['user_id'];
                                                endif;
                                                ?>" class="usersdeactive">
                                                    <span id="activeclass_<?php echo $userinfo['user_id']; ?>" class="label label-success"><?php echo $this->translate("Deactivate") ?></span></a></td>
                                        <?php } else { ?>
                                            <td id="activeuser_<?php echo $userinfo['user_id']; ?>" class = "userdeactive"><?php echo $this->translate("Suspended") ?></td>
                                            &nbsp;
                                            <td class="text-center"><a href="#" id="<?php
                                                if (isset($userinfo['user_id'])): echo "users_" . $userinfo['user_id'];
                                                endif;
                                                ?>" class="usersactive">
                                                    <span id="activeclass_<?php echo $userinfo['user_id']; ?>" class="label label-danger"><?php echo $this->translate("Activate") ?></span></a></td>
                                        <?php } ?>
                                        <td style="width: 13%;"><a href="edit-user/<?php echo $userinfo['user_id']; ?>"class="btn btn-success btn-sm"><?php echo $this->translate("Edit") ?></a>
                                            <a class="delete_<?php echo $userinfo['user_id']; ?>" data-val="<?php echo $userinfo['user_id']; ?>" id ="delete" ><button class="btn btn-danger btn-sm"><?php echo $this->translate("Delete") ?></button></a>
                                        </td>
                                    </tr>
                                    <?php $i++; ?>
                                    <?php
                                }
                            }
                            ?>

                        </tbody>
                    </table>
                </div>
                <div role="tabpanel" class="tab-pane" id="mUsers">
                       <table class="table table-striped" id="dbTable">
                        <thead>
                            <tr>
                                <th><?php echo $this->translate("S.No") ?></th>
                                <th><?php echo $this->translate("Firstname") ?></th>
                                <th><?php echo $this->translate("Email ID") ?></th>
                                <th><?php echo $this->translate("Joining Date") ?></th>
                                <th><?php echo $this->translate("Status") ?></th>
                                <th><?php echo $this->translate("Action") ?></th>
                                <th><?php echo $this->translate("Edit/Delete") ?></th>

                            </tr>
                        </thead>
                        <tbody id="cleardata">
                            <?php
                            if (isset($this->memberships )) {
                                $i = 1;
                                foreach ($this->memberships as $info) {
                                    ?>

                                    <tr class="userdet">
                                        <td><?php echo $i; ?></td>
                                        <td><?php echo $info['first_name'].$info['last_name']; ?></td>
                                        <td><?php echo $info['email']; ?></td>
                                        <td><?php if(isset($info['reg_date'])){ echo $info['reg_date'];}else{ echo "No Date";}?></td>
                                        <?php if ($info['status'] == 0) { ?>
                                            <td id="activeuser_<?php echo $info['user_id']; ?>" class = "useractive"><?php echo $this->translate("Active") ?></td>
                                            &nbsp;
                                            <td class="text-center"><a href="#" id="<?php
                                                if (isset($info['user_id'])): echo "users_" . $info['user_id'];
                                                endif;
                                                ?>" class="usersdeactive">
                                                    <span id="activeclass_<?php echo $info['user_id']; ?>" class="label label-success"><?php echo $this->translate("Deactivate") ?></span></a></td>
                                        <?php } else { ?>
                                            <td id="activeuser_<?php echo $info['user_id']; ?>" class = "userdeactive"><?php echo $this->translate("Suspended") ?></td>
                                            &nbsp;
                                            <td class="text-center"><a href="#" id="<?php
                                                if (isset($info['user_id'])): echo "users_" . $info['user_id'];
                                                endif;
                                                ?>" class="usersactive">
                                                    <span id="activeclass_<?php echo $info['user_id']; ?>" class="label label-danger"><?php echo $this->translate("Activate") ?></span></a></td>
                                        <?php } ?>
                                        <td style="width: 13%;"><a href="edit-user/<?php echo $info['user_id']; ?>"class="btn btn-success btn-sm"><?php echo $this->translate("Edit") ?></a>
                                            <a class="delete_<?php echo $info['user_id']; ?>" data-val="<?php echo $info['user_id']; ?>" id ="delete" ><button class="btn btn-danger btn-sm"><?php echo $this->translate("Delete") ?></button></a>
                                        </td>
                                    </tr>
                                    <?php $i++; ?>
                                    <?php
                                }
                            }
                            ?>

                        </tbody>
                    </table> 
                </div>
                   <div role="tabpanel" class="tab-pane" id="mteacher">
                       <table class="table table-striped" id="dbTables">
                        <thead>
                            <tr>
                                <th><?php echo $this->translate("S.No") ?></th>
                                <th><?php echo $this->translate("Firstname") ?></th>
                                <th><?php echo $this->translate("Email ID") ?></th>
                                <th><?php echo $this->translate("Joining Date") ?></th>
                                <th><?php echo $this->translate("Status") ?></th>
                                <th><?php echo $this->translate("Action") ?></th>
                                <th><?php echo $this->translate("Edit/Delete") ?></th>

                            </tr>
                        </thead>
                        <tbody id="cleardata">
                            <?php
                            if (isset($this->teachersdetails )) {
                                $i = 1;
                                foreach ($this->teachersdetails as $teacherinfo) {
                                    ?>

                                    <tr class="userdet">
                                        <td><?php echo $i; ?></td>
                                        <td><?php echo $teacherinfo['first_name']; ?></td>
                                        <td><?php echo $teacherinfo['email']; ?></td>
                                        <td><?php if(isset($teacherinfo['reg_date'])){ echo $teacherinfo['reg_date'];}else{ echo "No Date";}?></td>
                                        <?php if ($teacherinfo['status'] == 0) { ?>
                                            <td id="activeuser_<?php echo $teacherinfo['user_id']; ?>" class = "useractive"><?php echo $this->translate("Active") ?></td>
                                            &nbsp;
                                            <td class="text-center"><a href="#" id="<?php
                                                if (isset($teacherinfo['user_id'])): echo "users_" . $teacherinfo['user_id'];
                                                endif;
                                                ?>" class="usersdeactive">
                                                    <span id="activeclass_<?php echo $teacherinfo['user_id']; ?>" class="label label-success"><?php echo $this->translate("Deactivate") ?></span></a></td>
                                        <?php } else { ?>
                                            <td id="activeuser_<?php echo $teacherinfo['user_id']; ?>" class = "userdeactive"><?php echo $this->translate("Suspended") ?></td>
                                            &nbsp;
                                            <td class="text-center"><a href="#" id="<?php
                                                if (isset($teacherinfo['user_id'])): echo "users_" . $teacherinfo['user_id'];
                                                endif;
                                                ?>" class="usersactive">
                                                    <span id="activeclass_<?php echo $teacherinfo['user_id']; ?>" class="label label-danger"><?php echo $this->translate("Activate") ?></span></a></td>
                                        <?php } ?>
                                        <td style="width: 13%;"><a href="edit-user/<?php echo $teacherinfo['user_id']; ?>"class="btn btn-success btn-sm"><?php echo $this->translate("Edit") ?></a>
                                            <a class="delete_<?php echo $teacherinfo['user_id']; ?>" data-val="<?php echo $teacherinfo['user_id']; ?>" id ="delete" ><button class="btn btn-danger btn-sm"><?php echo $this->translate("Delete") ?></button></a>
                                        </td>
                                    </tr>
                                    <?php $i++; ?>
                                    <?php
                                }
                            }
                            ?>

                        </tbody>
                    </table> 
                </div>
                
                   <div role="tabpanel" class="tab-pane" id="mtrial">
                       <table class="table table-striped" id="dbTables">
                        <thead>
                            <tr>
                                <th><?php echo $this->translate("S.No") ?></th>
                                <th><?php echo $this->translate("Firstname") ?></th>
                                <th><?php echo $this->translate("Email ID") ?></th>
                                <th><?php echo $this->translate("Joining Date") ?></th>
                                <th><?php echo $this->translate("Status") ?></th>
                                <th><?php echo $this->translate("Action") ?></th>
                                <th><?php echo $this->translate("Edit/Delete") ?></th>

                            </tr>
                        </thead>
                        <tbody id="cleardata">
                            <?php
                            if (isset($this->trialusers )) {
                                $i = 1;
                                foreach ($this->trialusers as $teacherinfo) {
                                    ?>

                                    <tr class="userdet">
                                        <td><?php echo $i; ?></td>
                                        <td><?php echo $teacherinfo['first_name']; ?></td>
                                        <td><?php echo $teacherinfo['email']; ?></td>
                                        <td><?php if(isset($teacherinfo['reg_date'])){ echo $teacherinfo['reg_date'];}else{ echo "No Date";}?></td>
                                        <?php if ($teacherinfo['status'] == 0) { ?>
                                            <td id="activeuser_<?php echo $teacherinfo['user_id']; ?>" class = "useractive"><?php echo $this->translate("Active") ?></td>
                                            &nbsp;
                                            <td class="text-center"><a href="#" id="<?php
                                                if (isset($teacherinfo['user_id'])): echo "users_" . $teacherinfo['user_id'];
                                                endif;
                                                ?>" class="usersdeactive">
                                                    <span id="activeclass_<?php echo $teacherinfo['user_id']; ?>" class="label label-success"><?php echo $this->translate("Deactivate") ?></span></a></td>
                                        <?php } else { ?>
                                            <td id="activeuser_<?php echo $teacherinfo['user_id']; ?>" class = "userdeactive"><?php echo $this->translate("Suspended") ?></td>
                                            &nbsp;
                                            <td class="text-center"><a href="#" id="<?php
                                                if (isset($teacherinfo['user_id'])): echo "users_" . $teacherinfo['user_id'];
                                                endif;
                                                ?>" class="usersactive">
                                                    <span id="activeclass_<?php echo $teacherinfo['user_id']; ?>" class="label label-danger"><?php echo $this->translate("Activate") ?></span></a></td>
                                        <?php } ?>
                                        <td style="width: 13%;"><a href="edit-user/<?php echo $teacherinfo['user_id']; ?>"class="btn btn-success btn-sm"><?php echo $this->translate("Edit") ?></a>
                                            <a class="delete_<?php echo $teacherinfo['user_id']; ?>" data-val="<?php echo $teacherinfo['user_id']; ?>" id ="delete" ><button class="btn btn-danger btn-sm"><?php echo $this->translate("Delete") ?></button></a>
                                        </td>
                                    </tr>
                                    <?php $i++; ?>
                                    <?php
                                }
                            }
                            ?>

                        </tbody>
                    </table> 
                </div> 
                
            </div>
        </div><!-- ./padding-md -->
    </div><!-- /main-container -->

</div><!-- /wrapper -->

<a href="#" class="scroll-to-top hidden-print"><i class="fa fa-chevron-up fa-lg"></i></a>



<script>
    $("#musers").addClass("open active");
$("#ud1").attr("style","display: block;");
$("#ud2").addClass("active");
    $(function() {
        $('#dataTable').dataTable();
    });
    $(function() {
        $('#dbTable').dataTable();
    });
      $(function() {
        $('#dbTables').dataTable();
    });
//dev:priyanka varanasi
//desc:To deactivate the user
    $(document.body).on('click', '.usersdeactive', function() {
        var userid = $(this).attr('id')
        var userid = userid.replace("users_", "");
        console.log('deactivate called');
        $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'useractive',
                userid: userid
            },
            beforeSend: function() {

            },
            success: function(response) {
                console.log(response);
                var uid  = response.replace(/ /g,'');
                
                $('#' + "activeclass_" + uid).removeClass('label label-success');
                $('#' + "activeclass_" + uid).addClass('label label-danger');
                $('#' + "activeclass_" + uid).html("Activate");
                $('#users_' + uid).removeClass('usersdeactive');
                $('#users_' + uid).addClass('usersactive');
                $('#' + "activeuser_" + uid).html("Suspended");

            }
        });

    });
//dev:priyanka varanasi
//desc:To activate the user
    $(document.body).on('click', '.usersactive', function() {
        var userid = $(this).attr('id')
        var userid = userid.replace("users_", "");
        console.log('activate called');
        $.ajax({
            url: './user-ajax-handler',
            type: 'POST',
            datatype: 'HTML',
            data: {
                method: 'useractive',
                userid: userid
            },
            beforeSend: function() {

            },
            success: function(response) {
                var uid  = response.replace(/ /g,'');
                $('#' + "activeclass_" + uid).removeClass('label label-danger');
                $('#' + "activeclass_" + uid).addClass('label label-success');
                $('#' + "activeclass_" + uid).html("Dectivate");
                $('#users_' + uid).removeClass('usersactive');
                $('#users_' + uid).addClass('usersdeactive');
                $('#' + "activeuser_" + uid).html("Active");

            }


        });

    });

//dev:priyanka varanasi
//desc:To delete the user

    $(document.body).on('click', '#delete', function() {

        var deleteid = $(this).attr('data-val');

        $("#DeleteModal").modal('show');
        $(document.body).on('click', '#ok', function() {
            $("#DeleteModal").modal('hide');
            if (deleteid) {
                $.ajax({
                    url: './user-ajax-handler',
                    type: 'POST',
                    datatype: 'json',
                    data: {
                        method: 'userdelete',
                        userid: deleteid
                    },
                    beforeSend: function() {

                    },
                    success: function(response) {
                        if (response) {
                          var uid  = response.replace(/ /g,'');
                            $('.' + "delete_" +uid).parent().parent().remove();

                        }
                    }

                });

            }


        });
    });

    //dev: priyanka varanasi
    //desc: To filter membership users and all users 

//    $(document.body).on('change', '#radio4', function() {
//        var checked_site_radio = $('input:radio[name=radiog_dark]:checked').val();
//        if (checked_site_radio == "Membership") {
//            $.ajax({
//                url: './user-ajax-handler',
//                type: 'POST',
//                dataType: 'json',
//                data: {
//                    method: checked_site_radio
//                },
//                beforeSend: function() {
//
//                },
//                success: function(response) {
//
//
//                    $('#dataTable').dataTable();
//                    $('#dataTable').html('<thead><tr><th>S.No</th><th>Firstname</th><th>Email ID</th><th>Joining Date</th><th>Status</th><th>Action</th><th>Edit &nbsp;&nbsp;Delete</th></tr></thead><tbody id="cleardata">');
//                    var t = 1;
//                    $.each(response, function(index, val) {
//                        console.log(val);
//                        if (val.curstatus == 1) {
//                            if (val.reg_date == null) {
//                                $('#dataTable').append('<tr class="userdet"><td>' + t + '</td><td>' + val.first_name + '</td>' +
//                                        '<td>' + val.email + '</td><td> no date</td>' +
//                                        '<td id="activeuser_' + val.user_id + '" class="useractive">Active</td>' + '&nbsp;' +
//                                        '<td class="text-center"><a href="#" id="users_' + val.user_id + '" class="usersdeactive">' +
//                                        '<span id="activeclass_' + val.user_id + '"class="label label-success">Deactivate</span></a></td>' +
//                                        '<td style="width: 13%;"><a href="edit-user/' + val.user_id + '"><button class="btn btn-success btn-sm">Edit</button></a>' + '&nbsp;&nbsp;' +
//                                        '<a class="delete_' + val.user_id + '" data-val="' + val.user_id + '" id ="delete" ><button class="btn btn-danger btn-sm">' + '&nbsp;&nbsp;' + 'Delete</button></a></td></tr>');
//
//                            } else {
//                                $('#dataTable').dataTable();
//                                $('#dataTable').append('<tr class="userdet"><td>' + t + '</td><td>' + val.first_name + '</td>' +
//                                        '<td>' + val.email + '</td><td>' + val.reg_date + '</td>' +
//                                        '<td id="activeuser_' + val.user_id + '" class="useractive">Active</td>' + '&nbsp;' +
//                                        '<td class="text-center"><a href="#" id="users_' + val.user_id + '" class="usersdeactive">' +
//                                        '<span id="activeclass_' + val.user_id + '"class="label label-success">Deactivate</span></a></td>' +
//                                        '<td style="width: 13%;"><a href="edit-user/' + val.user_id + '"><button class="btn btn-success btn-sm">Edit</button></a>' + '&nbsp;&nbsp;' +
//                                        '<a class="delete_' + val.user_id + '" data-val="' + val.user_id + '" id ="delete" ><button class="btn btn-danger btn-sm">' + '&nbsp;&nbsp;' + 'Delete</button></a></td></tr>');
//                            }
//                        } else {
//                            if (val.reg_date == null) {
//                                $('#dataTable').append('<tr class="userdet"><td>' + t + '</td><td>' + val.first_name + '</td>' +
//                                        '<td>' + val.email + '</td><td>no date</td>' +
//                                        '<td id="activeuser_' + val.user_id + '" class = "userdeactive">Suspended</td>' +
//                                        '<td class="text-center"><a href="#" id="users_' + val.user_id + '" class="usersactive">' +
//                                        '<span id="activeclass_' + val.user_id + '" class="label label-danger">Activate</span></a></td>' +
//                                        '<td style="width: 13%;"><a href="edit-user/' + val.user_id + '"><button class="btn btn-success btn-sm">Edit</button></a>' + '&nbsp;&nbsp;' +
//                                        '<a class="delete_' + val.user_id + '" data-val="' + val.user_id + '" id ="delete" ><button class="btn btn-danger btn-sm">' + '&nbsp;&nbsp;' + 'Delete</button></a></td></tr>'
//                                        );
//
//
//                            } else {
//                                $('#dataTable').append('<tr class="userdet"><td>' + t + '</td><td>' + val.first_name + '</td>' +
//                                        '<td>' + val.email + '</td><td>' + val.reg_date + '</td>' +
//                                        '<td id="activeuser_' + val.user_id + '" class = "userdeactive">Suspended</td>' +
//                                        '<td class="text-center"><a href="#" id="users_' + val.user_id + '" class="usersactive">' +
//                                        '<span id="activeclass_' + val.user_id + '" class="label label-danger">Activate</span></a></td>' +
//                                        '<td><a href="edit-user/' + val.user_id + '"><button class="btn btn-success btn-sm">Edit</button></a>' + '&nbsp;&nbsp;' +
//                                        '<a class="delete_' + val.user_id + '" data-val="' + val.user_id + '" id ="delete" ><button class="btn btn-danger btn-sm">' + '&nbsp;&nbsp;' + 'Delete</button></a></td></tr>'
//                                        );
//                            }
//                        }
//                        t++;
//                    });
//
//
//                }
//            });
//
//        } else {
//            window.location.reload(true);
//        }
//    });

</script>

