<div id="content">
    <h4><?php echo $this->translate("Allow bonus to Country") ?></h4>
    <div class="innerLR">

        <!-- Widget -->
        <div class="widget">

            <!-- Widget heading -->
            <div class="widget-head">
<!--                <h4 class="heading">Country Manage</h4>-->

                     
            </div>
            <!-- // Widget heading END -->

            <div class="widget-body">
                <div class="widget-tablebody">
                
                <form method="post">
                    
                <!-- Table -->
                <table class="dynamicTable table table-striped table-bordered table-condensed">
                       
                    <!-- Table heading -->
                    <thead>
                        <tr>
                            <th><input type="checkbox" id="checkbutton"> <?php echo $this->translate("ALL") ?></th>
                            <th><?php echo $this->translate("Country Code") ?></th>
                            <th><?php echo $this->translate("Country Name") ?></th>
                            <th class="center"><?php echo $this->translate("Status") ?></th>
                           
                        </tr>
                    </thead>
                    <!-- // Table heading END -->

                    <!-- Table body -->
                    <tbody>

                        <?php if(isset($this->countries)): $row = 0; foreach($this->countries as $countriesDetails): $row ++;?>
                        <!-- Table row -->
                        <tr class="gradeA">
                            
                            <td><input type="checkbox" name="list[]" class="checkbox1" value="<?php echo $countriesDetails['country_id']; ?>"></td>
                            <td><?php echo $countriesDetails['country_code']; ?></td>
                            <td><?php echo $countriesDetails['country_name']; ?></td>
                            <td  class="center"><?php if(($countriesDetails['bonus'])==0){
                                        echo "denied";
                            } else{echo "allowed";}
                                 ?>
                            </td>  
                        </tr>                        
                        <!-- // Table row END -->
                        <?php endforeach;  endif; ?>
                    </tbody>
                    <!-- // Table body END -->

                </table>
                </div>
                <!-- // Table END -->
                <select name="action" class="form-control">
                    <option value=1><?php echo $this->translate("Allow Bonus") ?></option>
                    <option value=0><?php echo $this->translate("Deny Bonus") ?></option>
                </select>

                <button type="submit" class="btn btn-icon btn-primary glyphicons circle_ok"><i></i>Save changes</button>
                </form>
            </div>
           
        </div>
    </div>	
</div>
<script>
    $('#menu_components5').removeClass('collapse').addClass('in collapse');
    $('#site_menu').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons cogwheels active');
    $('#country_menu').addClass('active');    
</script>
<script type="text/javascript">
    
//         var checkflag = "false";
//         var i;
//         function check(field) {
//             console.log(field);
//             if (checkflag == "false") {
//                 for (i = 0; i < field.length; i++) {
//                     field[i].checked = true;
//                 }
//                 checkflag = "true";
//               
//             } else {
//                 for (i = 0; i < field.length; i++) {
//                     field[i].checked = false;
//                 }
//                 checkflag = "false";
//               
//             }
//         }
//         

         
 $(document).ready(function() {
    $('#checkbutton').click(function(event) {  //on click
        
            $('.checkbox1').each(function() { //loop through each checkbox
                
          $(this).prop('checked',(!$(this).prop('checked')));     
//        this.checked = true;  //select all checkboxes with class "checkbox1"              
            });
        
    });
   
});        
         
         
//       $(document).ready(function(){
//           
//           validator.oncheck(qwe) 
//           
//           
//           
//          $("#checkbutton").on('click',function(e){
//              
//              console.log(e);
//              
//          }); 
//           
//           
//       }); 
//        
//       
 </script>