<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	
    $('#user_list').highcharts({
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Join User Statics'
        },
        xAxis: {
            categories: ['JAN', 'FEB', 'MAR','APR','MAY','JUN','JLY','AUG','SEP','OCT','NOV','DEC']
        },
        yAxis: {
            title: {
                text: 'Users'
            }
        },
        series: [{
            name: 'Users',
            data: [ <?php     
                    foreach ($this->userstatic as $val)
                    {
                        echo "$val,";

                    }
            ?>]
        }]
    });
    
    $('#profit_list').highcharts({
        chart: {
            type: 'line'
        },
        title: {
            text: 'Profit Statics'
        },
        xAxis: {
            categories: ['JAN', 'FEB', 'MAR','APR','MAY','JUN','JLY','AUG','SEP','OCT','NOV','DEC']
        },
        yAxis: {
            title: {
                text: 'Profit'
            }
        },
        series: [{
            name: 'Profit',
            data: [<?php foreach($this->profitstatic as $profit) { if($profit['total'] == ""){ echo "0".','; }else { echo $profit['total'].','; } } ?>]
        }]
    }); 
    
});
</script>

<section id="content">
          <section class="vbox">          
            <section class="scrollable">
              <div class="wrapper-lg">
                <h3 class="m-b-xs font-bold m-t-none"><?php echo $this->translate("Welcome back") ?>, John</h3>
<!--                <div class="text-muted text-sm"><a href="#" class="text-primary font-bold">25</a> Tasks, <a href="#" class="text-primary font-bold">50</a> Messages</div>-->
              </div>
              <ul class="nav nav-tabs">                
                <li class="active m-l-lg"><a href="#sales" data-toggle="tab"><?php echo $this->translate("User") ?></a></li>
                <li><a href="#revenue" data-toggle="tab"><?php echo $this->translate("Profit") ?></a></li>
<!--                <li><a href="#orders" data-toggle="tab">Orders</a></li>-->
              </ul>
              <div class="wrapper-lg bg-white b-b b-light">
                <div class="tab-content">
                  <div class="tab-pane active" id="sales">
                  <div id="user_list" style="width:80%; height:400px;"></div>
                  </div>
                  <div class="tab-pane" id="revenue">
                    <div id="profit_list" style="width:80%; height:400px;"></div>
                  </div>
<!--                  <div class="tab-pane" id="orders">
                    <div id="flot-live"  style="width:100%;height:240px"></div>
                  </div>-->
                </div>
                <div class="row text-center no-gutter">
                  <div class="col-xs-4 b-r b-light">
                    <span class="h4 font-bold m-t block"><?php echo $this->totalusers; ?></span>
                    <small class="text-muted block"><?php echo $this->translate("Users") ?></small>
                  </div>
                  <div class="col-xs-4 b-r b-light">
                    <span class="h4 font-bold m-t block"><?php echo $this->totalcontets; ?></span>
                    <small class="text-muted block"><?php echo $this->translate("Contest") ?></small>
                  </div>
                  <div class="col-xs-4 b-r b-light">
                    <span class="h4 font-bold m-t block"><?php echo $this->totalProfit; ?></span>
                    <small class="text-muted block"><?php echo $this->translate("Profit") ?></small>
                  </div>
<!--                  <div class="col-xs-3">
                    <span class="h4 font-bold m-t block">7,230</span>
                    <small class="text-muted block">Customers</small>
                  </div>-->
                </div>
              </div>
              
            </section>
          </section>
          <a href="#" class="hide nav-off-screen-block" data-toggle="class:nav-off-screen, open" data-target="#nav,html"></a>
        </section>
        <aside class="bg-light lter b-l aside-md hide" id="notes">
          <div class="wrapper"><?php echo $this->translate("Notification") ?></div>
        </aside>
      </section>
    </section>
  </section>