
<div class="opennotificationGreen" style="z-index: 99;">
<span class="notification_msgGreen"><?php echo $this->translate("Your offers details has been added successfully") ?>.</span>
</div>
<div id="content">
    <h4><?php echo $this->translate("Offers Details") ?></h4>
    <div class="innerLR">

        <!-- Widget -->
        <div class="widget">

            <!-- Widget heading -->
            <div class="widget-head">
                <h4 class="heading"><?php echo $this->translate("Upload New Offer") ?></h4>
            </div>
            <!-- // Widget heading END -->
            <div>
 
 
            <div class="widget-body">
                <form action="" method="post" enctype="multipart/form-data" class="offersfileform">         
                                <div class="setingbg">
                                   <input required="true" id="imagefile" name="imagefile" type="file"/><br>
                                   <span id="errormsg"></span>
                                </div>
                    
                                <div class="setingbg">
                                   <input required="true" name="offer_name"  type="text" placeholder="<?php echo $this->translate("offer name") ?>"/><br>
                                </div>
                    
                               
                                <input type="text" id="datepicker"  name="end_date" value=""  placeholder="<?php echo $this->translate("Offer End Date") ?>"/><br>
                                
                                <div class="setingbg">
                                   <input required="true" name="description" type="text" placeholder="<?php echo $this->translate("add offer description") ?>"/><br>
                                </div>
                                
                                <div class="setingbg">
                                   <select name="contest" class="span6">
                                       <?php if(isset($this->contests)): foreach($this->contests as $value):  ?>
                                       <option value="<?php echo $value['contest_id']; ?>"><?php echo $value['contest_name']; ?></option>
                                       <?php endforeach; endif; ?>
                                   </select><br>
                                </div>
                                <div class="setingbg" style="margin-left: 31px;">
                                   <button type="submit" class="btn btn-icon btn-primary glyphicons upload"><i></i><?php echo $this->translate("Upload Offer") ?></button>
                                </div>
                    </form> 

            </div>
        </div>
        
        <!-- Widget -->
        <div class="widget">

            <!-- Widget heading -->
            <div class="widget-head">
                <h4 class="heading"><?php echo $this->translate("Offers Manage") ?></h4>
                
                    <h5 id="error" ></h5>
                
                
            </div>
            <!-- // Widget heading END -->

     <?php if(isset($this->offer_details)){?>
         
            <div class="widget-body">

                <!-- Table -->
                <div role="grid" class="offerTables_wrapper form-inline" >
                 
                    <table class="dynamicTable table table-striped table-bordered table-condensed dataTable">

                    <!-- Table heading -->
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 30px;" aria-sort="ascending" aria-label="<?php echo $this->translate("No: activate to sort column descending") ?>"><?php echo $this->translate("No") ?>.</th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 250px;" aria-label="<?php echo $this->translate("Name: activate to sort column ascending") ?>"><?php echo $this->translate("Name") ?></th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 80px;" aria-label="<?php echo $this->translate("Name: activate to sort column ascending") ?>"><?php echo $this->translate("Contest Id") ?></th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 180px;" aria-label="<?php echo $this->translate("Title: activate to sort column ascending") ?>"><?php echo $this->translate("Offer End Date") ?></th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 332px;" aria-label="<?php echo $this->translate("Description: activate to sort column ascending") ?>"><?php echo $this->translate("Description") ?></th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 100px;" aria-label="<?php echo $this->translate("Status: activate to sort column ascending") ?>"><?php echo $this->translate("Status") ?></th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 80px;" aria-label="<?php echo $this->translate("Actions: activate to sort column ascending") ?>"><?php echo $this->translate("Actions") ?></th>
                            <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 80px;" aria-label="<?php echo $this->translate("Actions: activate to sort column ascending") ?>"><?php echo $this->translate("Edit/Delete") ?></th></tr>
                    </thead>
                    <!-- // Table heading END -->

                    <!-- Table body -->
                    
                    <!-- // Table body END -->

                        <tbody role="alert" aria-live="polite" aria-relevant="all">
                          <?php  if(isset($this->offer_details)): $i=1; foreach($this->offer_details as $value): ?>                            
                            <tr class="gradeX odd">
                                    <td class="  sorting_1"><?= $i ?></td>                            
                                    <td class=" "><?php echo $value['offer_name'] ?></td>
                                    <td class="center"><?php echo $value['contest_id'] ?></td>
                                    <td class="center"><?php echo date("j F , Y",strtotime($value['offer_end_date'])); ?></td>
                                    <td class="center"><?php echo $value['description'] ?></td>

                                    <?php if($value['status']==1): ?>
                                    <td id="activemenu_<?php echo $value['offer_id']; ?>" class="center js-sortable-handle offersactive"><?php echo $this->translate("Active") ?></td>
                                    <td class="center" style="width: 80px;"><a  id="<?php if (isset($value['offer_id'])): echo "offers_" . $value['offer_id'];endif;?>" class="offersdeactive">
                                    <span id="activeclass_<?php echo $value['offer_id']; ?>" class="label label-block label-inverse"><?php echo $this->translate("Deactivate") ?></span></a></td>
                                      <?php  else: ?>
                                    <td id="activemenu_<?php echo $value['offer_id']; ?>" class="center js-sortable-handle offersdeactive"><?php echo $this->translate("Suspended") ?></td>
                                    <td class="center" style="width: 80px;"><a  id="<?php if (isset($value['offer_id'])): echo "offers_" . $value['offer_id']; endif;?>" class="offersactive">
                                    <span id="activeclass_<?php echo $value['offer_id']; ?>"  class="label label-block label-primary"><?php echo $this->translate("Activate") ?></span></a></td>
                                    <?php endif;?>
                                    <td>
                                        <a  href="edit-offer/<?php echo $value['offer_id']; ?>" class="btn-action glyphicons pencil btn-success"><i></i></a>
                                        <a  href="#" id="<?php  echo "offerdelete_" . $value['offer_id'];  ?>" class="btn-action glyphicons remove_2 btn-danger offer-delete"><i></i></a>
                                    </td>
                            
                            </tr>                            
                           <?php $i++;endforeach;endif;?>
                        </tbody>
                      
                    </table>
                  </div>
               
                <!-- // Table END -->
            </div>
            <?php } ?>
        </div>
    </div>	
</div>
</div>
<?php if(isset($this->success)) {?>
<!-- This script Displays the  notification when the user details are submitted on submit  -->
<script>  
        $('.opennotificationGreen').click(function()
        {
            alert('ss');
            $('.opennotificationGreen').fadeOut("slow");
            $('div').remove(".notification_msgGreen");
        });
    
        $('.opennotificationGreen').fadeIn("slow");             
        $('.opennotificationGreen').css('display','block');
        
        setTimeout(function() {
            $('.opennotificationGreen').fadeOut("slow");
            $('div').remove(".notification_msgGreen");
            }, 3000); 
             
        
    </script>
    <?php }?>
<script>
$('#menu_components7').removeClass('collapse').addClass('in collapse');
$('#offers_menu').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons cogwheels active');
$('#offers').addClass('active');
</script>

    
   