<style>
    .well-icon {
        min-height: 84px;
    }
</style>
<div class="main-container">
    <div class="padding-md">

        <div class="row">
            <div class="col-sm-6">
                <h5><?php echo $this->translate("DASHBOARD") ?></h5>  
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                <div class="well paddingTB-md relative">
                    <span class="block big_text">R$ <?php echo round($this->adminincomelastyear,2); ?></span>
                    <span class="block small"><?php echo $this->translate("Total earned last year") ?></span>

                    <span class="well-icon bg-info">
                        <i class="block fa-2x icon-057"></i>
                    </span>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                <div class="well paddingTB-md relative">
                   
                    <span class="block big_text">R$ <?php echo round($this->teacheralreadydividedlastyear,2); ?></span>
                    <span class="block small"><?php echo $this->translate("Total divided last year") ?></span>

                    <span class="well-icon bg-violet ">
                        <i class="block fa-2x icon-065"></i>
                    </span>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                <div class="well paddingTB-md relative">
                    <span class="block big_text">R$ <?php echo round($this->lastmonthadminearn,2); ?></span>
                    <span class="block small"><?php echo $this->translate("Total earned last month") ?>  <span class="text-warning"></span></span>

                    <span class="well-icon bg-warning">
                        <i class="block fa-2x icon-670"></i>
                    </span>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                <div class="well paddingTB-md relative">
                    <span class="block big_text">R$ <?php echo round($this->teacheralreadydividedlastmonth,2); ?></span>
                    <span class="block small"><?php echo $this->translate("Total divided  last month") ?>   <span class="text-warning"></span></span>

                    <span class="well-icon bg-purple">
                        <i class="block fa-2x icon-067"></i>
                    </span>
                </div>
            </div>
        </div>        
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                <div class="well paddingTB-md relative">
                    <span class="block big_text">R$ <?php echo round($this->lastyearleftover,2); ?></span>
                    <span class="block small"><?php echo $this->translate("Leftover last year") ?></span>

                    <span class="well-icon bg-gray">
                        <i class="block fa-2x icon-067"></i>
                    </span>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                <div class="well paddingTB-md relative">
                    <span class="block big_text">R$ <?php echo round($this->lastmonthleftover,2); ?></span>
                    <span class="block small"><?php echo $this->translate("Leftover last month") ?></span>

                    <span class="well-icon bg-gray">
                        <i class="block fa-2x icon-067"></i>
                    </span>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                <div class="well paddingTB-md relative">
                    <span class="block big_text">R$<?php echo round($this->bestteacher,2);?></span>
                    <span class="block small"><?php echo $this->translate("Teacher more earned last month") ?></span>

                    <span class="well-icon bg-gray">
                        <i class="block fa-2x icon-1368"></i>
                    </span>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                <div class="well paddingTB-md relative">
                    <span class="block big_text">R$ <?php echo  round($this->lessearnteacher,2); ?></span>
                    <span class="block small"><?php echo $this->translate("Teacher less earned last month") ?></span>

                    <span class="well-icon bg-gray">
                        <i class="block fa-2x icon-067"></i>
                    </span>
                </div>
            </div>
        </div>  
        <div class="row">
            <div class="col-md-12">
                <div class="smart-widget">
                    <div class="smart-widget-header border-bottom">
<?php echo $this->translate("FINANCE CONTROL") ?>
                    </div>
                    <div class="smart-widget-inner">
                        <div class="smart-widget-body no-padding">
                            <div class="padding-md">
                                <div>
                                    <span class="m-right-sm"><i class="fa fa-circle freeuser-link m-right-sm" style="color:rgba(156,43,108,1)"></i><?php echo $this->translate("Subscription Month") ?></span>
                                    <span class="m-right-sm"><i class="fa fa-circle referal-link m-right-sm" style="color:rgba(17,156,220,1)"></i><?php echo $this->translate("Subscription Annually") ?></span>
                                    <span><i class="fa fa-circle partnership-link m-right-sm" style="color:rgba(255,0,0,0.2)"></i><?php echo $this->translate("Total") ?></span>
                                    <ul class="list-unstyled list-inline pull-right">
                                        <li class="no-padding"><a id="dayg" ><?php echo $this->translate("Days") ?></a></li>
                                        <li  class="no-padding">- <a id="weekg"><?php echo $this->translate("Weeks") ?></a></li>
                                        <li class="no-padding">- <a id="monthg"><?php echo $this->translate("Months") ?></a></li>
                                    </ul>
                                </div>
                                <div class="m-top-sm" style="height:300px;width:100%">
                                    <canvas id="financeCanvas" style="height:300px; width:100%;"></canvas>
                                </div>


                            </div>

                        </div>
                    </div><!-- ./smart-widget-inner -->
                </div>
            </div>
        </div>


        <!--        <div class="row">
                    <div class="col-md-12">
                        <div class="smart-widget">
                            <div class="smart-widget-header border-bottom">
<?php echo $this->translate("OVERVIEW FASHIONLEARN") ?>
        
                            </div>
                            <div class="smart-widget-inner">
                                <div class="smart-widget-body no-padding">
                                    <div class="padding-md">
                                        <div class="table-responsive">
                                            <table class="table text-center no-m-bottom bg-headblue">
                                                <thead class="">
                                                    <tr class="marginTB-sm">
                                                        <th class="text-center"><?php echo $this->translate("Month Reference") ?></th>
                                                        <th class="text-center"><?php echo $this->translate("Nº Teacher") ?></th>
                                                        <th class="text-center"><?php echo $this->translate("Nº of class") ?></th>
                                                        <th class="text-center"><?php echo $this->translate("Premium Monthly") ?></th>
                                                        <th class="text-center"><?php echo $this->translate("Total received Monthly") ?></th>
                                                        <th class="text-center"><?php echo $this->translate("Premium Annually") ?></th>
                                                        <th class="text-center"><?php echo $this->translate("Total received Annually") ?></th>
                                                        <th class="text-center"><?php echo $this->translate("Total Divided Month+Anually") ?></th>
                                                        <th class="text-center"><?php echo $this->translate("Referral Teacher Payment") ?></th>
                                                        <th class="text-center"><?php echo $this->translate("Total general") ?></th>
                                                        <th class="text-center"><?php echo $this->translate("Total of students") ?></th>
                                                        <th class="text-center"><?php echo $this->translate("Leftover") ?></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
<?php if (isset($this->adminmonthlydatas)) {
    foreach ($this->adminmonthlydatas as $value) {
        ?>
                
                
                
                
                                                                    <tr>
                                                                        <td><?php echo $value['Month'] . '/';
        echo $this->year;
        ?></td>
                                                                        <td><?php echo $value['no_of_teacher']; ?></td>
                                                                        <td><?php echo $value['no_of_class']; ?></td>
                                                                        <td><?php echo $value['Total_subscibe_monthly'] ?></td>
                                                                        <td>R$ <?php echo $value['monthly_earned'] ?></td>
                                                                        <td><?php echo $value['Total_subscribe_Annually'] ?></td>
                                                                        <td>R$ <?php echo $value['annual_earned'] ?></td>
                                                                        <td>R$ <?php echo $value['Teacher_patternship'] ?></td>
                                                                        <td>R$ 105,00</td>
                                                                        <td>R$ <?php echo $value['Total'] ?></td>
                                                                        <td><?php echo $value['no_of_student'] ?></td>
                                                                        <td>R$ <?php echo $value['monthlyleftover'] ?></td>
                
                                                                    </tr>
    <?php }
}
?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
        
                    </div>
                </div>-->
    </div>



</div>



<script>
    $(function() {
        $('.chart').easyPieChart({
            easing: 'easeOutBounce',
            size: '140',
            lineWidth: '7',
            barColor: '#7266ba',
            onStep: function(from, to, percent) {
                $(this.el).find('.percent').text(Math.round(percent));
            }
        });

        $('.sortable-list').sortable();

        $('.todo-checkbox').click(function() {

            var _activeCheckbox = $(this).find('input[type="checkbox"]');

            if (_activeCheckbox.is(':checked')) {
                $(this).parent().addClass('selected');
            }
            else {
                $(this).parent().removeClass('selected');
            }

        });

        //Delete Widget Confirmation
        $('#deleteWidgetConfirm').popup({
            vertical: 'top',
            pagecontainer: '.container',
            transition: 'all 0.3s'
        });
    });


</script>
<script>
    $('[data-toggle="popover"]').popover({trigger: "hover focus"});

    $(window).on("load resize", function() {
        var width = $(window).width();

        if (width <= 500) {
            $('.followers').removeClass('col-xs-5').addClass('col-xs-11')
            $('.new-project').children().removeClass('col-xs-6').addClass('col-xs-12')

        }
        if (width > 500) {
            $('.followers').removeClass('col-xs-11').addClass('col-xs-5')
            $('.new-project').children().removeClass('col-xs-12').addClass('col-xs-6')
        }
        if (width < 768) {
            $('.followers').removeClass('margin-15px').addClass('margin-sm')
            $('.dashboard-brief').children().removeClass('col-xs-6').addClass('col-xs-12');
        }
        if (width >= 768) {
            $('.followers').removeClass('margin-sm').addClass('margin-15px')
            $('.dashboard-brief').children().removeClass('col-xs-12').addClass('col-xs-6');
        }


    });



</script>

<!--<script>
    var labeolsArray = [];
    var teacherDivision = [];
    var subAnual = [];
    var submonthly = [];
<?php foreach ($this->adminmonthlydatas as $data) {
    ?>
            labeolsArray.push(<?= $data['Month'] ?>);
            teacherDivision.push(<?= $data['Teacher_patternship'] ?>);
            subAnual.push(<?= $data['Total_subscribe_Annually'] ?>);
            submonthly.push(<?= $data['Total_subscibe_monthly'] ?>);
<?php } ?>
//    var a = [100, 5, 2, 3, 3, 5, 5];
    var lineChartData = {
        labels: labeolsArray,
        datasets: [
            {
                label: "My First dataset",
                fillColor: "rgba(156,43,108,0.2)",
                strokeColor: "rgba(156,43,108,1)",
                pointColor: "rgba(156,43,108,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(220,220,220,1)",
                data: teacherDivision
            },
            {
                label: "My Second dataset",
                fillColor: "rgba(17,156,220,0.2)",
                strokeColor: "rgba(17,156,220,1)",
                pointColor: "rgba(17,156,220,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(151,187,205,1)",
                data: subAnual
            },
            {
                label: "My third dataset",
                fillColor: "rgba(17,156,220,0.2)",
                strokeColor: "rgba(17,156,220,1)",
                pointColor: "rgba(17,156,220,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(151,187,205,1)",
                data:submonthly
            }
        ]

    }

    window.onload = function () {
        var ctx = document.getElementById("financeCanvasd").getContext("2d");
        window.myLine = new Chart(ctx).Line(lineChartData, {
            responsive: true
        });
    }

    Morris.Donut({
        element: 'donut-finance',
        data: [
            {label: "Illustrator to \n fashion designer", value: 12},
            {label: "Illustrator to \n fashion designer", value: 30},
            {label: "Illustrator to \n fashion designer", value: 20},
        ],
        colors: ["#44465f", "#626b85", "#9ca1b7"],
        formatter: function (y) {
            return "\n$200,00"
        }
    });

</script>-->


<script>
    window.onload = function() {
        $("#dayg").trigger("click");
    }

    $("#dayg").click(function() {
//            var arr=  <?php // echo json_decode($this->daysreport->labels);  ?> 
        var labels = new Array();
        var data1 = new Array();
        var data2 = new Array();
        var data3 = new Array();

<?php foreach ($this->daysreport["labels"] as $key => $val) { ?>
            labels.push('<?php echo $val; ?>');
<?php } ?>

<?php foreach ($this->daysreport["submonthly"] as $key => $val) { ?>
            data1.push('<?php echo $val; ?>');
<?php } ?>

<?php foreach ($this->daysreport["subAnual"] as $key => $val) { ?>
            data2.push('<?php echo $val; ?>');
<?php } ?>
<?php foreach ($this->daysreport["total"] as $key => $val) { ?>
            data3.push('<?php echo $val; ?>');
<?php } ?>


//             var arr= ["January","February","March","April","May","June","July"];

        var lineChartData1 = {
            labels: labels,
            datasets: [
                {
                    label: "My First dataset",
                    fillColor: "rgba(156,43,108,0.2)",
                    strokeColor: "rgba(156,43,108,1)",
                    pointColor: "rgba(156,43,108,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(220,220,220,1)",
                    data: data1
                },
                {
                    label: "My Second dataset",
                    fillColor: "rgba(17,156,220,0.2)",
                    strokeColor: "rgba(17,156,220,1)",
                    pointColor: "rgba(17,156,220,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(151,187,205,1)",
                    data: data2
                },
                {
                    label: "My Second dataset",
                    fillColor: "rgba(255,0,0,0.1)",
                    strokeColor: "rgba(255,0,0,0.2)",
                    pointColor: "rgba(255,0,0,0.2)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(151,187,205,1)",
                    data: data3
                }
            ]

        }
        if (window.myLine)
            window.myLine.destroy();


        var ctx = document.getElementById("financeCanvas").getContext("2d");

        window.myLine = new Chart(ctx).Line(lineChartData1, {
            responsive: true
        });

    });
</script>
<script>

    $("#weekg").click(function() {


        var labels = new Array();
        var data1 = new Array();
        var data2 = new Array();
        var data3 = new Array();
        var data4 = new Array();
<?php foreach ($this->weeksreport["labels"] as $key => $val) { ?>
            labels.push('<?php echo $val; ?>');
<?php } ?>

<?php foreach ($this->weeksreport["submonthly"] as $key => $val) { ?>
            data1.push('<?php echo $val; ?>');
<?php } ?>

<?php foreach ($this->weeksreport["subAnual"] as $key => $val) { ?>
            data2.push('<?php echo $val; ?>');
<?php } ?>
<?php foreach ($this->weeksreport["total"] as $key => $val) { ?>
            data3.push('<?php echo $val; ?>');
<?php } ?>


//             var arr= ["January","February","March","April","May","June","July"];

        var lineChartData2 = {
            labels: labels,
            datasets: [
                {
                    label: "My First dataset",
                    fillColor: "rgba(156,43,108,0.2)",
                    strokeColor: "rgba(156,43,108,1)",
                    pointColor: "rgba(156,43,108,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(220,220,220,1)",
                    data: data1
                },
                {
                    label: "My Second dataset",
                    fillColor: "rgba(17,156,220,0.2)",
                    strokeColor: "rgba(17,156,220,1)",
                    pointColor: "rgba(17,156,220,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(151,187,205,1)",
                    data: data2
                },
                {
                    label: "My Second dataset",
                    fillColor: "rgba(255,0,0,0.1)",
                    strokeColor: "rgba(255,0,0,0.2)",
                    pointColor: "rgba(255,0,0,0.2)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(151,187,205,1)",
                    data: data3
                }
            ]

        }

        if (window.myLine)
            window.myLine.destroy();

        var ctx = document.getElementById("financeCanvas").getContext("2d");

        window.myLine = new Chart(ctx).Line(lineChartData2, {
            responsive: true
        });


    });



</script>


<script>

    $("#monthg").click(function() {


        var labels = new Array();
        var data1 = new Array();
        var data2 = new Array();
        var data3 = new Array();

<?php foreach ($this->monthsreport["labels"] as $key => $val) { ?>
            labels.push('<?php echo $val; ?>');
<?php } ?>

<?php foreach ($this->monthsreport["submonthly"] as $key => $val) { ?>
            data1.push('<?php echo $val; ?>');
<?php } ?>

<?php foreach ($this->monthsreport["subAnual"] as $key => $val) { ?>
            data2.push('<?php echo $val; ?>');
<?php } ?>
<?php foreach ($this->monthsreport["total"] as $key => $val) { ?>
            data3.push('<?php echo $val; ?>');
<?php } ?>


//             var arr= ["January","February","March","April","May","June","July"];

        var lineChartData2 = {
            labels: labels,
            datasets: [
                {
                    label: "My First dataset",
                    fillColor: "rgba(156,43,108,0.2)",
                    strokeColor: "rgba(156,43,108,1)",
                    pointColor: "rgba(156,43,108,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(220,220,220,1)",
                    data: data1
                },
                {
                    label: "My Second dataset",
                    fillColor: "rgba(17,156,220,0.2)",
                    strokeColor: "rgba(17,156,220,1)",
                    pointColor: "rgba(17,156,220,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(151,187,205,1)",
                    data: data2
                },
                {
                    label: "My Second dataset",
                    fillColor: "rgba(255,0,0,0.1)",
                    strokeColor: "rgba(255,0,0,0.2)",
                    pointColor: "rgba(255,0,0,0.2)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(151,187,205,1)",
                    data: data3
                }
            ]

        }

        if (window.myLine)
            window.myLine.destroy();

        var ctx = document.getElementById("financeCanvas").getContext("2d");

        window.myLine = new Chart(ctx).Line(lineChartData2, {
            responsive: true
        });


    });



</script>