<div id="content">
    <h4><?php echo $this->translate("Depositor Details") ?></h4>
    <div class="innerLR">

        <!-- Widget -->
        <div class="widget">

            <!-- Widget heading -->
            <div class="widget-head">
                <h4 class="heading"><?php echo $this->translate("Depositor Manage") ?></h4>
            </div>
            <!-- // Widget heading END -->

            <div class="widget-body">

                <!-- Table -->
                <table class="dynamicTable table table-striped table-bordered table-condensed">

                    <!-- Table heading -->
                    <thead>
                        <tr>
                            <th><?php echo $this->translate("No") ?></th>
                            <th><?php echo $this->translate("User Name") ?></th>
                            <th><?php echo $this->translate("Pay Method") ?></th>
                            <th><?php echo $this->translate("Amount") ?></th>
                            <th><?php echo $this->translate("Confirmation Code") ?></th>
                            <th><?php echo $this->translate("Transaction Date") ?></th>                            
                        </tr>
                    </thead>
                    <!-- // Table heading END -->

                    <!-- Table body -->
                    <tbody>
                    <?php if(isset($this->transaction)): $row = 0; foreach($this->transaction as $depositorDetails): $row ++;?>
                        <!-- Table row -->
                        <tr class="gradeA">
                            <td><?php echo $row; ?></td>
                            <td><?php echo $depositorDetails['user_name']; ?></td>
                            <td><?php echo $depositorDetails['transaction_type']; ?></td>
                            <td><?php echo $depositorDetails['transaction_amount']; ?></td>                            
                            <td><?php echo $depositorDetails['confirmation_code']; ?></td>
                            <td><?php echo date("j F Y ", strtotime($depositorDetails['transaction_date'])); ?></td>                            
                            
                        </tr>
                        <!-- // Table row END -->
                    <?php endforeach;  endif; ?>
                    </tbody>
                    <!-- // Table body END -->

                </table>
                <!-- // Table END -->

            </div>
        </div>
    </div>	
</div>
<script>
    $('#menu_components1').removeClass('collapse').addClass('in collapse');
    $('#payment_setting').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons cogwheels active');
    $('#payment_details_menu').addClass('active');    
</script>
