<div id="content">
    <h4><?php echo $this->translate("Payment Approval") ?></h4>
    <div class="innerLR">

        <!-- Widget -->
        <div class="widget">

            <!-- Widget heading -->
            <div class="widget-head">
                <h4 class="heading"><?php echo $this->translate("Payment Manage") ?></h4>
            </div>
            <!-- // Widget heading END -->

            <div class="widget-body">

                <!-- Table -->
                <table class="dynamicTable table table-striped table-bordered table-condensed">

                    <!-- Table heading -->
                    <thead>
                        <tr>
                            <th><?php echo $this->translate("No") ?></th>
                            <th><?php echo $this->translate("User") ?></th>
                            <th class="center"><?php echo $this->translate("Amount") ?></th>
                            <th class="center"><?php echo $this->translate("Pay Method") ?></th>
                            <th class="center"><?php echo $this->translate("Request Date") ?></th>
                            <th class="center"><?php echo $this->translate("Status") ?></th>
                            <th class="center"><?php echo $this->translate("Action") ?></th>
                        </tr>
                    </thead>
                    <!-- // Table heading END -->

                    <!-- Table body -->
                    <tbody>      
                        <?php if(isset($this->withdrawal)): $row = 0; foreach($this->withdrawal as $withdrawalDetails): $row ++;?>
                        <!-- Table row -->
                        <tr class="gradeA">
                            <td><?php echo $row; ?></td>
                            <td><?php echo $withdrawalDetails['user_name']; ?></td>
                            <td class="center"><?php echo $withdrawalDetails['requested_amt']; ?></td>
                            <td class="center"><?php if($withdrawalDetails['pay_method'] == '1'): echo "Paypal"; elseif($withdrawalDetails['pay_method'] == '2'): echo "Check"; endif; ?></td>
                            <td class="center"><?php echo date("j F Y, h:i:s A", strtotime($withdrawalDetails['request_date'])); ?></td>
                            <?php if($withdrawalDetails['status']==0): ?>                            
                            <td id="activewithdrawal_<?php echo $withdrawalDetails['withdrawal_id']; ?>" class="center js-sortable-handle userdeactive"><?php echo $this->translate("Pending") ?></td>
                            <td class="center" style="width: 80px;"><a href="#" id="<?php if (isset($withdrawalDetails['withdrawal_id'])): echo "withdrawal_" . $withdrawalDetails['withdrawal_id']; endif;?>" class="withdrawalapproval">
                            <span id="activeclass_<?php echo $withdrawalDetails['withdrawal_id']; ?>"  class="label label-block label-primary"><?php echo $this->translate("Approval") ?></span></a></td>
                            <?php endif;?> 
                        </tr>
                        <?php endforeach;  endif; ?>
                        <!-- // Table row END -->                    

                    </tbody>
                    <!-- // Table body END -->

                </table>
                <!-- // Table END -->

            </div>
        </div>
    </div>	
</div>
<script>
    $('#menu_components1').removeClass('collapse').addClass('in collapse');
    $('#payment_setting').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons cogwheels active');
    $('#payment_approval_menu').addClass('active');    
</script>
