

<style>
    table {
        margin-top: 1% !important;
    }
    th.thead-content {
        width: 12px !important;
    }
    .sorting, .sorting_asc, sorting_desc {
        font-size: 12px;
        vertical-align: middle !important;
    }
    table.dataTable tbody td {
        font-size: 13px;
        vertical-align: middle;
    }
    .history-content {
        margin-bottom: 20px;
        max-height: 500px;
        overflow-y: scroll;
    }
    .history-content table td {
        font-size: 12px;
        padding: 4% 0 !important;
    }
    .history-content table tr:first-child td {
        border-top: none;
    }
    .annualview th, #annualview td {
        text-align: center;
        vertical-align: middle !important; 
    }
    .table-striped.annualview > tbody > tr:nth-of-type(2n+1) {
        background-color: #fff;
    }
    .widget-stat2 .stat-icon {
        font-size: 53px;
        padding: 30px 10px;
        width: 35%;
        min-height: 150px;
    }
    .bg-gray {
        background-color: #9ca1b7 !important;
        color: #fff;
    }
    .widget-stat2 .stat-value {
        width: 65%;
    }
    #annualoverview td {
        border-bottom: 1px solid #ddd;
        text-align: center;
        vertical-align: middle;
    }
</style>

<div class="main-container">
    <div class="padding-md">
        <div class="row" id ="paymentalertmessage" style="display:none;">
            <div class="col-md-6 col-md-offset-3 text-center">
                <div class="well bg-danger caution">
                    <h4><b>Some Error occured , please select appropriate month & year</b></h4>
                </div>
            </div>
        </div>
        <div class="row" id ="paymentalertmessage2" style="display:none;">
            <div class="col-md-6 col-md-offset-3 text-center">
                <div class="well bg-danger">
                    <h4><b>Some Error occured , please select atleast one user to pay</b></h4>
                </div>
            </div>
        </div>
        <div class="row" id ="paymentalertmessage4" style="display:none;">
            <div class="col-md-6 col-md-offset-3 text-center">
                <div class="well bg-danger">
                    <h4><b>Please select year first</b></h4>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-sm-6">
                <h5><?php echo $this->translate("PAYMENT CONTROL DASHBOARD") ?></h5>  
                <div class="pull-left" style="margin-right: 2%;">
                    <label class="inline-block top-m15px">Month</label>
                    <div class="input-group inline-block top-m5px">
                        <select id="selectmonthrevenue" class="form-control input-sm">
                            <option value="0">select Year first</option>
                          
                        </select>
                    </div>
                </div>
                <div class="pull-left" style="margin-right: 2%;">
                    <label class="inline-block top-m15px">Year</label>
                    <div class="input-group inline-block top-m5px">
                        <select id="selectyearrevenue" class="form-control input-sm">
                            <option value="0">select year</option>
                            <?php if(isset($this->years)){ foreach ( $this->years as $value) { ?>
                         <option value="<?php echo $value['years'];?>"><?php echo $value['years'];?></option>
                           <?php } }?>
                        
                       </select>
                    </div>
                </div>


            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                <div class="widget-stat2">
                    <div class="stat-icon bg-gray">
                        <i class="block icon-064"></i>
                    </div>
                    <div class="stat-value">
                        <div class="h2 no-margin"><?php echo $this->admincurstatistcs['cur_month_userscount']; ?></div>
                        <div class="text-muted"><?php echo $this->translate("Total of Paid Monthly") ?></div>
                        <div class="text-muted" style="margin-top: 2%;">
                            <span class="badge badge-success"> R$ <?php echo round($this->admincurstatistcs['monthly_sum'], 2); ?></span> <small>(this Month)</small></br>
                            <span class="badge badge-success" id="lastmonthmonthsum"> R$ <?php echo round($this->admincurstatistcs['last_month_sum'], 2); ?></span> <small>(Last Month)</small></br>
                            <strong id="monthdiff"><?php echo round($this->admincurstatistcs['month_differencs'], 2); ?>%</strong>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                <div class="widget-stat2">
                    <div class="stat-icon bg-gray">
                        <i class="block icon-065"></i>
                    </div>
                    <div class="stat-value">
                        <div class="h2 no-margin"><?php echo $this->admincurstatistcs['cur_year_userscount']; ?></div>
                        <div class="text-muted"><?php echo $this->translate("Total of Paid Annually") ?></div>
                        <div class="text-muted" style="margin-top: 2%;">
                            <span class="badge badge-warning"> R$ <?php echo round($this->admincurstatistcs['yearly_sum'], 2); ?></span> <small>(this Month)</small></br>
                            <span class="badge badge-success" id="lastmonthyearsum"> R$ <?php echo round($this->admincurstatistcs['last_month_yearsum'], 2); ?></span> <small>(Last Month)</small></br>
                            <strong id="yeardiff"><?php echo round($this->admincurstatistcs['yearly_differencs'], 2); ?>%</strong>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                <div class="widget-stat2">
                    <div class="stat-icon bg-gray">
                        <i class="block icon-066"></i>
                    </div>
                    <div class="stat-value">
                        <div class="h2 no-margin"><?php echo $this->admincurstatistcs['admin_weigtage']; ?>%</div>
                        <div class="text-muted">percentage of <?php echo $this->translate("Month") ?></div>
                        <div class="text-muted" style="margin-top: 2%;">
                            <span class="badge badge-danger"> R$ <?php echo round($this->admincurstatistcs['admin_weightage_amount'], 2); ?></span> <small>(this Month)</small></br>
                            <span class="badge badge-success" id="lastmonthadminrev"> R$ <?php echo round($this->admincurstatistcs['last_month_admincomm'], 2); ?></span> <small>(Last Month)</small></br>
                            <strong id="admindiff"><?php echo round($this->admincurstatistcs['admin_revenue'], 2); ?>%</strong>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
                <div class="widget-stat2">
                    <div class="stat-icon bg-gray">
                        <i class="block icon-073"></i>
                    </div>
                    <div class="stat-value">
                        <div class="h2 no-margin"><?php echo $this->translate("Left Over") ?></div>
                        <div class="text-muted"><?php echo $this->translate("Current Month") ?></div>
                        <div class="text-muted" style="margin-top: 2%;">
                            <span class="badge badge-purple"> R$ <?php echo round($this->admincurstatistcs['current_leftover'], 2); ?></span> <small>(this Month)</small></br>
                            <span class="badge badge-success" id="lastmonthleft"> R$ <?php echo round($this->admincurstatistcs['last_leftover'], 2); ?></span> <small>(Last Month)</small></br>
                            <strong id="adminleft"><?php echo round($this->admincurstatistcs['admin_leftover'], 2); ?>%</strong>
                        </div>
                    </div>
                </div>
            </div>

        </div>        




        <div class="row">
            <div class="col-md-12">
                <div class="smart-widget">
                    <div class="smart-widget-header border-bottom">
                        <?php echo $this->translate("TEACHER PAYMENT CONTROL") ?> <small>( <?php echo $this->translate("Your transfer is made on 15 day of each month") ?>)</small>
                        <div class="pull-right">
                            <label  class="inline-block top-m15px"><?php echo $this->translate("Year") ?></label>
                            <div class="input-group inline-block top-m5px">
                                <select class="form-control input-sm" id='selectYear'>
                                  <option value="0">select year</option>
                     <?php if(isset($this->teachersYears)){ foreach ( $this->teachersYears as $value) { ?>
                         <option value="<?php echo $value['years'];?>"><?php echo $value['years'];?></option>
                           <?php } }?>
                                </select>
                            </div>
                        </div>
                        <div class="pull-right" style="margin-right: 2%;">
                            <label  class="inline-block top-m15px"><?php echo $this->translate("Month") ?></label>
                            <div class="input-group inline-block top-m5px">
                                <select class="form-control input-sm" id='selectmonth'>
                                    <option value = '0'>select Year first</option>
                                   
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="smart-widget-inner">
                        <div class="smart-widget-body no-padding">
                            <div class="padding-md">
                                <div class="table-responsive">
                                    <table class="table text-center no-m-bottom bg-headblue" id="dataTableLarge">
                                        <thead class="">
                                            <tr class="marginTB-sm">
                                                <th class="text-center thead-content"><input type="checkbox" class="checkbox" /></th>
                                                <th class="text-center"><?php echo $this->translate("Name of teacher") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Total Class by teacher") ?></th>
                                                <th class="text-center"><?php echo $this->translate("No. total of Student") ?></th>
                                                <th class="text-center"><?php echo $this->translate("No. of Project") ?></th>
                                                <th class="text-center"><?php echo $this->translate("% Projects") ?></th>
                                                <th class="text-center"><?php echo $this->translate("% Students") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Total Percent") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Satisfaction percent") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Commission without Satisfaction") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Commission With Satisfaction") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Leftover") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Date") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Transaction id") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Pay Status") ?></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            if (isset($this->teacherpayinfo)) {
                                                foreach ($this->teacherpayinfo as $value) {
                                                    ?>
                                                    <tr>
                                                        <td><input type="checkbox" class="tablecheckbox"  data-payid ="<?php echo $value['pay_id'] ?>"/></td>
                                                        <td><?php echo $value['first_name'] . $value['last_name'] ?></td>
                                                        <td><?php echo $value['total_classes'] ?></td>
                                                        <td><?php echo $value['total_students'] ?></td>
                                                        <td><?php echo $value['total_projects'] ?></td>
                                                        <td><?php echo $value['projects_percentage'] ?></td>
                                                        <td><?php echo $value['students_percentage'] ?></td>
                                                        <td><?php echo $value['total_percentage'] ?>%</td>
                                                        <td id="test"><?php echo $value['satisfaction']; ?>%</td>
                                                        <td id="test"><?php echo $value['with_satisfaction']; ?></td>
                                                        <td id="test"><?php echo $value['without_satisfaction']; ?></td>
                                                        <td><?php echo $value['leftover']; ?></td>
                                                        <td><?php echo $value['pay_date']; ?></td>
                                                        <td><?php
                                                            if (!empty($value['trans_id'])) {
                                                                echo $value['trans_id'];
                                                            } else {
                                                                echo 'no data';
                                                            }
                                                            ?></td>
                                                        <td>
                                                            <?php if ($value['payment_status'] == 1) { ?>
                                                                <label class="label label-success"  id="<?php echo $value['user_id']; ?>"><?php echo $this->translate("Paid") ?></label>
                                                            <?php } else if ($value['payment_status'] == 0) { ?>
                                                                <label  class=" label label-danger status" id="<?php echo $value['user_id']; ?>"><?php echo $this->translate("Unpaid") ?></label>
                                                            <?php } else if ($value['payment_status'] == 2) {
                                                                ?>
                                                                <label  class=" label label-info status" id="<?php echo $value['user_id']; ?>"><?php echo $this->translate("Pending") ?></label>
                                                            <?php } else if ($value['payment_status'] == 3) { ?>
                                                                <label  class=" label label-warning status" id="<?php echo $value['user_id']; ?>"><?php echo $this->translate("Failed") ?></label>
                                                            <?php } else if ($value['payment_status'] == 4) { ?>
                                                                <label  class=" label label-primary status" id="<?php echo $value['user_id']; ?>"><?php echo $this->translate("Processing") ?></label>
                                                            <?php } else if ($value['payment_status'] == 5) { ?>
                                                                <label  class=" label label-default status" id="<?php echo $value['user_id']; ?>"><?php echo $this->translate("Canceled") ?></label>
                                                            <?php } else if ($value['payment_status'] == 6) { ?>
                                                                <label  class=" label label-purple status" id="<?php echo $value['user_id']; ?>"><?php echo $this->translate("Transferred to next month") ?></label>
                                                            <?php } else {
                                                                ?>
                                                                <label  class=" label label-danger status" id="<?php echo $value['user_id']; ?>"><?php echo $this->translate("No status") ?></label>     

                                                            <?php }
                                                            ?>
                                                        </td>
                                                    </tr>
                                                    <?php
                                                }
                                            }
                                            ?>

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="padding-md">
                                <button class="btn btn-danger" id="btnGetAllTeachers" ><?php echo $this->translate("Pay Teacher") ?></button>  
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-md-12">
                <div class="smart-widget">
                    <div class="smart-widget-header border-bottom">
                        <?php echo $this->translate("ANNUAL VIEW TO PAY TEACHER") ?> <small>( <?php echo $this->translate("Your transfer is made on 15 day of each month") ?> )</small>
                        <div class="pull-right">
                            <button class="btn btn-primary anualoverviewmodal" style="margin-top: -12%; margin-right: 10%;"  id="annualviewcontrol" data-year="<?php echo date('Y'); ?>" >Details</button>
                        </div> 
                        <div class="pull-right" style="margin-right: 1%;">
                            <label  class="inline-block top-m15px">Period</label>
                            <div class="input-group inline-block top-m5px">
                                <select class="form-control input-sm" id="annualyear">
                                     <option value = '0'>select year</option>
                        <?php if(isset($this->years)){ foreach ( $this->years as $value) { ?>
                         <option value="<?php echo $value['years'];?>"><?php echo $value['years'];?></option>
                           <?php } }?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="smart-widget-inner">
                        <div class="smart-widget-body no-padding">
                            <div class="padding-md">
                                <div class="table-responsive">
                                    <table class="table text-center no-m-bottom bg-headblue" id="dataTableLarge1">
                                        <thead class="">
                                            <tr class="marginTB-sm">
                                                <th class="text-center"><?php echo $this->translate("Month") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Total annual subscriptions") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Total monthly subcriptions") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Total Earned by annual subscription &nbsp (/12)") ?> R$</th>
                                                <th class="text-center"><?php echo $this->translate("Total Earned by monthly subscription") ?> R$</th>
                                                <th class="text-center"><?php echo $this->translate("Sum(M+Y) this month") ?> R$</th>
                                                <th class="text-center"><?php echo $this->translate("Teacher partnership (%)") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Amount to divide") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Total Already divided") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Balance to divide") ?></th>

                                            </tr>
                                        </thead>
                                        <tbody>
<?php
if (isset($this->adminmonthlystatistics)) {

    foreach ($this->adminmonthlystatistics as $value) {
        ?>
                                                    <tr>
                                                        <td> <?php echo date("F", strtotime($value['pay_date'])); ?></td>
                                                        <td> <?php echo $value['totalannualsubscriptions']; ?></td>
                                                        <td> <?php echo $value['totalmonthlysubscriptions']; ?></td>
                                                        <td> <?php echo round($value['totalthismonthyearlysum']); ?></td>
                                                        <td> <?php echo $value['totalthismonthmonthlysum']; ?></td>
                                                        <td> <?php echo round($value['monthlyplusyearly']); ?></td>
                                                        <td> <?php echo $value['teacherpartnershippercent']; ?></td>
                                                        <td> <?php echo round($value['amounttodivide'], 2); ?></td>
                                                        <td> <?php echo round($value['alreadydivided'], 2); ?></td>
                                                        <td> <?php echo round($value['balance_to_divide'], 2); ?></td>


                                                    </tr>


        <?php
    }
}
?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="col-md-12">
                <div class="smart-widget">
                    <div class="smart-widget-header border-bottom">
<?php echo $this->translate("REFERAL TEACHER PAYMENT CONTROL <small>( Your transfer is made on 15 day of each month)") ?></small>


                        <div class="pull-right">
                            <label  class="inline-block top-m15px"><?php echo $this->translate("Year") ?></label>
                            <div class="input-group inline-block top-m5px">
                                <select class="form-control input-sm" id='referralselectYear'>
                                    <option value = '0'>select year</option>
                                   
                                    <?php if(isset( $this->refyears)){ foreach (  $this->refyears as $value) { ?>
                         <option value="<?php echo $value['years'];?>"><?php echo $value['years'];?></option>
                           <?php } }?>
                                </select>
                            </div>
                        </div>
                        <div class="pull-right" style="margin-right: 2%;">
                            <label  class="inline-block top-m15px"><?php echo $this->translate("Month") ?></label>
                            <div class="input-group inline-block top-m5px">
                                <select class="form-control input-sm" id='referralselectmonth'>
                                    <option value = '0'>select Year first</option>
                                 
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="smart-widget-inner">
                        <div class="smart-widget-body no-padding">
                            <div class="padding-md">
                                <div class="table-responsive">
                                    <table class="table text-center no-m-bottom bg-headblue" id="dataTableLarge2">
                                        <thead class="">
                                            <tr class="marginTB-sm">
                                                <th class="text-center"><input type="checkbox" class="referralcheckbox"/>                                                                                    </th>
                                                <th class="text-center"><?php echo $this->translate("Name of teacher") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Month") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Nº Students Monthly") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Nº Students Annually") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Total Amount Monthly") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Total Amount Annually") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Total Amount") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Status") ?></th>
                                                <th class="text-center"><?php echo $this->translate("Transaction Id") ?></th>

                                            </tr>
                                        </thead>
                                        <tbody>

<?php
if (isset($this->referredteachers)) {

    foreach ($this->referredteachers as $value) {
        ?>
                                                    <tr>
                                                        <td><input type="checkbox" class="referraltablecheckbox"  data-refid ="<?php echo $value['ref_id'] ?>"/></td>
                                                        <td> <?php echo $value['first_name'] . $value['last_name']; ?></td>
                                                        <td> <?php echo date("F", strtotime($value['payment_date'])); ?></td>
                                                        <td> <?php echo $value['students_monthly']; ?></td>
                                                        <td> <?php echo $value['students_annually']; ?></td>
                                                        <td> <?php echo $value['amount_monthly']; ?></td>
                                                        <td> <?php echo $value['amount_annually']; ?></td>
                                                        <td> <?php echo $value['total_earned']; ?></td>
                                                        <td>     <?php if ($value['pay_status'] == 1) { ?>
                                                                <label class="label label-success"  id="<?php echo $value['user_id']; ?>"><?php echo $this->translate("Paid") ?></label>
                                                            <?php } else if ($value['pay_status'] == 0) { ?>
                                                                <label  class=" label label-danger status" id="<?php echo $value['user_id']; ?>"><?php echo $this->translate("Unpaid") ?></label>
                                                            <?php } else if ($value['pay_status'] == 2) {
                                                                ?>
                                                                <label  class=" label label-info status" id="<?php echo $value['user_id']; ?>"><?php echo $this->translate("Pending") ?></label>
                                                            <?php } else if ($value['pay_status'] == 3) { ?>
                                                                <label  class=" label label-warning status" id="<?php echo $value['user_id']; ?>"><?php echo $this->translate("Failed") ?></label>
                                                            <?php } else if ($value['pay_status'] == 4) { ?>
                                                                <label  class=" label label-primary status" id="<?php echo $value['user_id']; ?>"><?php echo $this->translate("Processing") ?></label>
                                                            <?php } else if ($value['pay_status'] == 5) { ?>
                                                                <label  class=" label label-default status" id="<?php echo $value['user_id']; ?>"><?php echo $this->translate("Canceled") ?></label>
                                                            <?php } else if ($value['pay_status'] == 6) { ?>
                                                                <label  class=" label label-purple status" id="<?php echo $value['user_id']; ?>"><?php echo $this->translate("Transferred to next month") ?></label>
        <?php } else {
            ?>
                                                                <label  class=" label label-danger status" id="<?php echo $value['user_id']; ?>"><?php echo $this->translate("No status") ?></label>     

                                                    <?php }
                                                    ?></td>
                                                        <td><?php
                                                    if (!empty($value['transaction_id'])) {
                                                        echo $value['transaction_id'];
                                                    } else {
                                                        echo 'no data';
                                                    }
                                                    ?></td>


                                                    </tr>


        <?php
    }
}
?>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="padding-md"><button class="btn btn-danger" id="referralpaytoday"><?php echo $this->translate("Pay Teacher") ?></button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>


        </div>
    </div>

    <!-- MODAL -->
    <div class="modal fade" id="pay-teacher" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-md" style="width: 750px;">
            <div class="modal-content">
                <div style="padding: 15px 15px 20px;" class="modal-header">
                    <button data-dismiss="modal" class="close" type="button"><span aria-hidden="true">x</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">Teacher Payment History</h4>
                </div>
                <div class="modal-body">
                    <div class="row history-content">
                        <div class="col-md-12">
                            <div class="">
                                <table class="table table-hover">
                                    <tbody id="addmessages">

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="annual-view" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-md" style="width: 750px;">
            <div class="modal-content">
                <div style="padding: 15px 15px 20px;" class="modal-header">
                    <button data-dismiss="modal" class="close" type="button"><span aria-hidden="true">x</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" style="font-weight: bold;">Teacher Annually Division (current Year)</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="">
                                <table class="table table-striped table-hover annualview">
                                    <thead>
                                        <tr>
                                            <th>Parcel</th>
                                            <th>Month</th>
                                            <th>Value</th>
                                            <th>Total Paid</th>
                                            <th>Payment</th>
                                        </tr>
                                    </thead>
                                    <tbody id="annualoverview">
                                            <?php
                                            if (isset($this->adminmonthlystatistics)) {
                                                $i = 1;
                                                foreach ($this->adminmonthlystatistics as $val) {
                                                    ?>

                                                <tr>
                                                    <td><?php echo $i; ?></td>
                                                    <td><?php echo $val['pay_date']; ?></td>
                                                    <td>R$<?php echo round($val['amounttodivide'], 2); ?></td>
                                                    <td>R$<?php echo $val['alreadydivided']; ?></td>
                                                <?php if (isset($val['unpaidcount'])) { ?>
                                                        <td>
                                                            <label class="label label-danger">Not Paid</label>
                                                        </td> 
        <?php } else { ?>
                                                        <td>
                                                            <label class="label label-success">OK</label>
                                                        </td>
                                                        <?php } ?>
                                                </tr>
                                                        <?php
                                                        $i++;
                                                    }
                                                }
                                                ?>
                                    </tbody>
                                    <tfoot id="annualtotal">
                                        <tr>
                                            <th colspan="3" style="text-align: left;"> Total Paid </th>
                                            <th> <?php
                                                if (isset($this->totalpaid)) {
                                                    echo'R$' . $this->totalpaid;
                                                } else {
                                                    echo 'R$' . $this->totalpaid;
                                                }
                                                ?></th>
                                            <th> &nbsp; </th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="pull-right" id="parcelcount">
                                <label class="label label-danger text-right"><?php echo $this->parcelspaid . '&nbsp; parcel paid'; ?></label>                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script>
        $(function() {
            $('#dataTableLarge').dataTable({
                "bAutoWidth": true,
                "bLengthChange": true,
                "bFilter": true,
                "sScrollX": "200%",
                "bScrollCollapse": true,
                "bSort": true,
                "bPaginate": true
            });
            $('#dataTableLarge1').dataTable({
                "bAutoWidth": true,
                "bLengthChange": true,
                "bFilter": true,
                "sScrollX": "200%",
                "bScrollCollapse": true,
                "bSort": true,
                "bPaginate": true
            });
            $('#dataTableLarge2').dataTable({
                "bAutoWidth": true,
                "bLengthChange": true,
                "bFilter": true,
                "sScrollX": "200%",
                "bScrollCollapse": true,
                "bSort": true,
                "bPaginate": true
            });
        });
///$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ TEACHER PAYMENT SCRIPTS $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
        /*
         * dev: priyanka varanasi
         * desc: TO select the records on the basis of month and year
         * date time :29/9/2015 7:38pm
         * 
         */

        $(document).on('change', '#selectYear', function() {

           
            var yearval = $('#selectYear').val();
            if (yearval !== '0') {
               
                $.ajax({
                    url: '/admin/getmonths-filter',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                       method:'getmonthsforteacherpayements',
                        year: yearval

                    },
                    success: function(response) {
                        var monthname = '';
                        if(response.code==200){
                             $('#selectmonth').html('');
                            $.each(response.data,function(index,val){
                   switch(val.month) {
                  case '1':
                      monthname ='Jan'
                             break;
                  case '2':
                     monthname ='Feb';
                         break;
                  case'3':
                     monthname ='Mar';
                         break;
                  case '4':
                     monthname ='Apr';
                         break;
                  case '5':
                     monthname ='May';
                         break;
                  case '6':
                     monthname ='Jun';
                         break;
                  case '7':
                     monthname ='Jul';
                         break;
                  case '8':
                     monthname ='Aug';
                         break;
                  case '9':
                     monthname ='Sep';
                         break;
                  case '10':
                     monthname ='Oct';
                         break;
                  case '11':
                     monthname ='Nov';
                         break;
                  case '12':
                     monthname ='Dec';
                         break;
                 }
                              
                               $('#selectmonth').append('<option value="'+val.month+'">'+monthname+'</option>') 
                                
                            });
                            
                        }else{
                           $('#paymentalertmessage4').show();  
                            
                        }
              
            setTimeout(function() {
                $('#paymentalertmessage4').fadeOut('slow');
            }, 2500);
                }

                });
            } else {
                $('#paymentalertmessage').show();

            }
            setTimeout(function() {
                $('#paymentalertmessage').fadeOut('slow');
            }, 2500);
        });


        /*
         * dev: priyanka varanasi
         * desc: TO select the records on the basis of month and year
         * date time :29/9/2015 7:38pm
         * 
         */

        $(document).on('change', '#selectmonth', function() {

            var monthval = $('#selectmonth').val();
            var yearval = $('#selectYear').val();
            var tablenew = $('#dataTableLarge').dataTable();
            if (monthval !== '0' && yearval !== '0') {
                $('#preloader').show();
                $.ajax({
                    url: '/admin/getteacher-paydetails',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        month: monthval,
                        year: yearval

                    },
                    success: function(response) {
                        console.log(response);
//          var res = jQuery.parseJSON(response);
                        if (response.code === 200) {
                            $('#preloader').hide();
                            tablenew.fnClearTable();
                            var i = 0;
                            $.each(response.data, function(index, value) {
                                i++;
                                var a = "";
                                var b = " ";
                                var c = " ";
                                var d = "";
                                var e = " ";
                                var f = " ";
                                var g = " ";
                                var h = " ";
                                var i = " ";
                                var j = " ";
                                var k = " ";
                                var l = " ";

                                var n = " ";
                                var o = '';
                                var p = '';
                                p = '<input type="checkbox" class="tablecheckbox" data-id="' + value.user_id + '"/></td>';
                                a = value.first_name + " " + value.last_name;
                                b = value.total_classes;
                                c = value.total_students;
                                d = value.total_projects;
                                e = value.projects_percentage;
                                f = value.students_percentage;
                                g = value.total_percentage;
                                h = value.satisfaction;
                                i = value.with_satisfaction;
                                j = value.without_satisfaction;
                                k = value.leftover;
                                l = value.pay_date;

                                if (value.trans_id === null) {
                                    n = 'no data';

                                } else {
                                    n = value.trans_id;
                                }
                                if (value.payment_status === '1') {
                                    o = '<label class="label label-success"  id="' + value.user_id + '">Paid</label>';
                                } else if (value.payment_status === '0') {
                                    o = '<label class="label label-danger status" id="' + value.user_id + '">Unpaid</label>';
                                } else if (value.payment_status === '2') {
                                    o = '<label  class=" label label-info status" id="' + value.user_id + '">Pending</label>';
                                } else if (value.payment_status === '3') {
                                    o = '<label  class=" label label-warning status" id="' + value.user_id + '">Failed</label>';
                                } else if (value.payment_status === '4') {
                                    o = '<label  class=" label label-primary status" id="' + value.user_id + '">Processing</label>';
                                } else if (value.payment_status === '5') {
                                    o = '<label  class=" label label-default status" id="' + value.user_id + '">Canceled</label>';
                                } else if (value.payment_status === '6') {
                                    o = '<label  class=" label label-purple status" id="' + value.user_id + '">Transferred-to-Nextmonth</label>';
                                } else {
                                    o = '<label class="label label-danger status" id="' + value.user_id + '">No status</label>';
                                }
                                tablenew.fnAddData([p, a, b, c, d, e, f, g, h, i, j, k, l, n, o]);
                                if (i === response.length)
                                {
                                    tablenew.draw();
                                }
                            });


                        } else {
                            $('#preloader').hide();
                            tablenew.fnClearTable();
                            var a = "";
                            var b = " ";
                            var c = " ";
                            var d = "";
                            var e = " ";
                            var f = " ";
                            var g = response.data;
                            var h = " ";
                            var i = " ";
                            var j = " ";
                            var k = " ";
                            var l = " ";
                            var n = " ";
                            var o = " ";
                            var p = '';
                            tablenew.fnAddData([p, a, b, c, d, e, f, g, h, i, j, k, l, n, o]);

                        }

                    }

                });
            } else {
                $('#paymentalertmessage').show();
            }
            setTimeout(function() {
                $('#paymentalertmessage').fadeOut('slow');
            }, 2500);
        });

        //dev: priyanka varanasi
        //desc: TO check all check boxes by cheking one
        //date Time:30/9/2015 4:09pm

        $('.checkbox').click(function(e) {
            $(".tablecheckbox").prop('checked', this.checked);
        });

        //dev: priyanka varanasi
        //desc: paying Teachers by selecting checkboxes.
        //date Time:30/9/2015 5:59pm

        $(document).on('click', '#btnGetAllTeachers', function() {
            var arr = [];
            var checboxcheckedcount = $('.tablecheckbox:checked').length;

            if (checboxcheckedcount !== 0) {

                $('#preloader').show();
                $('.tablecheckbox:checked').each(function() {

                    var userpayvalues = $(this).attr('data-payid');
                    arr.push(userpayvalues);

                });

                $.ajax({
                    url: '/admin/payment-process',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        payinfo: arr
                    },
                    success: function(response) {
                        if (response) {
                            console.log(response);
                            $('#preloader').hide();
                            $("#addmessages").html('');
                            $(response).each(function(index, val) {
                                $("#addmessages").append('<tr><td>' + val.useremail + '</td></tr>');
                            });
                            $('#pay-teacher').modal('show');
                        } else {
                            console.log(response);
                            $('#preloader').hide();
                        }
                    }
                });
            } else {

                $('#paymentalertmessage2').show();
            }
            setTimeout(function() {
                $('#paymentalertmessage2').fadeOut('slow');
            }, 2500);
        });

// $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$ CODE ENDS $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$4

//#################################### ADMIN RECORDS DISPLAY ON BASIS OF SELECT BOX IN BOXES #####################3

        /*
         * dev: priyanka varanasi
         * desc: TO select the admin revenue records on the basis of month and year
         * date time :7/10/2015 1:06pm
         * 
         */

        $(document).on('change', '#selectmonthrevenue', function() {

            var monthval = $('#selectmonthrevenue').val();
            var yearval = $('#selectyearrevenue').val();
            if (Number(monthval) !== 0 && Number(yearval) !== 0) {
                var n = new Date().getMonth();
                if (Number(monthval) - 1 !== Number(n)) {
                    $('#preloader').show();
                    $.ajax({
                        url: '/admin/getadmin-revenue',
                        type: 'POST',
                        dataType: 'json',
                        data: {
                            month: monthval,
                            year: yearval

                        },
                        success: function(response) {
                            if (response.code === 200) {
                                $('#preloader').hide();
                                $('#lastmonthmonthsum').html(response.data['lastmonth_monthlyysum']);
                                $('#lastmonthyearsum').html(response.data['lastmonth_yearlysum']);
                                $('#lastmonthadminrev').html(response.data['last_adminweightage']);
                                $('#lastmonthleft').html(response.data['last_leftover']);

                                $('#monthdiff').html(response.data['month_differencs'] + '%');
                                $('yeardiff').html(response.data['yearly_differencs'] + '%');
                                $('#admindiff').html(response.data['admin_revenue'] + '%');
                                $('#adminleft').html(response.data['admin_leftover'] + '%');
                            } else {
                                $('#preloader').hide();
                                $('.caution').html(' <h4><b>' + response.data + '</b></h4>');
                                $('#paymentalertmessage').show();

                            }

                        }
                    });
                } else {
                    $('.caution').html(' <h4><b>You have choosen current month to compare</b></h4>');
                    $('#paymentalertmessage').show();
                }
            } else {

                $('#paymentalertmessage4').show();
            }
            setTimeout(function() {
                $('#paymentalertmessage').fadeOut('slow');
            }, 2500);
        });


        /*
         * dev: priyanka varanasi
         * desc: TO select the admin revenue records on the basis of month and year
         * date time :7/10/2015 1:06pm
         * 
         */
    $(document).on('change', '#selectyearrevenue', function() {

           
            var yearval = $('#selectyearrevenue').val();
            if (yearval !== '0') {
               
                $.ajax({
                    url: '/admin/getmonths-filter',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                       method:'getmonthsforadminrevenue',
                        year: yearval

                    },
                    success: function(response) {
                        var monthname = '';
                        if(response.code==200){
                            $('#selectmonthrevenue').html('');
                            $.each(response.data,function(index,val){
                   switch(val.month) {
                  case '1':
                      monthname ='Jan'
                             break;
                  case '2':
                     monthname ='Feb';
                         break;
                  case'3':
                     monthname ='Mar';
                         break;
                  case '4':
                     monthname ='Apr';
                         break;
                  case '5':
                     monthname ='May';
                         break;
                  case '6':
                     monthname ='Jun';
                         break;
                  case '7':
                     monthname ='Jul';
                         break;
                  case '8':
                     monthname ='Aug';
                         break;
                  case '9':
                     monthname ='Sep';
                         break;
                  case '10':
                     monthname ='Oct';
                         break;
                  case '11':
                     monthname ='Nov';
                         break;
                  case '12':
                     monthname ='Dec';
                         break;
                 }
                              
                               $('#selectmonthrevenue').append('<option value="'+val.month+'">'+monthname+'</option>') 
                                
                            });
                            
                        }else{
                           $('#paymentalertmessage4').show();  
                            
                        }
              
            setTimeout(function() {
                $('#paymentalertmessage4').fadeOut('slow');
            }, 2500);
                }

                });
            } else {
                $('#paymentalertmessage').show();

            }
            setTimeout(function() {
                $('#paymentalertmessage').fadeOut('slow');
            }, 2500);
        });

//################################################## CODE ENDS #############################################

//**********************************ANNUAL OVERVIEW CONTROL SCRIPTS ****************************************
        /*
         * dev: priyanka varanasi
         * desc: TO select the records on the basis  year
         * date time :09/10/2015 5:20pm
         * 
         */

        $(document).on('change', '#annualyear', function() {

            var yrval = $('#annualyear').val();
            var tablenew = $('#dataTableLarge1').dataTable();
            $('.anualoverviewmodal').attr('data-year', '');
            $('.anualoverviewmodal').attr('data-year', yrval);
            if (yrval !== '0') {
                $('#preloader').show();
                $.ajax({
                    url: '/admin/getteacher-paydetails',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        yr: yrval

                    },
                    success: function(response) {
                        console.log(response);
//          var res = jQuery.parseJSON(response);
                        if (response.code === 200) {
                            $('#preloader').hide();
                            tablenew.fnClearTable();
                            var i = 0;
                            $.each(response.data, function(index, value) {
                                i++;
                                var a = "";
                                var b = " ";
                                var c = " ";
                                var d = "";
                                var e = " ";
                                var f = " ";
                                var g = " ";
                                var h = " ";
                                var i = " ";
                                var j = " ";
                                a = value.pay_date;
                                b = value.totalannualsubscriptions;
                                c = value.totalmonthlysubscriptions;
                                d = value.totalthismonthyearlysum;
                                e = value.totalthismonthmonthlysum;
                                f = value.monthlyplusyearly;
                                g = value.teacherpartnershippercent;
                                h = (value.amounttodivide);
                                i = (value.alreadydivided);
                                j = (value.balance_to_divide);
                                tablenew.fnAddData([a, b, c, d, e, f, g, h, i, j]);
                                if (i === response.length)
                                {
                                    tablenew.draw();
                                }
                            });


                        } else {
                            $('#preloader').hide();
                            tablenew.fnClearTable();
                            var a = "";
                            var b = " ";
                            var c = " ";
                            var d = "";
                            var e = " ";
                            var f = " ";
                            var g = response.data;
                            var h = " ";
                            var i = " ";
                            var j = " ";

                            tablenew.fnAddData([a, b, c, d, e, f, g, h, i, j]);

                        }

                    }

                });
            } else {
                $('#paymentalertmessage3').show();
            }
            setTimeout(function() {
                $('#paymentalertmessage3').fadeOut('slow');
            }, 2500);
        });


        $('#annualviewcontrol').on('click', function() {
            var year = $(this).attr('data-year');
            $('#preloader').show();
            $.ajax({
                url: '/admin/getannual-overview',
                type: 'POST',
                dataType: 'json',
                data: {
                    year: year

                },
                success: function(response) {
                    $('#annualoverview').html('');
                    $('#parcelcount').html('');
                    $('#annualtotal').html('');
                    if (response.code === 200) {
                        $(response.data1).each(function(index, val) {
                            var i = 1;
                             if (val.unpaidcount ===0 || val.unpaidcount) {
                           $('#annualoverview').append('<tr><td>' + i + '</td><td>' + val.pay_date + '</td>' +
                                        '<td>' + val.amounttodivide + '</td>' +
                                        '<td>' + val.alreadydivided + '</td>' +
                                        '<td><label class="label label-danger">Not Paid</label></td></tr>');

                            } else {
                            
                                $('#annualoverview').append('<tr><td>' + i + '</td><td>' + val.pay_date + '</td>' +
                                        '<td>' + val.amounttodivide + '</td>' +
                                        '<td>' + val.alreadydivided + '</td>' +
                                        '<td><label class="label label-success">OK</label></td></tr>');

                            }
                            i++;
                        });

                        if (response.data3) {
                            $('#annualtotal').append('<tr><th colspan="3" style="text-align: left;"> Total Paid </th><th>R$ &nbsp;' + response.data3 + '</th></tr>');
                        } else {
                            $('#annualtotal').append('<tr><th colspan="3" style="text-align: left;"> Total Paid </th><th>R$ &nbsp; 0</th></tr>');
                        }
                        $('#parcelcount').html('<label class="label label-danger text-right">' + response.data2 + '&nbsp; parcel paid</label>');
                        $('#preloader').hide();
                        $('#annual-view').modal('show');
                    } else {

                        $('#annualoverview').append('<tr><td colspan="5">No result for this year</td></tr>');
                        $('#preloader').hide();
                        $('#annual-view').modal('show');
                    }
                }

            });
        });

//********************************************** CODE ENDS ***********************************88888888888


        ///dev:priyanka varanasi
//*****************************    //desc: to filter the referral teachers on the bais of seleected month and year ******************************************88
        //date:15/10/2015


        $(document).on('change', '#referralselectmonth', function() {

            var monthval = $('#referralselectmonth').val();
            var yearval = $('#referralselectYear').val();
            var tablenew = $('#dataTableLarge2').dataTable();
            if (monthval !== '0' && yearval !== '0') {
                $('#preloader').show();
                $.ajax({
                    url: '/admin/getreferrals-details',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        month: monthval,
                        year: yearval

                    },
                    success: function(response) {
                        console.log(response);
//          var res = jQuery.parseJSON(response);
                        if (response.code === 200) {
                            $('#preloader').hide();
                            tablenew.fnClearTable();
                            var i = 0;
                            $.each(response.data, function(index, value) {
                                i++;
                                a = '<input type="checkbox" class="tablecheckbox" data-id="' + value.user_id + '"/></td>';
                                b = value.first_name + " " + value.last_name;
                                c = value.payment_date;
                                d = value.students_monthly;
                                e = value.students_annually;
                                f = value.amount_monthly;
                                g = value.amount_annually;
                                h = value.total_earned;
                                i = value.pay_status;

                                if (value.transaction_id === null || value.transaction_id === 0) {
                                    j = 'no data';

                                } else {
                                    j = value.transaction_id;
                                }
                                if (value.pay_status === '1') {
                                    i = '<label class="label label-success"  id="' + value.user_id + '">Paid</label>';
                                } else if (value.pay_status === '0') {
                                    i = '<label class="label label-danger status" id="' + value.user_id + '">Unpaid</label>';
                                } else if (value.pay_status === '2') {
                                    i = '<label  class=" label label-info status" id="' + value.user_id + '">Pending</label>';
                                } else if (value.pay_status === '3') {
                                    i = '<label  class=" label label-warning status" id="' + value.user_id + '">Failed</label>';
                                } else if (value.pay_status === '4') {
                                    i = '<label  class=" label label-primary status" id="' + value.user_id + '">Processing</label>';
                                } else if (value.pay_status === '5') {
                                    i = '<label  class=" label label-default status" id="' + value.user_id + '">Canceled</label>';
                                } else if (value.pay_status === '6') {
                                    i = '<label  class=" label label-purple status" id="' + value.user_id + '">Transferred-to-Nextmonth</label>';
                                } else {
                                    i = '<label class="label label-danger status" id="' + value.user_id + '">No status</label>';
                                }
                                tablenew.fnAddData([a, b, c, d, e, f, g, h, i, j]);
                                if (i === response.length)
                                {
                                    tablenew.draw();
                                }
                            });


                        } else {
                            $('#preloader').hide();
                            tablenew.fnClearTable();
                            var a = "";
                            var b = " ";
                            var c = " ";
                            var d = "";
                            var e = " ";
                            var f = " ";
                            var g = response.data;
                            var h = " ";
                            var i = " ";
                            var j = " ";
                            tablenew.fnAddData([a, b, c, d, e, f, g, h, i, j]);

                        }

                    }

                });
            } else {
                $('#paymentalertmessage4').show();
            }
            setTimeout(function() {
                $('#paymentalertmessage').fadeOut('slow');
            }, 2500);
        });

         $(document).on('change', '#referralselectYear', function() {

           
            var yearval = $('#referralselectYear').val();
            if (yearval !== '0') {
               
                $.ajax({
                    url: '/admin/getmonths-filter',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                       method:'getmonthsforreferredteachers',
                        year: yearval

                    },
                    success: function(response) {
                        var monthname = '';
                        $('#referralselectmonth').html('');
                        if(response.code==200){
                            $.each(response.data,function(index,val){
                   switch(val.month) {
                  case '1':
                      monthname ='Jan'
                             break;
                  case '2':
                     monthname ='Feb';
                         break;
                  case'3':
                     monthname ='Mar';
                         break;
                  case '4':
                     monthname ='Apr';
                         break;
                  case '5':
                     monthname ='May';
                         break;
                  case '6':
                     monthname ='Jun';
                         break;
                  case '7':
                     monthname ='Jul';
                         break;
                  case '8':
                     monthname ='Aug';
                         break;
                  case '9':
                     monthname ='Sep';
                         break;
                  case '10':
                     monthname ='Oct';
                         break;
                  case '11':
                     monthname ='Nov';
                         break;
                  case '12':
                     monthname ='Dec';
                         break;
                 }
                                
                               $('#referralselectmonth').append('<option value="'+val.month+'">'+monthname+'</option>') 
                                
                            });
                            
                        }else{
                           $('#paymentalertmessage4').show();  
                            
                        }
              
            setTimeout(function() {
                $('#paymentalertmessage4').fadeOut('slow');
            }, 2500);
                }

                });
            } else {
                $('#paymentalertmessage').show();

            }
            setTimeout(function() {
                $('#paymentalertmessage').fadeOut('slow');
            }, 2500);
        });


        //dev: priyanka varanasi
        //desc: TO check all check boxes by cheking one in referral section
        //date Time:15/10/2015 4:55pm

        $('.referralcheckbox').click(function(e) {
            $(".referraltablecheckbox").prop('checked', this.checked);
        });



        $(document).on('click', '#referralpaytoday', function() {

            var arr = [];
            var checboxcheckedcount = $('.referraltablecheckbox:checked').length;
            if (checboxcheckedcount !== 0) {

                $('#preloader').show();
                $('.referraltablecheckbox:checked').each(function() {

                    var referralpayvalues = $(this).attr('data-refid');
                    arr.push(referralpayvalues);

                });

                $.ajax({
                    url: '/admin/referralpayment-process',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        payinfo: arr
                    },
                    success: function(response) {
                        if (response) {
                            console.log(response);
                            $('#preloader').hide();
                            $("#addmessages").html('');
                            $(response).each(function(index, val) {
                                $("#addmessages").append('<tr><td>' + val.useremail + '</td></tr>');
                            });
                            $('#pay-teacher').modal('show');
                        } else {
                            console.log(response);
                            $('#preloader').hide();
                        }
                    }
                });
            } else {

                $('#paymentalertmessage2').show();
            }
            setTimeout(function() {
                $('#paymentalertmessage2').fadeOut('slow');
            }, 2500);
        });
    </script>
