<div id="content">
    <h4><?php echo $this->translate("Withdrawal Details") ?></h4>
    <div class="innerLR">

        <!-- Widget -->
        <div class="widget">

            <!-- Widget heading -->
            <div class="widget-head">
                <h4 class="heading"><?php echo $this->translate("Withdrawal Manage") ?></h4>
            </div>
            <!-- // Widget heading END -->

            <div class="widget-body">

                <!-- Table -->
                <table class="dynamicTable table table-striped table-bordered table-condensed">

                    <!-- Table heading -->
                    <thead>
                        <tr>
                            <th><?php echo $this->translate("No") ?></th>
                            <th><?php echo $this->translate("User") ?></th>
                            <th><?php echo $this->translate("Amount") ?></th>
                            <th><?php echo $this->translate("Pay Method") ?></th>
                            <th><?php echo $this->translate("Request Date") ?></th>
                            <th><?php echo $this->translate("Status") ?></th>
                            <th><?php echo $this->translate("Transection ID") ?></th>
                        </tr>
                    </thead>
                    <!-- // Table heading END -->

                    <!-- Table body -->
                    <tbody>      
                        <?php if(isset($this->withdrawal)): $row = 0; foreach($this->withdrawal as $withdrawalDetails): $row ++;?>
                        <!-- Table row -->
                        <tr class="gradeA">
                            <td><?php echo $row; ?></td>
                            <td><?php echo $withdrawalDetails['user_name']; ?></td>
                            <td><?php echo $withdrawalDetails['requested_amt']; ?></td>
                            <td><?php if($withdrawalDetails['pay_method'] == '1'): echo "Paypal"; elseif($withdrawalDetails['pay_method'] == '2'): echo "Check"; endif; ?></td>
                            <td><?php echo date("j F Y, h:i:s A", strtotime($withdrawalDetails['request_date'])); ?></td>                            
                            <td><?php if($withdrawalDetails['status'] == '1'): echo "Completed"; else: echo "Pending"; endif; ?></td>
                            <td><?php echo $withdrawalDetails['transaction_id']; ?></td>
                        </tr>
                        <?php endforeach;  endif; ?>
                        <!-- // Table row END -->                    

                    </tbody>
                    <!-- // Table body END -->

                </table>
                <!-- // Table END -->

            </div>
        </div>
    </div>	
</div>
<script>
    $('#menu_components1').removeClass('collapse').addClass('in collapse');
    $('#payment_setting').removeClass('hasSubmenu glyphicons cogwheels').addClass('hasSubmenu glyphicons cogwheels active');
    $('#withdrawal_details_menu').addClass('active');    
</script>
