<script>
    $(document).ready(function(){
        
//        $('#team').change(function(){
//            
//            var teamcode = $(this).val();
//            $.ajax({
//                
//                url      : './contest-ajax-handler',
//                type     : 'POST',
//                dataType : 'json',
//                data : {
//                    method   : 'getPlayerList',
//                    teamcode : teamcode
//                },
//                beforeSend : function() {
//                    
//                },
//                success : function(response) {
//                    
//                    if(response.code == 200){
//                   // console.log(response.data);
//                    
//                    //$("#player").html('');
//                    //$("#match_id").append('<option value="">Select</option>');
//                    $.each(response.data,function( index, value ) {                      
//                       $("#player").append('<option value="'+value.plr_id+'">'+value.plr_name+'</option>');                        
//                    });
//                
//                    }
//                    
//                }
//                
//            });   
//        });
//        
//    $('#addoutcome').click(function(){
//    $('#addnewoutcome').append('<div class="form-group"><label class="col-sm-2 control-label"></label><div class="col-sm-12"><input type="text" name="outcome[]" class="form-control" ></div></div> ');
//    
//    });
//        
    });
</script>

