
<?php if (isset($this->session->storage->role)){ if ($this->session->storage->role == '2') { ?>
        <?php echo $this->render('admin-header.phtml'); ?>


        <?php

}

}

?> 

<?php echo $this->layout()->content; ?>  
<?php if (isset($this->session->storage->role)){ if ($this->session->storage->role == '2') { ?>
        <?php echo $this->render('admin-footer.phtml'); ?>  
        <?php

}
}
?> 




