

<?php echo $this->render('script.phtml'); ?>
<!--<script>
    jQuery(window).load(function() {

        "use strict";

        // Page Preloader
        jQuery('#preloader').delay(350).fadeOut(function() {
            jQuery('body').delay(350).css({'overflow': 'visible'});
        });
    });
</script>-->
<script type="text/javascript">
    (function(i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function() {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-8694286-1', 'krzysztof-furtak.pl');
    ga('send', 'pageview');
</script>

</body>
</html>
<!--<iframe width="230px" height="368px" scrolling=no frameborder="0" src="http://www.soupnetworks.com/widget/feed-mlb"></iframe>-->