<?php // echo $this->doctype();   ?>
<html lang="en">
    <head>
        <?php
        # Title

        echo $this->headTitle();

        # Meta data
        echo $this->headMeta();

        # CSS
        echo $this->headLink()
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'link/bootstrap.min.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'css/style.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'css/font-awesome.min.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'css/ionicons.min.css')
//                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'css/simplify.min.css')
                //          ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'css/simplify.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'css/fashionlearn.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'css/owl.carousel.min.css')
                ->appendStylesheet($this->baseUrl() . $this->appSetting->assestPath . 'css/bootstrapValidator.min.css');
//
//
//        # Javascript
//        echo $this->headScript()
//                ->appendFile('http://fonts.googleapis.com/css?family=Raleway', 'text/css')                        
//                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'js/admin/js/jquery.min.js', 'text/javascript')
//                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'js/jquery-ui.custom.min.js', 'text/javascript')
//                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'link/bootstrap.min.js', 'text/javascript')
//                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'js/docs.min.js', 'text/javascript')
//                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'js/jquery.validate.min.js', 'text/javascript')
//                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'js/validate.settings.js', 'text/javascript')
//                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'js/jquery.localScroll.min.js', 'text/javascript')
//                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'js/jquery.slimscroll.min.js', 'text/javascript')
//                ->appendFile($this->baseUrl() . $this->appSetting->assestPath . 'js/function.js', 'text/javascript');
        ?>



        <!-- Bootstrap -->
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        
          <script src="<?php echo $this->baseUrl() . $this->appSetting->assestPath . 'js/html5shiv.js'; ?>"></script>
          <script src="<?php echo $this->baseUrl() . $this->appSetting->assestPath . 'js/respond.min.js'; ?>"></script>
        <![endif]-->

        <style>
            #preloader {
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background-color: #e4e7ea; 
                z-index: 10000; 
            }

            #status {
                width: 30px;
                height: 30px;
                font-size: 32px;
            }
        </style>
    </head>
    <body style="background-color: #E7E3E6;">
<!--        <div id="preloader">
            <div id="status"><img alt="" src="<?php echo $this->baseUrl() . $this->appSetting->assestPath . '/images/loading.gif'; ?>"></div>
        </div>-->
