	

<div class="main-container">
				<div class="padding-md">
				

				  <h3 class="header-text m-top-lg">Coupon Details</h3>

					<div class="smart-widget widget-dark-blue">
						<div class="smart-widget-header">
							<h3 class="no-margin inline-block">Coupon Details</h3>
                            
                                                        <a href ="/admin/create-coupon"><button  class="btn btn-success btn-sm pull-right">Create Coupon</button></a>
						</div>
						<div class="smart-widget-inner">
							<div class="smart-widget-body">
								<table class="table" id="couponstable">
									<thead>
					<tr>  
                                              <th>S.no</th>
                                              <th>Coupon Name</th>
					      <th>Coupon Code</th>
                                              <th>Start Date</th>
                                              <th>End Date</th>
                                              <th>Discount</th>
                                              <th>Coupon Limit</th>
                                              <th>Coupon Type</th>
					      <th>Edit</th>
                                              
					 </tr>
						</thead>
						<tbody>
                                    
                                        
            <?php if(isset($this->coupondetails)){$row = 0; foreach($this->coupondetails as $coupondetails){ $row ++;?>
        <tr>
            <td><?php echo $row ; ?></td>
            <td><?php echo $coupondetails['coupon_name'];?></td>
            <td><?php  echo $coupondetails['coupon_code'];  ?></td>
            <td><?php echo date("F j, Y", strtotime($coupondetails['coupon_startdate']));  ?></td>
            <td><?php echo date("F j, Y", strtotime($coupondetails['coupon_enddate']));  ?></td>
            <td><?php if($coupondetails['discount_type']==0){echo $coupondetails['discount_offered'].'%';}else{echo '$'.$coupondetails['discount_offered'];} ?></td>
            <td><?php  echo $coupondetails['coupon_limit'];?></td>
            <td><?php if($coupondetails['coupon_type'] ==0) { echo "One time applied";}else {echo "applied all time";}?></td>
            <td>
                <a  href="/admin/edit-coupon/<?php echo $coupondetails['coupon_id']; ?>"><button class="btn btn-success btn-sm"><span><i class="fa fa-edit"></i></span></button></a> &nbsp;&nbsp;&nbsp;
                 <!--<button  id="delete_<?php echo $coupondetails['coupon_id'];?>" coupon-data="<?php echo $coupondetails['coupon_id'];?>" class="btn btn-danger btn-sm deletecoupon" ><span><i class="fa fa-trash-o"></i></span></button>-->
          
           </td>
         </tr>
       <?php }}?>
                            
						
									</tbody>
								</table>
							</div>
						</div><!-- ./smart-widget-inner -->
					</div>


				</div><!-- ./padding-md -->
                
                
			</div>


<script>
    
    
         $(function() {
        $('#couponstable').dataTable();
    });
    
    $(document).on('click','.deletecoupon',function(){
        var couponid = $(this).attr('coupon-data');
               $.ajax({
                  
                    url: './coupons',
                    type: 'POST',
                    datatype: 'json',
                    data: {
                        
                        coupondelid: couponid
                    },
                    beforeSend: function() {

                    },
                    success: function(response) {
                        if (response) {
                          
                            $('#' + "delete_"+ couponid).parent().parent().remove();

                        }
                    }

                });
        
    });
    </script>