<div class="main-container">
    <div class="padding-md">

        <h3 class="m-left-xs header-text m-top-lg"style="margin-top:5px"><?php echo $this->translate("Create New Plan") ?></h3>
        <div class="smart-widget m-top-lg widget-dark-blue"style="margin-top:5px">
            <div class="smart-widget-inner">
                <div class="smart-widget-hidden-section">
                    <ul class="widget-color-list clearfix">
                        <li data-color="widget-dark" style="background-color:#20232b;"></li>
                        <li data-color="widget-dark-blue" style="background-color:#4c5f70;"></li>
                        <li data-color="widget-blue" style="background-color:#23b7e5;"></li>
                        <li data-color="widget-green" style="background-color:#2baab1;"></li>
                        <li data-color="widget-yellow" style="background-color:#edbc6c;"></li>
                        <li data-color="widget-orange" style="background-color:#fbc852;"></li>
                        <li data-color="widget-red" style="background-color:#e36159;"></li>
                        <li data-color="widget-purple" style="background-color:#7266ba;"></li>
                        <li data-color="widget-light-grey" style="background-color:#f5f5f5;"></li>
                        <li data-color="reset" style="background-color:#fff;"></li>
                    </ul>
                </div>
                <div class="smart-widget-body">
                    <form class="form-horizontal" id="createplan" name="createPlan" method="POST">
                        <div class="form-group">
                            <label class="col-lg-2 control-label" for="planName"><?php echo $this->translate("Plan Name") ?></label>
                            <div class="col-lg-10">
                                <input type="text" name="planname" id="planname" class="form-control" required>
                            </div><!-- /.col -->
                        </div><!-- /form-group -->
                        <div class="form-group">
                            <label class="col-lg-2 control-label" for="Amount"><?php echo $this->translate("Amount") ?></label>
                            <div class="col-lg-10">
                                <input type="text" name="amount" id="amount" class="form-control" required>
                                <span id="amount_error" style="font-size:10px; color:#F00;"></span>
                            </div><!-- /.col -->
                        </div><!-- /form-group -->
                        <div class="form-group">
                            <label class="col-lg-2 control-label" for="duration"><?php echo $this->translate("Duration(Days)") ?></label>
                            <div class="col-lg-10">
                                <input type="text" name="duration" placeholder="" id="duration" class="form-control" required>
                                <span id="dur_error" style="font-size:10px; color:#F00;"></span>
                            </div><!-- /.col -->
                        </div><!-- /form-group -->
                        <div class="form-group">
                            <label class="col-lg-2 control-label" for="trial"><?php echo $this->translate("Trial Period(Days)") ?></label>
                            <div class="col-lg-10">
                                <input type="text" name="trial" placeholder="" id="trial" class="form-control" required>
                                <span id="trial_error" style="font-size:10px; color:#F00;"></span>
                            </div><!-- /.col -->
                        </div><!-- /form-group -->


                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-success btn-sm" type="submit"><?php echo $this->translate("Create") ?></button>
                                &nbsp;&nbsp;&nbsp;
                                <a href="<?php $this->baseUrl(); ?>/admin/manageusers"><button class="btn btn-danger btn-sm"><?php echo $this->translate("Cancel") ?></button></a>

                            </div><!-- /.col -->
                        </div><!-- /form-group -->
                    </form>
                </div>
            </div><!-- ./smart-widget-inner -->
        </div>
    </div><!-- ./padding-md -->
</div><!-- /main-container -->
</div><!-- /wrapper -->

<a href="#" class="scroll-to-top hidden-print"><i class="fa fa-chevron-up fa-lg"></i></a>

<script>

    

    $(document).ready(function(){  
        $('#createplan').on('submit',function(){
            $('#amount_error').html('');
            $('#dur_error').html('');
            $('#trial_error').html('');
            var amount = document.forms["createplan"]["amount"].value;
            var dur = document.forms["createplan"]["duration"].value;
            var trial = document.forms["createplan"]["trial"].value;
            var regex = /^[0-9\b]+$/;
            var amountMatch = amount.match(regex);
            var durMatch = dur.match(regex);
            var trialMatch = trial.match(regex);
            if(amountMatch == null){
                $('#amount_error').html('');
                $('#amount_error').html('* Can be numbers only');
                return(false); 
            }
            if(durMatch == null){
                $('#dur_error').html('');
                $('#dur_error').html('* Can be numbers only');
                return(false); 
            }
            if(trialMatch == null){
                $('#trial_error').html('');
                $('#trial_error').html('* Can be numbers only');
                return(false); 
            }
            
            
        
        });
    }); 
</script>


<script>
    $(function ()	{
				

        //Wizard Step
	          
        $("#formWizard").steps({
            headerTag: "h2",
            bodyTag: "section",
            transitionEffect: "slideLeft",
            onStepChanging: function (event, currentIndex, newIndex) { 
                if(newIndex > currentIndex)	{ 
                    if($('#formExample').parsley().validate('step' + newIndex))	{
                        return true;
                    }
                    else	{
                        return false;
                    }
                }
                else	{
                    return true;
                }
	                	
            },
            onFinished: function (event, currentIndex) { 
                $('#wizardModal').modal('show')
            }

        });
    });
</script>
<script>
    $(document).ready(function(){
        setTimeout(function(){
            $('#data').fadeOut("slow"),5000});
    });
    
</script>
