<div class="main-container">


    <div class="smart-widget m-top-lg widget-dark-blue">
        <div class="smart-widget-header"style="margin-top:-33px">
            <?php echo $this->translate("Edit plan") ?>

        </div>
        <div class="smart-widget-inner">
            <div class="smart-widget-hidden-section">
                <ul class="widget-color-list clearfix">
                    <li data-color="widget-dark" style="background-color:#20232b;"></li>
                    <li data-color="widget-dark-blue" style="background-color:#4c5f70;"></li>
                    <li data-color="widget-blue" style="background-color:#23b7e5;"></li>
                    <li data-color="widget-green" style="background-color:#2baab1;"></li>
                    <li data-color="widget-yellow" style="background-color:#edbc6c;"></li>
                    <li data-color="widget-orange" style="background-color:#fbc852;"></li>
                    <li data-color="widget-red" style="background-color:#e36159;"></li>
                    <li data-color="widget-purple" style="background-color:#7266ba;"></li>
                    <li data-color="widget-light-grey" style="background-color:#f5f5f5;"></li>
                    <li data-color="reset" style="background-color:#fff;"></li>
                </ul>
            </div>
            <div class="smart-widget-body">
                <form class="form-horizontal" name="editplans"  id="editplans" method="POST">
                    <div class="form-group">
                        <label class="col-lg-2 control-label"  for="plantype"><?php echo $this->translate("Plan Type") ?></label>
                        <div class="col-lg-10">
                            <input type="text" placeholder="" value="<?php if (isset($this->selectSub)) {
    echo ($this->selectSub[0]['subscription_type']);
} ?>"  name="plantype" id="plantype" class="form-control">
                        </div><!-- /.col -->
                    </div><!-- /form-group -->
                    <div class="form-group">
                        <label class="col-lg-2 control-label" for="amount"><?php echo $this->translate("Amount") ?></label>
                        <div class="col-lg-10">
                            <input type="text" placeholder="" value="<?php if (isset($this->selectSub)) {
    echo ($this->selectSub[0]['payment_amount']);
} ?>"  name="amount" id="amount" class="form-control">
                        </div><!-- /.col -->
                    </div><!-- /form-group -->
                    <div class="form-group">
                        <label class="col-lg-2 control-label" for="duration"><?php echo $this->translate("Duration(Month)") ?></label>
                        <div class="col-lg-10">
                            <input type="text" value="<?php if (isset($this->selectSub)) {
    echo ($this->selectSub[0]['billing_period']);
} ?>"  name="duration" placeholder="" id="duration" class="form-control">
                        </div><!-- /.col -->
                    </div><!-- /form-group -->
               <div class="form-group">
                        <label class="col-lg-2 control-label" for="duration"><?php echo $this->translate("Trial Period(Days)") ?></label>
                        <div class="col-lg-10">
                            <input type="text" value="<?php if (isset($this->selectSub)) {
    echo ($this->selectSub[0]['trial_billing_period']);
} ?>"  name="duration" placeholder="" id="duration" class="form-control">
                        </div><!-- /.col -->
                    </div><!-- /form-group -->
					

                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-success btn-sm" type="submit"><?php echo $this->translate("SAVE") ?></button>
                                &nbsp;&nbsp;&nbsp;
                                <a href="<?php $this->baseUrl(); ?>/admin/membership-plans"><button class="btn btn-danger btn-sm"><?php echo $this->translate("Cancel") ?></button></a>
                            </div><!-- /.col -->
                        </div><!-- /form-group -->

                </form>
            </div><!-- ./smart-widget-inner -->
        </div>
    </div><!-- ./padding-md -->
</div><!-- /main-container -->
<!-- /wrapper -->

<a href="#" class="scroll-to-top hidden-print"><i class="fa fa-chevron-up fa-lg"></i></a>



<script>
    $(function() {


        //Wizard Step

        $("#formWizard").steps({
            headerTag: "h2",
            bodyTag: "section",
            transitionEffect: "slideLeft",
            onStepChanging: function(event, currentIndex, newIndex) {
                if (newIndex > currentIndex) {
                    if ($('#formExample').parsley().validate('step' + newIndex)) {
                        return true;
                    }
                    else {
                        return false;
                    }
                }
                else {
                    return true;
                }

            },
            onFinished: function(event, currentIndex) {
                $('#wizardModal').modal('show')
            }

        });
    });
</script>

