<div class="main-container">
    <div class="padding-md">
        <h3 class="header-text" style="margin-top: 0;">Edit Coupon</h3>
        <div class="smart-widget widget-dark-blue">
            <div class="smart-widget-header">
                <strong class="no-margin inline-block">Edit Coupon</strong>
            </div>
            <div class="smart-widget-inner">
                <div class="smart-widget-body">

                    <div class="row">
                        <div class="col-md-6 col-md-offset-3">
                            <form method="POST">
                                <div class="form-group" style="margin-top: 5%;">
                                    <label class="col-xs-3 control-label m-top-xs">Name *</label>
                                    <div class="input-group col-xs-9">
                                        <input type="text" name="editcouponname" value="<?php
                                        if (isset($this->couponinfo)) {
                                            echo $this->couponinfo['coupon_name'];
                                        }
                                        ?>" class="form-control">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-xs-3 control-label m-top-xs">Coupon Code *</label>
                                    <div class="input-group col-xs-9">
                                        <input type="text"  name="editcouponcode" value="<?php
                                        if (isset($this->couponinfo)) {
                                            echo $this->couponinfo['coupon_code'];
                                        }
                                        ?>"class="form-control">
                                    </div>
                                </div>
                                <div class="form-group" style="display:flex;">
                                    <label class="col-xs-3 control-label m-top-xs">Discount *</label>
                                    <div class="input-group col-xs-5">
                                        <input type="text"  name="editcoupondiscount" value="<?php
                                        if (isset($this->couponinfo)) {
                                            echo $this->couponinfo['discount_offered'];
                                        }
                                        ?>" class="form-control">

                                    </div>
                                    <div class="input-group col-xs-3 col-xs-offset-1">
                                        <select class="form-control" name="editdiscounttype">
                                            <option value="0" <?php
                                            if ($this->couponinfo['discount_type'] == 0) {
                                                echo "selected";
                                            }
                                            ?>>% OFF</option>
                                            <option value="1" <?php
                                            if ($this->couponinfo['discount_type'] == 1) {
                                                echo "selected";
                                            }
                                            ?>>$ OFF</option>
                                        </select>
                                    </div>

                                </div>
                                <div class="d-divider"></div>
                                <div class="form-group">
                                    <label class="col-xs-3 control-label m-top-xs">Subscriptions Options</label>
                                    <div class="input-group col-xs-7">
                                        <label class="rd1">
                                            <input type="radio" <?php
                                            if ($this->couponinfo['coupon_type'] == 0) {
                                                echo "checked";
                                            }
                                            ?> value ="0" name="editsubscriptionoffers" id="rd1">
                                            <span>Apply Discount to First Charge only </span>
                                        </label>
                                        <label class="rd2">
                                            <input type="radio" <?php
                                            if ($this->couponinfo['coupon_type'] == 1) {
                                                echo "checked";
                                            }
                                            ?> value="1" name="editsubscriptionoffers" id="rd2">
                                            <span>Apply Discount to All Charges</span>
                                        </label>
                                    </div>
                                </div>
                                <div class="d-divider"></div>
                                <div class="form-group">
                                    <label class="col-xs-3 control-label m-top-xs">Restrictions</label>
                                    <div class="input-group col-xs-9">
                                        <div class="block row">
                                            <label class="col-xs-3 m-top-xs">Start Date</label>
                                            <div class="col-xs-9">
                                                <input placeholder="Start Date" name="editcouponstartdate" value="<?php
                                            if (isset($this->couponinfo)) {
                                                echo $this->couponinfo['coupon_startdate'];
                                            }
                                            ?>" data-provide="datepicker" class="thisdate form-control" >	
                                            </div>
                                        </div>
                                        <div class="block row m-top-xs">
                                            <label class="col-xs-3 m-top-xs">End Date</label>
                                            <div class="col-xs-9">
                                                <input  placeholder="End Date"  value="<?php
                                            if (isset($this->couponinfo)) {
                                                echo $this->couponinfo['coupon_enddate'];
                                            }
                                            ?>" name="editcouponenddate"  data-provide="datepicker" class="thisdate form-control">	
                                            </div>
                                        </div>
                                        <div class="block row m-top-xs">
                                            <label class="col-xs-3 m-top-xs">Limit</label>
                                            <div class="col-xs-9">


                                                <input type="text"  name="editcouponlimit" value="<?php
                                            if (isset($this->couponinfo)) {
                                                echo $this->couponinfo['coupon_limit'];
                                            }
                                            ?>" class="form-control">
                                            </div>
                                        </div>

                                    </div>
                                </div>
                                <button  type ="submit" class="btn btn-success">Save Changes</button>
                                <a href = "/admin/coupons" class="btn btn-danger">Cancel</a>
                            </form>

                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function() {

        $('.thisdate').datepicker();
    });
</script>