<div class="main-container">
    <div class="padding-md">
        <h3 class="header-text m-top-lg"><?php echo $this->translate("MemberShip Plans") ?></h3>

        <div class="smart-widget">
            <div class="smart-widget-header">
                <?php echo $this->translate("All Plans") ?>

            </div>
            <div class="smart-widget-inner">
                <div class="smart-widget-hidden-section">
                    <ul class="widget-color-list clearfix">
                        <li style="background-color:#20232b;" data-color="widget-dark"></li>
                        <li style="background-color:#4c5f70;" data-color="widget-dark-blue"></li>
                        <li style="background-color:#23b7e5;" data-color="widget-blue"></li>
                        <li style="background-color:#2baab1;" data-color="widget-green"></li>
                        <li style="background-color:#edbc6c;" data-color="widget-yellow"></li>
                        <li style="background-color:#fbc852;" data-color="widget-orange"></li>
                        <li style="background-color:#e36159;" data-color="widget-red"></li>
                        <li style="background-color:#7266ba;" data-color="widget-purple"></li>
                        <li style="background-color:#f5f5f5;" data-color="widget-light-grey"></li>
                        <li style="background-color:#fff;" data-color="reset"></li>
                    </ul>
                </div>
                <div class="smart-widget-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th><?php echo $this->translate("S.No") ?></th>
                                <th><?php echo $this->translate("Plan Type") ?></th>
                                <th><?php echo $this->translate("Amount") ?></th>
                                <th><?php echo $this->translate("Duration(Days)") ?></th>
                                <th><?php echo $this->translate("Trial(Days)") ?></th>
                                <th><?php echo $this->translate("Edit") ?></th>

                            </tr>
                        </thead>
                        <tbody id="cleardata">
                            <?php
                            if (isset($this->subResult)) {
                                $i = 1;
                                foreach ($this->subResult as $subResultVal) {
                                    ?>

                                    <tr class="userdet">
                                        <td><?php echo $i; ?></td>
                                        <td><?php if($subResultVal['plan_type_id']==1){ echo "Monthly";}else{ echo "Yearly";}?></td>
                                        <td class="payment_ammount"><input class="ammount_edit" type="text" value="<?php echo $subResultVal['amount']; ?>" style="display:none"><a id="ammount"><?php echo $subResultVal['amount']; ?></a></td>
                                        <td class="payment_period"><input type="text" class="period" value="<?php echo $subResultVal['subscription_period']; ?>" style="display:none"><a id="duration"><?php echo $subResultVal['subscription_period']; ?></a></td>
                                        <td class="trial_duration"><input type="text" class="trailperiod" value="<?php echo $subResultVal['trail_days']; ?>" style="display:none"><a id="trial_period"><?php echo $subResultVal['trail_days']; ?></a></td>
                                        <td>
                                           <a class ="edit_<?php echo $subResultVal['plan_type_id']; ?> editplan" data-val="<?php echo $subResultVal['plan_type_id']; ?>"  ><button class="btn btn-info btn-sm"> <i class="fa fa-pencil"></i></button></a>
                                           <a class="edited" data-val="<?php echo $subResultVal['plan_type_id']; ?>" style="hover:pointer; display:none"><button class="btn btn-success btn-sm"><i class="fa fa-check"></i></button></a>
                                        </td>
                                    </tr>
                                    <?php $i++; ?>
                                    <?php
                                }
                            }
                            ?>

                        </tbody>
                    </table>
              
                </div>
            </div><!-- ./smart-widget-inner -->
        </div><!-- ./smart-widget -->

    </div><!-- ./padding-md -->
</div><!-- /main-container -->



<a href="#" class="scroll-to-top hidden-print"><i class="fa fa-chevron-up fa-lg"></i></a>

<script>
    //script used for editing the plans /////////////////////////
      $('.editplan').on('click', function () {
           $(this).css('display', 'none');
            $(this).siblings('.edited').css('display', 'block');
            $(this).parent().siblings('.payment_ammount').children('.ammount_edit').css('display', 'block');
            $(this).parent().siblings('.payment_ammount').children('#ammount').css('display', 'none');
            $(this).parent().siblings('.payment_period').children('.period').css('display', 'block');
            $(this).parent().siblings('.payment_period').children('#duration').css('display', 'none');
            $(this).parent().siblings('.trial_duration').children('.trailperiod').css('display', 'block');
            $(this).parent().siblings('.trial_duration').children('#trial_period').css('display', 'none');
    });
            $('.edited').on('click', function () {
    var click_this = $(this);
             var ammount = $(this).parent().siblings('.payment_ammount').children('.ammount_edit').val();
             var duration = $(this).parent().siblings('.payment_period').children('.period').val();
             var trailperiod = $(this).parent().siblings('.trial_duration').children('.trailperiod').val();
            var subscription_id = $(this).attr('data-val');
            $.ajax({
            url: '/admin/edit-plans',
                    type: 'POST',
                    data: {
                    trial_duration: trailperiod,
                            sid: subscription_id,
                            amount: ammount,
                            duration: duration
                    },
                    beforeSend: function () {

                    },
                    success: function (response) {
                    if (response) {
                       location.reload();

                    }
                    }

            });
    });

    </script>






<script>
    //////////////////////////code not needed/////////////////////////////////////////////////////
    $('#membershippanel').addClass('active');
            $(document.body).on('click', '#deletemem', function () {
    var deletesub = $(this).attr('data-val');
            $("#Deletemembershipmodal").modal('show');
            $(document.body).on('click', '#ok', function () {
    $("#Deletemembershipmodal").modal('hide');
            if (deletesub) {
    $.ajax({
    url: '/admin/membership-ajax-handler',
            type: 'POST',
            datatype: 'json',
            data: {
            delsubscripton: deletesub
            },
            beforeSend: function () {
            console.log('delete subcription');
            },
            success: function (response) {
            if (response) {
            $('.' + "delete_" + response).parent().parent().remove();
            }
            }

    });
    }
    });
    });
          

            $('.addplans').on('click', function(){

    $("#cleardata").append("<tr class='userdet' id='userdet'><td></td><td id='plan_name'><input type='text'></td><td id='plan_amount'><input type='text'></td><td id='plan_dur'><input type='text'></td><td id='plan_trial'><input type='text'></td></tr>");
            $(this).css('display', 'none');
            $(this).siblings('.save').removeAttr('style');
            $(this).siblings('.cancel').removeAttr('style');
    });
    
    
    
   $('.save').on('click', function(){
   $planname= $('#userdet').children('#plan_name').children().val();
   $amount= $('#userdet').children('#plan_amount').children().val();
   $trial= $('#userdet').children('#plan_trial').children().val();
   $duration= $('#userdet').children('#plan_dur').children().val();
    $.ajax({
    url:'/admin/create-plans',
            type:'POST',
            data:{
            planname:$planname,
            amount:$amount,
            duration:$duration,
            trial:$trial

            },
            success:function(response){
           location.reload();
            }

    });

    });
    $('.cancel').on('click',function(){
        
        $('#userdet').hide();
    });
   ////////////////////////////////////////code ends ////////////////////////////////
</script>


