<style>
    th {
        font-size: 14px;
    }
    td {
        font-size: 12px;
    }
</style>
<div class="main-container">
    <div class="padding-md">
        <h3 class="header-text m-top-lg"><?php echo $this->translate("Transaction Details") ?></h3>
        <div role="tabpanel">
            <ul role="tablist" class="nav nav-tabs">
                <li class="active" role="presentation">
                    <a data-toggle="tab" role="tab" aria-controls="credit" href="#credit"> Credit Card Transactions</a>
                </li>
                <li role="presentation">
                    <a data-toggle="tab" role="tab" aria-controls="boleto" href="#boleto"> Boleto Transactions </a>
                </li>
                 <li role="presentation">
                    <a data-toggle="tab" role="tab" aria-controls="boletocancel" href="#boletocancel"> Boleto Canceled Transactions </a>
                </li>
            </ul>
            <div class="tab-content">
                <div id="credit" class="tab-pane active" role="tabpanel">
                    <div class="smart-widget" style="margin-top: 1%;">
                        <div class="smart-widget-header">
                            <?php echo $this->translate("All Plans") ?>
                        </div>
                        <div class="smart-widget-inner">
                            <div class="smart-widget-body">
                                <table class="table table-hover" id="AllplansTable">
                                    <thead>
                                        <tr>
                                            <th><?php echo $this->translate("S.No") ?></th>
                                            <th><?php echo $this->translate("User Name") ?></th>
                                            <th><?php echo $this->translate("Transaction id") ?></th>
                                            <th><?php echo $this->translate("Amount") ?></th>
                                            <th><?php echo $this->translate("Date") ?></th>
                                            <th><?php echo $this->translate("Finger Print") ?></th>
                                            <th><?php echo $this->translate("Status") ?></th>
                                            <th><?php echo $this->translate("Reason") ?></th>
                                        </tr>
                                    </thead>
                                    <tbody id="cleardata">
                                        <?php if (isset($this->alltransactioninfo)) {
                                            $row = 0;
                                            foreach ($this->alltransactioninfo as $transdetails) {
                                                $row ++; ?>
                                                <tr>
                                                    <td><?php echo $row; ?></td>
                                                    <td><?php echo $transdetails['first_name'] . $transdetails['last_name']; ?></td>
                                                    <td><?php echo $transdetails['transaction_id']; ?></td>
                                                    <td><?php echo $transdetails['amount']; ?></td>
                                                    <td><?php echo date("F j, Y", strtotime($transdetails['transaction_date'])); ?></td>
                                                    <td><?php echo $transdetails['finger_print']; ?></td>
                                                    <td><?php echo $transdetails['status']; ?></td>
                                                    <td><?php echo $transdetails['status_reason']; ?></td>
                                                </tr>
    <?php }
} ?>
                                    </tbody>
                                </table>
                            </div>
                        </div><!-- ./smart-widget-inner -->
                    </div><!-- ./smart-widget -->
                </div> 
                <div id="boleto" class="tab-pane" role="tabpanel">
                    <div class="smart-widget" style="margin-top: 1%;">
                        <div class="smart-widget-header">
                            <?php echo $this->translate("All Plans") ?>
                        </div>
                        <div class="smart-widget-inner">
                            <div class="smart-widget-body">
                                <table class="table table-hover" id="BoletotransTable">
                                    <thead>
                                        <tr>
                                            <th><?php echo $this->translate("S.No") ?></th>
                                            <th><?php echo $this->translate("User Name") ?></th>
                                            <th><?php echo $this->translate("Transaction id") ?></th>
                                            <th><?php echo $this->translate("Amount") ?></th>
                                            <th><?php echo $this->translate("Date") ?></th>
                                            <th><?php echo $this->translate("Boleto Url") ?></th>
                                            <th><?php echo $this->translate("Boleto Barcode") ?></th>
                                            <th><?php echo $this->translate("Boleto expdate") ?></th>
                                            <th><?php echo $this->translate("Status") ?></th>
                                            <th><?php echo $this->translate("Reason") ?></th>
                                        </tr>
                                    </thead>
                                    <tbody id="cleardata">
                                        <?php if (isset($this->alltransactionboletoinfo)) {
                                            $row = 0;
                                            foreach ($this->alltransactionboletoinfo as $transdetails) {
                                                $row ++; ?>
                                                <tr>
                                                    <td><?php echo $row; ?></td>
                                                    <td><?php echo $transdetails['first_name'] . $transdetails['last_name']; ?></td>
                                                    <td><?php echo $transdetails['transaction_id']; ?></td>
                                                    <td><?php echo $transdetails['amount']; ?></td>
                                                    <td><?php echo date("F j, Y", strtotime($transdetails['transaction_date'])); ?></td>
                                                    <td><?php echo $transdetails['boleto_url']; ?></td>
                                                    <td><?php echo $transdetails['boleto_barcode']; ?></td>
                                                    <td><?php echo date("F j, Y", strtotime($transdetails['boleto_expdate'])); ?></td>
                                                    <td><?php echo $transdetails['status']; ?></td>
                                                    <td><?php echo $transdetails['status_reason']; ?></td>
                                                </tr>
    <?php }
} ?>
                                    </tbody>
                                </table>
                            </div>
                        </div><!-- ./smart-widget-inner -->
                    </div><!-- ./smart-widget -->
                </div>
                
                      <div id="boletocancel" class="tab-pane" role="tabpanel">
                    <div class="smart-widget" style="margin-top: 1%;">
                        <div class="smart-widget-header">
                            <?php echo $this->translate("All Plans") ?>
                        </div>
                        <div class="smart-widget-inner">
                            <div class="smart-widget-body">
                                <table class="table table-hover" id ="canceledtransTable">
                                    <thead>
                                        <tr>
                                            <th><?php echo $this->translate("S.No") ?></th>
                                            <th><?php echo $this->translate("User Name") ?></th>
                                            <th><?php echo $this->translate("Transaction id") ?></th>
                                            <th><?php echo $this->translate("Amount") ?></th>
                                            <th><?php echo $this->translate("Date") ?></th>
                                            <th><?php echo $this->translate("Boleto Url") ?></th>
                                            <th><?php echo $this->translate("Boleto Barcode") ?></th>
                                            <th><?php echo $this->translate("Boleto expdate") ?></th>
                                            <th><?php echo $this->translate("Status") ?></th>
                                            <th><?php echo $this->translate("Reason") ?></th>
                                        </tr>
                                    </thead>
                                    <tbody id="cleardata">
                                        <?php if (isset($this->transactionsboletocanceledinfo)) {
                                            $row = 0;
                                            foreach ($this->transactionsboletocanceledinfo as $transdetails) {
                                                $row ++; ?>
                                                <tr>
                                                    <td><?php echo $row; ?></td>
                                                    <td><?php echo $transdetails['first_name'] . $transdetails['last_name']; ?></td>
                                                    <td><?php echo $transdetails['transaction_id']; ?></td>
                                                    <td><?php echo $transdetails['amount']; ?></td>
                                                    <td><?php echo date("F j, Y", strtotime($transdetails['transaction_date'])); ?></td>
                                                    <td><?php echo $transdetails['boleto_url']; ?></td>
                                                    <td><?php echo $transdetails['boleto_barcode']; ?></td>
                                                    <td><?php echo date("F j, Y", strtotime($transdetails['boleto_expdate'])); ?></td>
                                                    <td><?php echo $transdetails['status']; ?></td>
                                                    <td><?php echo $transdetails['status_reason']; ?></td>
                                                </tr>
    <?php }
} ?>
                                    </tbody>
                                </table>
                            </div>
                        </div><!-- ./smart-widget-inner -->
                    </div><!-- ./smart-widget -->
                </div>         
                
            </div>
        </div>


    </div><!-- ./padding-md -->
</div><!-- /main-container -->
<script>
   $(function() {
        $('#canceledtransTable').dataTable();
    });
    
       $(function() {
        $('#BoletotransTable').dataTable();
    });
         $(function() {
        $('#AllplansTable').dataTable();
    });
    
</script>



