        
        
<!--<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.4/css/jquery.dataTables.css">-->

<!--<script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.10.2.min.js"></script>-->
  

<!--<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.4/js/jquery.dataTables.js"></script>-->
<div class="main-container">
    <div class="padding-md m-bottom-md">

        <h3 class="header-text m-top-lg" style="margin-top:2px"><?php echo $this->translate("Categories Details") ?></h3>
      
           
        <div class="form-group col-lg-4 col-md-4 col-sm-4 pull-right">
  <input type="text" name="addcategory" placeholder="<?php echo $this->translate("Add catgory") ?>" class="" id="addcategory" style="padding: 5px 10px; height: 30px;">
 <button id="add" class="btn btn-success btn-sm" ><?php echo $this->translate("AddCategory") ?></button>
  </div>
     <table class="table table-striped" id="dataTable"  class="display">
            <thead>
                <tr>
                    <th><?php echo $this->translate("Category id") ?></th>
                    <th><?php echo $this->translate("Category Name") ?></th>
                    <th><?php echo $this->translate("Edit/Delete") ?></th>

                </tr>
            </thead>
            <tbody>
                <?php if (isset($this->categories)) {
                    $i = 1;
                    foreach ($this->categories as $value) { ?>

                        <tr>
                            <td><?php echo $i; ?></td>
                            <td><?php echo $value['category_name']; ?></td>
                            <td colspan="2"><a href="edit-category/<?php echo $value['category_id']; ?>"><button class="btn btn-success btn-sm"><?php echo $this->translate("Edit") ?></button></a> &nbsp;<a class="delete_<?php echo $value['category_id']; ?>" data-val="<?php echo $value['category_id']; ?>" id ="delete" ><button class="btn btn-danger btn-sm"> &nbsp;&nbsp;<?php echo $this->translate("Delete") ?></button></a></td>

        <?php $i++;
    }
} ?>


            </tbody>
        </table>
    </div><!-- ./padding-md -->
</div><!-- /main-container -->

</div><!-- /wrapper -->

<a href="#" class="scroll-to-top hidden-print"><i class="fa fa-chevron-up fa-lg"></i></a>

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<!-- Jquery -->



<script type="text/javascript" language="javascript">    
    
    $(document).ready(function() {
     
	$('#dataTable').dataTable();
      
       
    });
    

//dev:priyanka varanasi                 
//desc: to delete category
    $(document.body).on('click', '#delete', function() {

        var deleteid = $(this).attr('data-val');

        $("#Deletecategory").modal('show');
        $(document.body).on('click', '#ok', function() {
            $("#Deletecategory").modal('hide');
            if (deleteid) {
                $.ajax({
                    url: './category-ajax-handler',
                    type: 'POST',
                    datatype: 'json',
                    data: {
                        method: 'categorydelete',
                        categoryid: deleteid
                    },
                    beforeSend: function() {

                    },
                    success: function(response) {
                        if (response) {
                            $('.' + "delete_" + response).parent().parent().remove();

                        }
                    }

                });

            }


        });
    });
    
    //dev: to add category
    //dev: priyanka varanasi
    
    $(document.body).on('click', '#add', function() {
      var add = $("#addcategory").val();
       $.ajax({
                    url: './category-ajax-handler',
                    type: 'POST',
                    datatype: 'json',
                    data: {
                        method: 'addcategory',
                        categoryname: add
                    },
                    beforeSend: function() {

                    },
                    success: function(response) {
                      window.location.reload(true);
                    }
                    });
     
    });
    
</script>

