<div class="main-container">
				<div class="padding-md m-bottom-md">
<h3 class="header-text m-top-lg"><?php echo $this->translate("Projects Details") ?></h3>
					<table class="table table-striped" id="dataTable">
						<thead>
							<tr>
                                                            <th><?php echo $this->translate("Category name") ?></th>
                                                            <th><?php echo $this->translate("Class Name") ?></th>
                                                            <th><?php echo $this->translate("Project Title") ?></th>
					                    <th><?php echo $this->translate("Project Description") ?></th>
						            <th><?php echo $this->translate("Image") ?></th>
							    <th><?php echo $this->translate("Username") ?></th>
						            <th colspan="2"><?php echo $this->translate("Edit/Delete") ?></th>
								
							</tr>
						</thead>
						<tbody>
                                                    <?php if(isset($this->projectresult)){ $i= 1; foreach ($this->projectresult as $value) { ?>
     
 
							<tr>     <td><?php echo ($value['category_name']);?></td>
								<td><?php echo ($value['class_title']);?></td>
								<td style="padding: 5px;"><?php echo ($value['project_title']);?></td>
								<td><a class="button" href="edit-projects/<?php echo $value['project_id']; ?>"><button class="btn btn-primary btn-sm" type="button"><?php echo $this->translate("click to view") ?></button>
</a></td>
								<td><img src="<?php echo ($value['project_cover_image']);?>" class="img-responsive prj_image"  alt=""/></td>
								<td><?php echo ($value['first_name']);?></td>
                                                                <td colspan="2" style="padding: 5px;"><a style="float:left; margin-right: 2px;"href="edit-projects/<?php echo $value['project_id']; ?>"><button class="btn btn-success btn-sm"><?php echo $this->translate("Edit") ?></button></a>
                                                                <a class="delete_<?php echo $value['project_id']; ?>" data-val="<?php echo $value['project_id']; ?>" id ="delete" ><button class="btn btn-danger btn-sm"><?php echo $this->translate("Delete") ?></button></a></td>
								
							</tr>
                                                    <?php  $i++; } }?>	
						</tbody>
					</table>
				</div><!-- ./padding-md -->
			</div><!-- /main-container -->

                        <a href="#" class="scroll-to-top hidden-print"><i class="fa fa-chevron-up fa-lg"></i></a>
  	
                                
                          

     
     <script type="text/javascript" language="javascript">    
    $('#projectdetailsli').addClass("active");
    $(document).ready(function() {
     
	$('#dataTable').dataTable( {

	});
    } );
    
//dev:priyanka varanasi
//desc:To delete the projects

$(document.body).on('click','#delete',function(){
    
   var deleteid = $(this).attr('data-val');
  $("#Deleteprojectmodal").modal('show');
 $(document.body).on('click','#ok',function(){ 
     $("#Deleteprojectmodal").modal('hide');
     if(deleteid){
                    $.ajax({
                            url:  './project-ajax-handler',
                            type: 'POST',
                            datatype: 'json',
                            data:{
                            method : 'projectdelete',
                            projectid: deleteid
                            },
                            beforeSend : function() {

                            },
                             success : function(response) { 
                               if(response){
                                    $('.'+"delete_"+response).parent().parent().remove();
                                    
                                 } 
                             }
                             
                        });
                    
     }
   
  
 });
});
</script>